const pool = require('../config/db');
const withTransaction = require('../utils/withTransaction');

class MaintenanceRepository {
  constructor(db = pool) { this.db = db; }
  transaction(work) { return withTransaction(client => work(new MaintenanceRepository(client)), { pool: this.db }); }
  async equipment(id, instituteId, lock = false) { const r=await this.db.query(`SELECT * FROM maintainable_equipment WHERE id=$1 AND institute_id=$2${lock?' FOR UPDATE':''}`,[id,instituteId]);return r.rows[0]||null; }
  async coverage(id,equipmentId,instituteId){if(!id)return null;const r=await this.db.query('SELECT * FROM contract_equipment_coverage WHERE id=$1 AND equipment_id=$2 AND institute_id=$3',[id,equipmentId,instituteId]);return r.rows[0]||null;}
  async assignee(id,instituteId){if(!id)return null;const r=await this.db.query('SELECT id FROM users WHERE id=$1 AND institute_id=$2 AND is_active=true',[id,instituteId]);return r.rows[0]||null;}
  async list(instituteId,{equipment_id,status,limit=50}={}){limit=Math.min(100,Math.max(1,Number(limit)||50));const values=[instituteId],where=['wo.institute_id=$1'];if(equipment_id){values.push(equipment_id);where.push(`wo.equipment_id=$${values.length}`);}if(status){values.push(status);where.push(`wo.status=$${values.length}`);}values.push(limit);const r=await this.db.query(`SELECT wo.*,e.equipment_code,a.asset_number,a.description equipment_name,c.contract_id,
    count(p.id)::int part_line_count FROM maintenance_work_orders wo JOIN maintainable_equipment e ON e.id=wo.equipment_id
    LEFT JOIN assets a ON a.id=e.asset_id LEFT JOIN contract_equipment_coverage c ON c.id=wo.coverage_id
    LEFT JOIN maintenance_work_order_parts p ON p.work_order_id=wo.id WHERE ${where.join(' AND ')}
    GROUP BY wo.id,e.equipment_code,a.asset_number,a.description,c.contract_id ORDER BY wo.requested_at DESC LIMIT $${values.length}`,values);return r.rows;}
  async get(id,instituteId,lock=false){const r=await this.db.query(`SELECT * FROM maintenance_work_orders WHERE id=$1 AND institute_id=$2${lock?' FOR UPDATE':''}`,[id,instituteId]);return r.rows[0]||null;}
  async create(data,instituteId,actorId){const keys=Object.keys(data);const r=await this.db.query(`INSERT INTO maintenance_work_orders(institute_id,work_order_number,${keys.join(',')},created_by,updated_by) VALUES($1,next_maintenance_work_order_number($1),${keys.map((_,i)=>`$${i+2}`).join(',')},$${keys.length+2},$${keys.length+2}) RETURNING *`,[instituteId,...keys.map(k=>data[k]),actorId]);return r.rows[0];}
  async transition(id,instituteId,data,version,actorId){const keys=Object.keys(data);const r=await this.db.query(`UPDATE maintenance_work_orders SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')},updated_by=$${keys.length+1},updated_at=now(),row_version=row_version+1 WHERE id=$${keys.length+2} AND institute_id=$${keys.length+3} AND row_version=$${keys.length+4} RETURNING *`,[...keys.map(k=>data[k]),actorId,id,instituteId,version]);return r.rows[0]||null;}
  async spareForEquipment(spareId,equipmentId,instituteId){const r=await this.db.query(`SELECT s.id,s.stock_item_id,s.is_serialized,s.technical_approval_status FROM approved_spare_parts s
    JOIN spare_part_equipment_compatibility c ON c.spare_part_id=s.id AND c.equipment_id=$2 AND c.compatibility_status='APPROVED'
    WHERE s.id=$1 AND s.institute_id=$3 AND s.lifecycle_status='ACTIVE'`,[spareId,equipmentId,instituteId]);return r.rows[0]||null;}
  async addPart(workOrderId,data,instituteId,actorId){const keys=Object.keys(data);const r=await this.db.query(`INSERT INTO maintenance_work_order_parts(institute_id,work_order_id,${keys.join(',')},created_by) VALUES($1,$2,${keys.map((_,i)=>`$${i+3}`).join(',')},$${keys.length+3}) RETURNING *`,[instituteId,workOrderId,...keys.map(k=>data[k]),actorId]);return r.rows[0];}
  async parts(workOrderId,instituteId){const r=await this.db.query(`SELECT p.*,s.spare_part_code,s.name spare_part_name FROM maintenance_work_order_parts p JOIN approved_spare_parts s ON s.id=p.spare_part_id WHERE p.work_order_id=$1 AND p.institute_id=$2 ORDER BY p.created_at`,[workOrderId,instituteId]);return r.rows;}
  async part(id,workOrderId,instituteId,lock=false){const r=await this.db.query(`SELECT p.*,wo.status work_order_status FROM maintenance_work_order_parts p JOIN maintenance_work_orders wo ON wo.id=p.work_order_id AND wo.institute_id=p.institute_id WHERE p.id=$1 AND p.work_order_id=$2 AND p.institute_id=$3${lock?' FOR UPDATE OF p':''}`,[id,workOrderId,instituteId]);return r.rows[0]||null;}
  async updatePart(id,instituteId,data){const keys=Object.keys(data);const r=await this.db.query(`UPDATE maintenance_work_order_parts SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')},updated_at=now() WHERE id=$${keys.length+1} AND institute_id=$${keys.length+2} RETURNING *`,[...keys.map(k=>data[k]),id,instituteId]);return r.rows[0]||null;}
  async inventoryOperation(partId,type,key,instituteId){const r=await this.db.query('SELECT * FROM maintenance_part_inventory_operations WHERE work_order_part_id=$1 AND operation_type=$2 AND idempotency_key=$3 AND institute_id=$4',[partId,type,key,instituteId]);return r.rows[0]||null;}
  async addInventoryOperation(partId,type,quantity,key,reservationId,movementId,instituteId,actorId){const r=await this.db.query(`INSERT INTO maintenance_part_inventory_operations(institute_id,work_order_part_id,operation_type,quantity,idempotency_key,reservation_id,inventory_movement_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[instituteId,partId,type,quantity,key,reservationId||null,movementId||null,actorId]);return r.rows[0];}
  async activePartReservations(workOrderId,instituteId){const r=await this.db.query(`SELECT p.id,p.reservation_id,r.quantity,r.consumed_quantity FROM maintenance_work_order_parts p JOIN inventory_reservations r ON r.id=p.reservation_id AND r.status='ACTIVE' WHERE p.work_order_id=$1 AND p.institute_id=$2`,[workOrderId,instituteId]);return r.rows;}
}
module.exports=MaintenanceRepository;