'use strict';

const express=require('express');const request=require('supertest');
const {createAiRouter}=require('../modules/ai-intelligence/routes');
const {AiToolRegistry}=require('../modules/ai-intelligence/aiToolRegistry');
const {AiService}=require('../modules/ai-intelligence/aiService');
const {OpenAiProvider}=require('../modules/ai-intelligence/aiProviderService');
const {createTools,coverage}=require('../modules/ai-intelligence/tools');

const user={id:7,institute_id:3,department_id:4,permissions:['ai-intelligence.use','procurement-performance.view','requests.view-all'],data_scopes:{institute_ids:['3']}};
const audit=()=>({start:jest.fn().mockResolvedValue(11),finish:jest.fn().mockResolvedValue(),tool:jest.fn().mockResolvedValue()});
const makeRegistry=(tools,auditService=audit())=>new AiToolRegistry({tools,auditService});
const appFor=(service,authenticated=true)=>{const app=express();app.use(express.json());app.use('/api/ai',(req,_res,next)=>{if(authenticated){req.user=user;return next();}const e=new Error('Authentication required');e.statusCode=401;next(e);},createAiRouter({service}));app.use((e,_req,res,_next)=>res.status(e.statusCode||500).json({code:e.code,message:e.message}));return app;};

describe('AI Intelligence read-only foundation',()=>{
  test('unauthenticated AI request is rejected',async()=>{const response=await request(appFor({chat:jest.fn()},false)).post('/api/ai/chat').send({message:'hello'});expect(response.status).toBe(401);});
  test('authorized user is allowed and stable response contract is returned',async()=>{const service={chat:jest.fn().mockResolvedValue({conversationId:'c',message:'ok',sources:[],toolsUsed:[],warnings:[],coverage:{},suggestedActions:[]})};const response=await request(appFor(service)).post('/api/ai/chat').send({message:'hello'});expect(response.status).toBe(200);expect(response.body.suggestedActions).toEqual([]);});
  test('unknown tool and malformed parameters are rejected',async()=>{const registry=makeRegistry({get_request_summary:{execute:jest.fn()}});await expect(registry.execute({name:'delete_supplier',parameters:{},context:{...user,userId:7,instituteIds:[3]},interactionId:1})).rejects.toMatchObject({code:'AI_UNKNOWN_TOOL'});await expect(registry.execute({name:'get_request_summary',parameters:{requestId:'bad'},context:{...user,userId:7,instituteIds:[3]},interactionId:1})).rejects.toMatchObject({code:'AI_INVALID_PARAMETERS'});});
  test('no mutation tool is registered',()=>{const names=Object.keys(createTools({query:jest.fn()}));expect(names).toEqual(expect.arrayContaining(['get_request_summary','get_pending_approvals','get_procurement_cases','get_supplier_summary','get_supply_chain_kpis','get_attention_items']));expect(names.some(name=>/(create|update|delete|approve|reject|post|pay)/i.test(name))).toBe(false);});
  test('oversized tool results are rejected before reaching a model',async()=>{const auditService=audit();const registry=new AiToolRegistry({tools:{get_pending_approvals:{execute:jest.fn().mockResolvedValue({data:'x'.repeat(2000)})}},auditService,maxResultBytes:1024});await expect(registry.execute({name:'get_pending_approvals',parameters:{},context:{...user,userId:7,instituteIds:[3]},interactionId:1})).rejects.toMatchObject({code:'AI_TOOL_RESULT_TOO_LARGE'});});
  test('supplier outside institute-scoped transactional evidence is blocked',async()=>{const database={query:jest.fn().mockResolvedValueOnce({rowCount:0,rows:[]})};await expect(createTools(database).get_supplier_summary.execute({supplierId:9},{instituteIds:[3]})).rejects.toMatchObject({code:'AI_RECORD_NOT_FOUND'});expect(database.query.mock.calls[0][1]).toEqual([[3],9]);});
  test('request and tools cannot escape institute data scope',async()=>{const database={query:jest.fn().mockResolvedValueOnce({rows:[],rowCount:0})};await expect(createTools(database).get_request_summary.execute({requestId:2},{userId:7,instituteIds:[3],permissions:[]})).rejects.toMatchObject({code:'AI_RECORD_NOT_FOUND'});expect(database.query.mock.calls[0][0]).toContain('r.institute_id = ANY');expect(database.query.mock.calls[0][1]).toEqual([2,[3],7]);});
  test('ambiguous supplier datasets fail closed while deterministic SRM links stay institute scoped',async()=>{const database={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[{}]}).mockResolvedValueOnce({rowCount:1,rows:[{id:9,name:'Scoped supplier'}]}).mockResolvedValue({rows:[],rowCount:0})};const result=await createTools(database).get_supplier_summary.execute({supplierId:9},{instituteIds:[3]});expect(result.data.supplier_evaluations).toEqual([]);expect(result.data.srm.compliance).toEqual([]);expect(result.coverage.supplier_evaluations.coverage).toBe('UNAVAILABLE');expect(result.coverage.supplier_compliance_artifacts.coverage).toBe('UNAVAILABLE');expect(result.warnings.join(' ')).toContain('omitted');const sql=database.query.mock.calls.map(call=>call[0]).join('\n');expect(sql).not.toMatch(/FROM supplier_evaluations/);expect(sql).not.toMatch(/FROM supplier_compliance_artifacts/);expect(sql).toContain('direct_request.institute_id=ANY');});
  test('provider unavailable and timeout are controlled errors',async()=>{await expect(new OpenAiProvider({apiKey:'',model:'',environment:{}}).respond({tools:[]})).rejects.toMatchObject({code:'AI_PROVIDER_CONFIGURATION_ERROR',statusCode:503});const fetch=jest.fn((_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})))));await expect(new OpenAiProvider({apiKey:'x',model:'test-model',timeoutMs:1000,fetch}).respond({systemInstruction:'x',message:'x',tools:[],executeTool:jest.fn()})).rejects.toMatchObject({code:'AI_PROVIDER_TIMEOUT',statusCode:504});},2000);
  test('interaction and tool execution audits are created',async()=>{const auditService=audit();const tool={description:'read',parameters:{type:'object',properties:{},additionalProperties:false},execute:jest.fn().mockResolvedValue({recordCount:1})};const registry=makeRegistry({get_pending_approvals:tool},auditService);const provider={name:'ollama',model:'test',respond:({executeTool})=>executeTool('get_pending_approvals',{}).then(()=>({message:'done'}))};const service=new AiService({provider,registry,auditService});await service.chat({user,request:{message:'x',conversationId:'c',context:{}}});expect(auditService.start).toHaveBeenCalledWith(expect.objectContaining({provider:'ollama',model:'test'}));expect(auditService.tool).toHaveBeenCalledWith(expect.objectContaining({toolName:'get_pending_approvals',success:true}));expect(auditService.finish).toHaveBeenCalledWith(11,'COMPLETED',expect.objectContaining({provider:'ollama',duration_ms:expect.any(Number)}));});
  test('currencies remain separate, coverage preserved, and missing is not zero',async()=>{const rows=[{activity_coverage:'PARTIAL',complexity_coverage:'MISSING',commercial_coverage:'LEGACY_INCOMPLETE',cycle_time_coverage:'MISSING',logistics_coverage:'MISSING'}];const metadata=coverage(rows);expect(metadata.commercial.coverage).toBe('LEGACY_INCOMPLETE');expect(metadata.complexity.usable_evidence_cases).toBe(0);const database={query:jest.fn().mockResolvedValueOnce({rows:rows.map((r,i)=>({...r,id:i+1,request_id:1,requested_item_id:1,case_status:'SOURCING',department_id:2,assigned_buyer_id:null,workload_units:null}))}).mockResolvedValueOnce({rows:[{pr_count:1,requested_item_count:1,departments_served:1}]}).mockResolvedValueOnce({rows:[{case_status:'SOURCING',count:1}]}).mockResolvedValueOnce({rows:[{value_type:'HARD_SAVINGS',currency:'USD',value:'10'},{value_type:'HARD_SAVINGS',currency:'EUR',value:'20'}]}).mockResolvedValueOnce({rows:[{rfqs:2,quotations:1}]})};const result=await createTools(database).get_supply_chain_kpis.execute({dateFrom:'2026-01-01',dateTo:'2026-12-31'},{instituteIds:[3]});expect(result.data.values_by_currency).toHaveLength(2);expect(result.data.median_approval_time).toBeNull();expect(result.coverage.commercial.coverage).toBe('LEGACY_INCOMPLETE');});
});