const e=require('../services/approvalPolicyEngine');
const step=(approvalLevel,stepOrder,resolverType,semanticKey,extra={})=>({approvalLevel,stepOrder,resolverType,semanticKey,...extra});
const version=steps=>({policy:{id:1},status:'SHADOW',rules:[{code:'BASE',priority:10,conditions:[],steps}]});
describe('approval policy shadow core',()=>{
test('controlled conditions cover true false unknown and exact decimals',()=>{expect(e.evaluateCondition({type:'AMOUNT_GTE',value:'9007199254740993.01'},{estimatedAmount:'9007199254740993.01'})).toBe(true);expect(e.evaluateCondition({type:'AMOUNT_LT',value:'0.10000000000000001'},{estimatedAmount:'0.1'})).toBe(true);expect(e.evaluateCondition({type:'DEPARTMENT_EQUALS',value:2},{departmentId:3})).toBe(false);expect(e.evaluateCondition({type:'SECTION_EQUALS',value:2},{sectionId:null})).toBe('UNKNOWN')});
test('validation fails malformed configuration',()=>expect(e.validateVersion({policy:{},rules:[{code:'X',priority:1,steps:[step(0,1,'BAD','')]}]}).valid).toBe(false));
test('combines priority rules and preserves parallel ordering',async()=>{const v={rules:[{code:'LATE',priority:20,conditions:[],steps:[step(3,1,'REQUESTER','THREE')]},{code:'BASE',priority:10,conditions:[],steps:[step(2,2,'REQUESTER','B',{parallelGroup:'P'}),step(2,1,'REQUESTER','A',{parallelGroup:'P'})]}]};const r=await e.composeShadowRoute(v,{requesterId:7},{organization:{}});expect(r.steps.map(x=>[x.approvalLevel,x.semanticKey])).toEqual([[2,'A'],[2,'B'],[3,'THREE']])});
test('dedupes same semantic only and reports duplicate principal',async()=>{const r=await e.composeShadowRoute(version([step(1,1,'REQUESTER','A'),step(2,1,'REQUESTER','A'),step(3,1,'REQUESTER','B')]),{requesterId:7},{organization:{}});expect(r.steps.map(x=>x.resolutionStatus)).toEqual(['RESOLVED','DEDUPLICATED','RESOLVED']);expect(e.compareApprovalRoutes([],r.steps).differences.some(x=>x.type==='DUPLICATE_PRINCIPAL')).toBe(true)});
test('missing and ambiguous authorities fail closed',async()=>{let r=await e.composeShadowRoute(version([step(1,1,'CEO_AUTHORITY','CEO')]),{}, {organization:{},resolveCapability:async()=>[]});expect(r.steps[0].resolutionStatus).toBe('UNRESOLVED');r=await e.composeShadowRoute(version([step(1,1,'CEO_AUTHORITY','CEO')]),{}, {organization:{},resolveCapability:async()=>[{userId:1},{userId:2}]});expect(r.steps[0].resolutionStatus).toBe('AMBIGUOUS')});
test('Nursing CEO to CMO move affects future route, not snapshot',async()=>{let parent='CEO';const people={CEO:{userId:1},CMO:{userId:2}};const deps={organization:{resolveDepartmentHead:async()=>({userId:3}),resolveExecutiveOwner:async()=>people[parent]},resolveCapability:async code=>[{userId:{'approval-authority.supply-chain':4,'approval-authority.coo':5,'approval-authority.ceo':1}[code]}]};const v=version([step(1,1,'DEPARTMENT_HEAD','DEPARTMENT_AUTHORIZATION'),step(2,1,'EXECUTIVE_OWNER','CLINICAL_EXECUTIVE_AUTHORIZATION'),step(3,1,'SUPPLY_CHAIN_AUTHORITY','SUPPLY_CHAIN_REVIEW'),step(4,1,'COO_AUTHORITY','COO_PR_AUTHORITY'),step(5,1,'CEO_AUTHORITY','CEO_POLICY_APPROVAL')]);const first=await e.composeShadowRoute(v,{departmentId:9},deps),snapshot=JSON.parse(JSON.stringify(first));parent='CMO';const second=await e.composeShadowRoute(v,{departmentId:9},deps);expect(first.steps.map(x=>x.userId)).toEqual([3,1,4,5,1]);expect(second.steps.map(x=>x.userId)).toEqual([3,2,4,5,1]);expect(snapshot.steps[1].userId).toBe(1);expect(first.steps.filter(x=>x.userId===1)).toHaveLength(2)});
test('normalizes legacy semantics and live routing is disabled',()=>{expect(e.normalizeCurrentRoute([{approval_level:1,approver_id:1}])[0].semanticKey).toBe('LEGACY_SEMANTIC_UNKNOWN');expect(e.LIVE_ROUTING_ENABLED).toBe(false)});
});