const mockQuery=jest.fn();jest.mock('../config/db',()=>({query:(...a)=>mockQuery(...a)}));
jest.mock('../repositories/approvalPolicyRepository',()=>({}));jest.mock('../services/auditService',()=>({writeAuditEvent:jest.fn()}));
const service=require('../services/approvalPolicyService'),actor={id:1,instituteId:7};
const version=steps=>({policy:{id:1},rules:[{id:2,code:'R',priority:1,conditions:[],steps}]});
const step=(resolverType,resolverReference,id=3)=>({id,resolverType,resolverReference,approvalLevel:1,stepOrder:1,semanticKey:`${resolverType}-${id}`});
beforeEach(()=>jest.clearAllMocks());
test('vacant effective POSITION is structurally valid but not currently routable',async()=>{mockQuery.mockResolvedValue({rows:[{id:8,user_id:null,is_active:true,unit_active:true}]});const result=await service.validateVersionReadiness(version([step('POSITION','9:DEPARTMENT_HEAD')]),actor);expect(result).toMatchObject({status:'WARNING',structurallyValid:true,currentlyRoutable:false,warnings:[{code:'POSITION_VACANT',stepId:3}]})});
test.each([
  [[], 'POSITION_MISSING_OR_INEFFECTIVE'],
  [[{id:1,user_id:4,is_active:false,unit_active:true,holder_active:true}],'POSITION_INACTIVE'],
  [[{id:1,user_id:4,is_active:true,unit_active:true,holder_active:true},{id:2,user_id:5,is_active:true,unit_active:true,holder_active:true}],'POSITION_AMBIGUOUS']
])('position readiness fails closed for invalid cardinality/state',async(rows,code)=>{mockQuery.mockResolvedValue({rows});const result=await service.validateVersionReadiness(version([step('POSITION','9:DEPARTMENT_HEAD')]),actor);expect(result.status).toBe('ERROR');expect(result.errors).toEqual(expect.arrayContaining([expect.objectContaining({code})]))});
test('fixed users are institute scoped and active',async()=>{mockQuery.mockResolvedValueOnce({rows:[{institute_id:7,is_active:true}]}).mockResolvedValueOnce({rows:[{institute_id:8,is_active:true}]});expect((await service.validateVersionReadiness(version([step('FIXED_USER','10')]),actor)).status).toBe('READY');expect((await service.validateVersionReadiness(version([step('FIXED_USER','10')]),actor)).errors[0].code).toBe('FIXED_USER_INVALID')});
test('capability zero is vacancy warning and multiple is ambiguity error',async()=>{mockQuery.mockResolvedValueOnce({rows:[{count:0}]}).mockResolvedValueOnce({rows:[{count:2}]});expect((await service.validateVersionReadiness(version([step('CAPABILITY_HOLDER','approval-authority.ceo')]),actor)).warnings[0].code).toBe('CAPABILITY_VACANT');expect((await service.validateVersionReadiness(version([step('CAPABILITY_HOLDER','approval-authority.ceo')]),actor)).errors[0].code).toBe('CAPABILITY_AMBIGUOUS')});
test('malformed amounts and incoherent parallel groups are categorized errors',async()=>{const v=version([{...step('REQUESTER',null,4),parallelGroup:'G',approvalLevel:1},{...step('REQUESTER',null,5),parallelGroup:'G',approvalLevel:2}]);v.rules[0].conditions=[{type:'AMOUNT_GTE',value:'1e9'}];const result=await service.validateVersionReadiness(v,actor);expect(result.errors.map(x=>x.code)).toEqual(expect.arrayContaining(['MALFORMED_AMOUNT','PARALLEL_GROUP_LEVEL_MISMATCH']))});