const mockQuery=jest.fn(),mockRelease=jest.fn(),mockConnect=jest.fn();
jest.mock('../config/db',()=>({query:(...a)=>mockQuery(...a),connect:(...a)=>mockConnect(...a)}));
const mockRepo={getVersion:jest.fn(),listRules:jest.fn(),listConditions:jest.fn(),listSteps:jest.fn(),getPolicy:jest.fn(),getVersions:jest.fn(),listPolicies:jest.fn(),getShadowRun:jest.fn(),getShadowSteps:jest.fn(),getShadowDifferences:jest.fn(),getCurrentRouteForRun:jest.fn(),listShadowRuns:jest.fn()};jest.mock('../repositories/approvalPolicyRepository',()=>mockRepo);
jest.mock('../services/auditService',()=>({writeAuditEvent:jest.fn()}));jest.mock('../services/approvalPolicyShadowService',()=>({generateShadowApprovalRoute:jest.fn()}));
const service=require('../services/approvalPolicyService'),shadow=require('../services/approvalPolicyShadowService');const actor={id:1,instituteId:10};
beforeEach(()=>{jest.clearAllMocks();mockConnect.mockResolvedValue({query:mockQuery,release:mockRelease});mockQuery.mockResolvedValue({rows:[],rowCount:0});mockRepo.listRules.mockResolvedValue({rows:[]});mockRepo.listConditions.mockResolvedValue({rows:[]});mockRepo.listSteps.mockResolvedValue({rows:[]});mockRepo.getCurrentRouteForRun.mockResolvedValue({rows:[]})});
test.each([
 ['GET policy',()=>{mockRepo.getPolicy.mockResolvedValue({rows:[]});return service.getPolicy(99,actor)}],
 ['list versions',()=>{mockRepo.getVersions.mockResolvedValue({rows:[]});return service.getVersions(99,actor)}],
 ['GET version',()=>{mockRepo.getVersion.mockResolvedValue({rows:[]});return service.hydrateVersion(99,actor)}],
 ['read shadow run',()=>{mockRepo.getShadowRun.mockResolvedValue({rows:[]});return service.getShadowRun(99,actor)}]
])('%s returns no foreign-institute data',async(_,run)=>{const value=await run();expect(Array.isArray(value)?value.length===0:!value).toBe(true)});
test('all mockRepository reads derive institute scope from actor',async()=>{mockRepo.getPolicy.mockResolvedValue({rows:[{id:2}]});mockRepo.getVersions.mockResolvedValue({rows:[]});mockRepo.getShadowRun.mockResolvedValue({rows:[{id:3}]});mockRepo.getShadowSteps.mockResolvedValue({rows:[]});mockRepo.getShadowDifferences.mockResolvedValue({rows:[]});await service.getPolicyDetail(2,actor);await service.getShadowRun(3,actor);expect(mockRepo.getPolicy).toHaveBeenCalledWith(2,10);expect(mockRepo.getVersions).toHaveBeenCalledWith(2,10);expect(mockRepo.getShadowRun).toHaveBeenCalledWith(3,10);expect(mockRepo.getShadowSteps).toHaveBeenCalledWith(3,10);expect(mockRepo.getShadowDifferences).toHaveBeenCalledWith(3,10)});
test('body instituteId cannot override actor scope when creating a policy',async()=>{mockQuery.mockImplementation(async sql=>sql==='BEGIN'||sql==='COMMIT'?{rows:[]}:sql.startsWith('INSERT INTO approval_policies')?{rows:[{id:1,institute_id:10}]}:{rows:[]});await service.createPolicy({code:'A',name:'A',instituteId:999},actor);const insert=mockQuery.mock.calls.find(x=>x[0].startsWith('INSERT INTO approval_policies'));expect(insert[1][0]).toBe(10);expect(insert[1]).not.toContain(999)});
test.each(['SHADOW','ACTIVE','RETIRED'])('%s configuration replacement is rejected and rolled back',async status=>{mockRepo.getVersion.mockResolvedValue({rows:[{id:4,status}]});await expect(service.replaceDraft(4,{rules:[]},actor)).rejects.toMatchObject({statusCode:409});expect(mockQuery).toHaveBeenCalledWith('ROLLBACK');expect(mockQuery.mock.calls.some(x=>String(x[0]).startsWith('DELETE FROM approval_policy_rules'))).toBe(false)});
test('DRAFT validates to VALIDATED and VALIDATED enters SHADOW',async()=>{mockRepo.getVersion.mockResolvedValueOnce({rows:[{id:4,status:'DRAFT',policy:{instituteId:10}}]}).mockResolvedValueOnce({rows:[{id:4,status:'VALIDATED',policy:{instituteId:10}}]});mockRepo.listRules.mockResolvedValue({rows:[{id:8,rule_code:'R',priority:1}]});mockRepo.listSteps.mockResolvedValue({rows:[{approvalLevel:1,stepOrder:1,resolverType:'REQUESTER',semanticKey:'REQUESTER',displayName:'Requester'}]});await expect(service.validate(4,actor)).resolves.toMatchObject({valid:true});mockQuery.mockImplementation(async sql=>String(sql).includes("status='SHADOW'")?{rows:[{id:4,status:'SHADOW'}]}:{rows:[],rowCount:0});await expect(service.enterShadow(4,actor)).resolves.toMatchObject({status:'SHADOW'})});
test.each(['rule','condition','step'])('replaceDraft rolls back completely when %s persistence fails',async failure=>{mockRepo.getVersion.mockResolvedValue({rows:[{id:4,status:'DRAFT',policy:{instituteId:10}}]});mockQuery.mockImplementation(async sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[]};if((failure==='rule'&&sql.startsWith('INSERT INTO approval_policy_rules'))||(failure==='condition'&&sql.startsWith('INSERT INTO approval_policy_rule_conditions'))||(failure==='step'&&sql.startsWith('INSERT INTO approval_policy_rule_steps')))throw new Error(`${failure} failed`);if(sql.startsWith('INSERT INTO approval_policy_rules'))return {rows:[{id:8}]};return {rows:[]}});const body={rules:[{code:'R',name:'Rule',priority:1,conditions:[{type:'REQUEST_TYPE_EQUALS',value:'PR'}],steps:[{stepOrder:1,approvalLevel:1,semanticKey:'X',displayName:'X',resolverType:'REQUESTER'}]}]};await expect(service.replaceDraft(4,body,actor)).rejects.toThrow(`${failure} failed`);expect(mockQuery).toHaveBeenCalledWith('ROLLBACK');expect(mockQuery).not.toHaveBeenCalledWith('COMMIT')});
test('runShadow verifies scoped version and request before invoking isolated generator',async()=>{mockRepo.getVersion.mockResolvedValue({rows:[{id:4,status:'SHADOW',policy:{instituteId:10}}]});mockQuery.mockResolvedValue({rows:[{id:7}]});shadow.generateShadowApprovalRoute.mockResolvedValue({run:{id:1}});await service.runShadow(7,4,actor);expect(mockQuery).toHaveBeenCalledWith(expect.stringContaining('institute_id=$2'),[7,10]);expect(shadow.generateShadowApprovalRoute).toHaveBeenCalledWith(7,4,1,expect.objectContaining({instituteId:10}))});
test('batch clamps limit, scopes every filter mockQuery, and never evaluates unselected history',async()=>{mockRepo.getVersion.mockResolvedValue({rows:[{id:4,status:'SHADOW',policy:{instituteId:10}}]});mockQuery.mockResolvedValue({rows:[]});const result=await service.runShadowBatch({policyVersionId:4,dateFrom:'2026-01-01',dateTo:'2026-02-01',departmentId:5,requestType:'PR',limit:999,cursor:'20',instituteId:999},actor).catch(e=>e);expect(result.statusCode).toBe(400);await service.runShadowBatch({policyVersionId:4,dateFrom:'2026-01-01',dateTo:'2026-02-01',departmentId:5,requestType:'PR',limit:999,cursor:'20'},actor);const call=mockQuery.mock.calls.find(x=>String(x[0]).includes('SELECT id FROM requests'));expect(call[1]).toEqual([10,'2026-01-01','2026-02-01',5,'PR',100,20])});