process.env.RFID_CREDENTIAL_PEPPER='test-only-pepper-that-is-at-least-32-bytes-long';
const {normalizeEpc}=require('../domain/rfidConstants');
const {FixedAssetService}=require('../services/fixedAssetService');
const {RfidService,RfidIngestionService}=require('../services/rfidService');
test('EPC normalization prevents case and whitespace identities',()=>expect(normalizeEpc(' e280 1160 ')).toBe('E2801160'));
test('EPC validation remains length-flexible but rejects unsafe payloads',()=>{expect(normalizeEpc('ABC-1234')).toBe('ABC-1234');expect(()=>normalizeEpc('x')).toThrow(/4-128/);expect(()=>normalizeEpc('ABCD<script>')).toThrow();});
test('service credentials are hashed and human bearer tokens fail closed',async()=>{expect(RfidIngestionService.hash('secret')).toMatch(/^[a-f0-9]{64}$/);await expect(new RfidIngestionService({query:jest.fn()}).authenticate('Bearer human.jwt')).rejects.toMatchObject({statusCode:401});});
test('disabled or unknown service client is rejected',async()=>{const repo={query:jest.fn().mockResolvedValue({rowCount:0,rows:[]})};await expect(new RfidIngestionService(repo).authenticate('RFID device:secret')).rejects.toMatchObject({statusCode:401});expect(repo.query).toHaveBeenCalledWith(expect.stringContaining('enabled=true'),expect.any(Array));});
test('asset movement state machine rejects bypass to received',async()=>{const tx={db:{},query:jest.fn().mockResolvedValue({rows:[{id:4,status:'PENDING_APPROVAL'}]}),asset:jest.fn()},repo={transaction:jest.fn(fn=>fn(tx))};await expect(new FixedAssetService(repo,jest.fn()).transitionMovement(4,'RECEIVED',{instituteId:7,userId:9})).rejects.toMatchObject({statusCode:409});});
test('received movement updates canonical location and audit in one transaction',async()=>{const movement={id:4,status:'IN_TRANSIT',asset_id:8,to_location_id:12,to_department_id:null};const tx={db:{tx:true},asset:jest.fn().mockResolvedValue({id:8,current_location_id:undefined,responsible_department_id:4}),query:jest.fn().mockResolvedValueOnce({rows:[movement]}).mockResolvedValueOnce({rows:[{...movement,status:'RECEIVED'}]}).mockResolvedValueOnce({rows:[{current_location_id:12,responsible_department_id:4}]})},repo={transaction:jest.fn(fn=>fn(tx))},audit=jest.fn();const row=await new FixedAssetService(repo,audit).transitionMovement(4,'RECEIVED',{instituteId:7,userId:9});expect(row.status).toBe('RECEIVED');expect(tx.query.mock.calls[2][0]).toContain('UPDATE assets SET current_location_id');expect(audit).toHaveBeenCalledWith(expect.objectContaining({client:tx.db,action:'ASSET_MOVEMENT_RECEIVED'}));});
test.each([['PERMANENT_TRANSFER',true],['MAINTENANCE_TRANSFER',false],['EXTERNAL_MAINTENANCE',false],['TEMPORARY_LOAN',false],['STORAGE_TRANSFER',false],['LOCATION_CORRECTION',false],['RETURN',false],['DISPOSAL_TRANSFER',false]])('receipt department semantics for %s',async(movementType,changes)=>{const movement={id:4,status:'IN_TRANSIT',asset_id:8,to_location_id:12,to_department_id:10,movement_type:movementType};const tx={db:{},asset:jest.fn().mockResolvedValue({id:8,current_location_id:undefined,responsible_department_id:4}),query:jest.fn().mockResolvedValueOnce({rows:[movement]}).mockResolvedValueOnce({rows:[{...movement,status:'RECEIVED'}]}).mockResolvedValueOnce({rows:[{current_location_id:12,responsible_department_id:4}]})};await new FixedAssetService({transaction:fn=>fn(tx)},jest.fn()).transitionMovement(4,'RECEIVED',{instituteId:7,userId:9});expect(tx.query.mock.calls[2][1][1]).toBe(changes);});
test('asset number cannot be edited',async()=>{const tx={db:{},asset:jest.fn().mockResolvedValue({id:1,asset_number:'WICI-A-000001'}),query:jest.fn()},repo={transaction:jest.fn(fn=>fn(tx))};await expect(new FixedAssetService(repo,jest.fn()).update(1,{assetNumber:'OTHER',rowVersion:1},{instituteId:7,userId:9})).rejects.toMatchObject({statusCode:409});expect(tx.query).not.toHaveBeenCalled();});
test('currency listing uses sources that define currency',async()=>{const repo={query:jest.fn().mockResolvedValue({rows:[{code:'IQD'},{code:'USD'}]})};await expect(new FixedAssetService(repo,jest.fn()).currencies({instituteId:7})).resolves.toEqual(['IQD','USD']);const [sql,params]=repo.query.mock.calls[0];expect(sql).toContain('SELECT a.currency FROM assets a');expect(sql).toContain('SELECT po.currency FROM purchase_orders po');expect(sql).not.toContain('requested_items');expect(params).toEqual([7]);});
test('category listing provisions governed baseline categories for an empty institute',async()=>{const rows=[{id:1,code:'IT_EQUIPMENT',name:'IT Equipment',is_active:true}];const repo={query:jest.fn().mockResolvedValueOnce({rowCount:8,rows:[]}).mockResolvedValueOnce({rows})};await expect(new FixedAssetService(repo,jest.fn()).categories({instituteId:7,userId:9})).resolves.toEqual(rows);expect(repo.query.mock.calls[0][0]).toContain('ON CONFLICT (institute_id,code) DO NOTHING');expect(repo.query.mock.calls[0][1].slice(0,2)).toEqual([7,9]);expect(JSON.parse(repo.query.mock.calls[0][1][2])).toEqual(expect.arrayContaining([expect.objectContaining({code:'IT_EQUIPMENT'}),expect.objectContaining({code:'OTHER'})]));expect(repo.query.mock.calls[1]).toEqual([expect.stringContaining('WHERE institute_id=$1'),[7]]);});
describe('acceptance hardening',()=>{
 beforeAll(()=>{process.env.RFID_CREDENTIAL_PEPPER='test-only-pepper-that-is-at-least-32-bytes-long';});
 test('credential verifier is keyed and deterministic',()=>{const hash=RfidIngestionService.hash('secret');expect(hash).toMatch(/^[a-f0-9]{64}$/);expect(hash).not.toBe(require('crypto').createHash('sha256').update('secret').digest('hex'));});
 test('ambiguous timestamps are rejected',async()=>{const repo={transaction:fn=>fn({query:jest.fn()})};await expect(new RfidIngestionService(repo).ingest([{epc:'ABC1234',timestamp:'2026-09-09 10:42:14'}],{id:1,institute_id:2})).rejects.toThrow(/timezone/);});
 test('oversized raw payload is rejected before database writes',async()=>{const query=jest.fn();const repo={transaction:fn=>fn({query})};await expect(new RfidIngestionService(repo).ingest([{epc:'ABC1234',timestamp:'2026-09-09T10:42:14Z',rawPayload:{data:'x'.repeat(17000)}}],{id:1,institute_id:2})).rejects.toMatchObject({statusCode:413});expect(query).not.toHaveBeenCalled();});
 test('missing credential pepper fails closed',()=>{const pepper=process.env.RFID_CREDENTIAL_PEPPER;delete process.env.RFID_CREDENTIAL_PEPPER;expect(()=>RfidIngestionService.hash('secret')).toThrow(/not configured/);process.env.RFID_CREDENTIAL_PEPPER=pepper;});
 test('client listing projection never exposes credential verifier',async()=>{const query=jest.fn().mockResolvedValue({rows:[]});await new RfidService({query}).listClients({instituteId:2});expect(query.mock.calls[0][0]).not.toContain('credential_hash');});
 test('direction engine uses ordered portal sides',()=>{const {deriveDirection}=require('../services/rfidEventProcessor');const result=deriveDirection([{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'SIDE_A'},{read_timestamp:'2026-09-09T10:00:01Z',direction_role:'SIDE_B'}],{from_location_id:1,to_location_id:2});expect(result).toMatchObject({direction:'ENTERING',confidence:.8});});
 test('direction remains unknown without orientation',()=>{const {deriveDirection}=require('../services/rfidEventProcessor');expect(deriveDirection([{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'SIDE_A'}],{}).direction).toBe('UNKNOWN');});
});
test('migration 017 has strict compatible, drift, dependency, function and index contracts',()=>{const sql=require('fs').readFileSync(require('path').join(__dirname,'../sql/manual/017_fixed_assets_rfid_core.sql'),'utf8');for(const marker of ['SQL_017_PARTIAL_OR_DRIFTED_SCHEMA','SQL_017_DEPENDENCY_MISSING_OR_INCOMPATIBLE','next_asset_number','custody_records_asset_idx','rfid_read_processing_idx','asset_tags_active_epc_uq'])expect(sql).toContain(marker);for(const table of ['asset_number_allocators','asset_categories','asset_locations','assets','asset_movements','asset_tags','rfid_readers','rfid_antennas','rfid_portals','rfid_portal_antennas','rfid_integration_clients','rfid_read_events','rfid_business_events','asset_exceptions'])expect(sql).toContain(`CREATE TABLE ${table}`);expect(sql).not.toContain('rfid_portal_enable_scope');expect(sql).not.toMatch(/CREATE (?:TABLE|INDEX) IF NOT EXISTS/);expect(sql).not.toMatch(/max\s*\([^)]*\)\s*\+\s*1/i);});

test('migration 018 remains the immutable two-guard deployment',()=>{const sql=require('fs').readFileSync(require('path').join(__dirname,'../sql/manual/018_fixed_assets_rfid_post_deployment_hardening.sql'),'utf8');expect((sql.match(/CREATE FUNCTION public\.enforce_rfid_/g)||[])).toHaveLength(2);expect(sql).not.toContain('enforce_rfid_reader_scope_update');});

test('migration 027 upgrades SQL 018 forward-only with mutation guards',()=>{const sql=require('fs').readFileSync(require('path').join(__dirname,'../sql/manual/027_rfid_configuration_mutation_guards.sql'),'utf8');for(const marker of ['SQL_027_ALREADY_APPLIED_COMPATIBLE','SQL_027_REQUIRES_COMPATIBLE_SQL_018','enforce_rfid_antenna_scope_update','enforce_rfid_reader_scope_update','CREATE OR REPLACE FUNCTION public.enforce_rfid_portal_antenna_scope'])expect(sql).toContain(marker);expect(sql).not.toMatch(/CREATE (?:TABLE|INDEX) IF NOT EXISTS/);});

test('migration 026 adds the portal scope index forward-only and fails closed on drift',()=>{const sql=require('fs').readFileSync(require('path').join(__dirname,'../sql/manual/026_rfid_portal_enable_scope_index.sql'),'utf8');for(const marker of ['SQL_026_ALREADY_APPLIED_COMPATIBLE','SQL_026_PARTIAL_OR_DRIFTED_SCHEMA','SQL_026_DEPENDENCY_MISSING_OR_INCOMPATIBLE','CREATE INDEX rfid_portal_enable_scope'])expect(sql).toContain(marker);expect(sql).not.toMatch(/CREATE (?:TABLE|INDEX) IF NOT EXISTS/);});

test.each([
 ['028_asset_movement_operational_hardening.sql',['SQL_028_ALREADY_APPLIED_COMPATIBLE','SQL_028_PARTIAL_OR_DRIFTED_SCHEMA','SQL_028_DEPENDENCY_MISSING_OR_INCOMPATIBLE','SQL_028_ACTIVE_MOVEMENT_CONFLICT']],
 ['029_fixed_asset_deployment_valuation.sql',['SQL_029_ALREADY_APPLIED_COMPATIBLE','SQL_029_PARTIAL_OR_DRIFTED_SCHEMA','SQL_029_DEPENDENCY_MISSING_OR_INCOMPATIBLE']],
])('pending migration %s exposes fail-closed deployment states',(file,markers)=>{const sql=require('fs').readFileSync(require('path').join(__dirname,'../sql/manual',file),'utf8');for(const marker of markers)expect(sql).toContain(marker);expect(sql).not.toMatch(/(?:ADD COLUMN|CREATE INDEX) IF NOT EXISTS/);});

describe('fixed asset deployment completion',()=>{
 test('section must belong to selected same-institute department',async()=>{const tx={query:jest.fn().mockResolvedValue({rowCount:0,rows:[]})};await expect(new FixedAssetService().validateLinks({responsibleDepartmentId:3,responsibleSectionId:9},{instituteId:7},tx)).rejects.toThrow(/foreign departments|Section/);});
 test('foreign or inactive physical locations are rejected',async()=>{const tx={query:jest.fn().mockResolvedValue({rowCount:0,rows:[]})};await expect(new FixedAssetService().validateLinks({currentLocationId:4},{instituteId:7},tx)).rejects.toThrow(/asset_locations/);expect(tx.query.mock.calls[0][0]).toContain('is_active=true');});
 test('legacy recovery permits unknown deployment',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce({rows:[{id:1,asset_number:'WICI-A-1',serial_number:null}]})};const service=new FixedAssetService({transaction:fn=>fn(tx)},jest.fn());await expect(service.create({description:'Recovered',assetClass:'CONTROLLED',assetCategoryId:null,acquisitionMethod:'LEGACY',ownershipType:'INSTITUTE_OWNED',condition:'UNKNOWN',operationalStatus:'IN_STORAGE',reconciliationStatus:'UNKNOWN',creationSource:'LEGACY_RECOVERY'},{instituteId:1,userId:2})).resolves.toMatchObject({asset:{id:1}});expect(tx.query).toHaveBeenCalledTimes(1);});
 test('initial deployment is a received canonical movement with audit',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[{id:2}]}).mockResolvedValueOnce({rowCount:1,rows:[{id:3}]}).mockResolvedValueOnce({rowCount:1,rows:[{id:3}]}).mockResolvedValueOnce({rowCount:1,rows:[{id:10,asset_number:'WICI-A-1'}]}).mockResolvedValueOnce({rows:[{id:20,movement_type:'INITIAL_DEPLOYMENT'}]})};const audit=jest.fn();const service=new FixedAssetService({transaction:fn=>fn(tx)},audit);await service.create({description:'Pump',assetClass:'CONTROLLED',assetCategoryId:null,acquisitionMethod:'PURCHASE',ownershipType:'INSTITUTE_OWNED',condition:'NEW',operationalStatus:'IN_SERVICE',reconciliationStatus:'UNVERIFIED',creationSource:'MANUAL',responsibleDepartmentId:2,responsibleSectionId:3,currentLocationId:4,deploymentDate:'2026-09-14'},{instituteId:1,userId:5});expect(tx.query.mock.calls[4][0]).toContain("'INITIAL_DEPLOYMENT'");expect(audit).toHaveBeenCalledWith(expect.objectContaining({action:'ASSET_INITIAL_DEPLOYMENT'}));});
 test('valuation delegates decimal-safe conversion to PostgreSQL and stores snapshot',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce({rows:[{code:'IQD'},{code:'USD'}]}).mockResolvedValueOnce({rows:[{id:1,asset_number:'A',serial_number:null}]})};await new FixedAssetService({transaction:fn=>fn(tx)},jest.fn()).create({description:'Pump',assetClass:'CONTROLLED',assetCategoryId:null,acquisitionMethod:'PURCHASE',ownershipType:'INSTITUTE_OWNED',condition:'NEW',operationalStatus:'IN_SERVICE',reconciliationStatus:'UNVERIFIED',creationSource:'MANUAL',acquisitionCost:'5000.0000',currency:'USD',exchangeRateToIqd:'1310.000000',exchangeRateEffectiveDate:'2026-09-14',exchangeRateSource:'Central bank bulletin'},{instituteId:1,userId:2});expect(tx.query.mock.calls[1][0]).toContain('round($21::numeric*$23::numeric)');expect(tx.query.mock.calls[1][1]).toEqual(expect.arrayContaining(['5000.0000','USD','1310.000000','Central bank bulletin']));});
 test('asset creation rejects a syntactically valid currency outside the governed source',async()=>{const tx={query:jest.fn().mockResolvedValue({rows:[{code:'IQD'},{code:'USD'}]})};await expect(new FixedAssetService({transaction:fn=>fn(tx)},jest.fn()).create({description:'Pump',assetClass:'CONTROLLED',assetCategoryId:null,acquisitionMethod:'PURCHASE',ownershipType:'INSTITUTE_OWNED',condition:'NEW',operationalStatus:'IN_SERVICE',reconciliationStatus:'UNVERIFIED',creationSource:'MANUAL',acquisitionCost:'1.0000',currency:'ZZZ',exchangeRateToIqd:'1.000000'},{instituteId:1,userId:2})).rejects.toMatchObject({code:'ASSET_CURRENCY_NOT_GOVERNED'});expect(tx.query).toHaveBeenCalledTimes(1);});
 test('RFID encoding failure never activates a tag and QR uses permanent identity',async()=>{const {AssetLabelService}=require('../services/assetLabelService');const repo={query:jest.fn()},printer={configured:true,printAndEncode:jest.fn().mockResolvedValue({verified:false})},labels=new AssetLabelService(repo,printer),asset={id:2,asset_number:'WICI-A-42'};expect(labels.qrPayload(asset)).toBe('WICI-ASSET:WICI-A-42');await expect(labels.printAndEncode(asset,'EPC1',{instituteId:1,userId:2})).rejects.toThrow(/verification failed/);expect(repo.query).not.toHaveBeenCalled();});
});
describe('behavioral closure coverage',()=>{
 test.each([
  [[{read_timestamp:'2026-09-09T10:00:01Z',direction_role:'SIDE_B'},{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'SIDE_A'}],'ENTERING'],
  [[{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'SIDE_B'},{read_timestamp:'2026-09-09T10:00:01Z',direction_role:'SIDE_A'}],'EXITING'],
  [[{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'APPROACH'},{read_timestamp:'2026-09-09T10:00:01Z',direction_role:'DEPARTURE'}],'ENTERING'],
  [[{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'UNKNOWN'}],'UNKNOWN'],
  [[{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'SIDE_A'},{read_timestamp:'2026-09-09T10:00:01Z',direction_role:'SIDE_B'},{read_timestamp:'2026-09-09T10:00:02Z',direction_role:'SIDE_A'}],'UNKNOWN'],
 ])('direction is deterministic for ordered evidence %#',(reads,expected)=>{const {deriveDirection}=require('../services/rfidEventProcessor');const out=deriveDirection(reads,{from_location_id:1,to_location_id:2});expect(out.direction).toBe(expected);expect(out.confidence).toBeGreaterThanOrEqual(0);expect(out.confidence).toBeLessThanOrEqual(1);});
 test('event lookup enforces inactivity and bounded-start session boundaries',async()=>{const RfidEventProcessor=require('../services/rfidEventProcessor');const read={id:1,institute_id:2,epc:'EPC-A',portal_id:null,asset_id:null,asset_tag_id:null,reader_id:3,read_timestamp:'2026-09-09T10:00:25Z'};const query=jest.fn().mockResolvedValueOnce({rows:[read]}).mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[{id:9}]}).mockResolvedValue({rows:[]});await new RfidEventProcessor().processOne({query},1);const session=query.mock.calls.find(([sql])=>sql.includes('FROM rfid_business_events WHERE'));expect(session[0]).toContain('last_seen_at >=');expect(session[0]).toContain('first_seen_at >=');expect(session[0]).not.toContain('last_seen_at BETWEEN');});
 test('audit failure propagates inside the asset transaction callback',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce({rows:[{id:10,asset_number:'WICI-A-000001'}]})};const repo={transaction:jest.fn(fn=>fn(tx))};const audit=jest.fn().mockRejectedValue(new Error('audit unavailable'));const input={description:'Pump',assetClass:'CONTROLLED',assetCategoryId:null,acquisitionMethod:'LEGACY',ownershipType:'INSTITUTE_OWNED',condition:'UNKNOWN',operationalStatus:'IN_STORAGE',reconciliationStatus:'UNVERIFIED',creationSource:'LEGACY_RECOVERY'};await expect(new FixedAssetService(repo,audit).create(input,{instituteId:1,userId:2})).rejects.toThrow('audit unavailable');expect(repo.transaction).toHaveBeenCalledTimes(1);});
});