process.env.RFID_CREDENTIAL_PEPPER='test-only-pepper-that-is-at-least-32-bytes-long';
const {normalizeEpc}=require('../domain/rfidConstants');
const {FixedAssetService}=require('../services/fixedAssetService');
const {RfidIngestionService}=require('../services/rfidService');
test('EPC normalization prevents case and whitespace identities',()=>expect(normalizeEpc(' e280 1160 ')).toBe('E2801160'));
test('EPC validation remains length-flexible but rejects unsafe payloads',()=>{expect(normalizeEpc('ABC-1234')).toBe('ABC-1234');expect(()=>normalizeEpc('x')).toThrow(/4-128/);expect(()=>normalizeEpc('ABCD<script>')).toThrow();});
test('service credentials are hashed and human bearer tokens fail closed',async()=>{expect(RfidIngestionService.hash('secret')).toMatch(/^[a-f0-9]{64}$/);await expect(new RfidIngestionService({query:jest.fn()}).authenticate('Bearer human.jwt')).rejects.toMatchObject({statusCode:401});});
test('disabled or unknown service client is rejected',async()=>{const repo={query:jest.fn().mockResolvedValue({rowCount:0,rows:[]})};await expect(new RfidIngestionService(repo).authenticate('RFID device:secret')).rejects.toMatchObject({statusCode:401});expect(repo.query).toHaveBeenCalledWith(expect.stringContaining('enabled=true'),expect.any(Array));});
test('asset movement state machine rejects bypass to received',async()=>{const tx={db:{},query:jest.fn().mockResolvedValue({rows:[{id:4,status:'PENDING_APPROVAL'}]}),asset:jest.fn()},repo={transaction:jest.fn(fn=>fn(tx))};await expect(new FixedAssetService(repo,jest.fn()).transitionMovement(4,'RECEIVED',{instituteId:7,userId:9})).rejects.toMatchObject({statusCode:409});});
test('received movement updates canonical location and audit in one transaction',async()=>{const movement={id:4,status:'IN_TRANSIT',asset_id:8,to_location_id:12,to_department_id:null};const tx={db:{tx:true},query:jest.fn().mockResolvedValueOnce({rows:[movement]}).mockResolvedValueOnce({rows:[{...movement,status:'RECEIVED'}]}).mockResolvedValueOnce({rows:[]})},repo={transaction:jest.fn(fn=>fn(tx))},audit=jest.fn();const row=await new FixedAssetService(repo,audit).transitionMovement(4,'RECEIVED',{instituteId:7,userId:9});expect(row.status).toBe('RECEIVED');expect(tx.query.mock.calls[2][0]).toContain('UPDATE assets SET current_location_id');expect(audit).toHaveBeenCalledWith(expect.objectContaining({client:tx.db,action:'ASSET_MOVEMENT_RECEIVED'}));});
test('asset number cannot be edited',async()=>{const tx={db:{},asset:jest.fn().mockResolvedValue({id:1,asset_number:'WICI-A-000001'}),query:jest.fn()},repo={transaction:jest.fn(fn=>fn(tx))};await expect(new FixedAssetService(repo,jest.fn()).update(1,{assetNumber:'OTHER',rowVersion:1},{instituteId:7,userId:9})).rejects.toMatchObject({statusCode:409});expect(tx.query).not.toHaveBeenCalled();});
describe('acceptance hardening',()=>{
 beforeAll(()=>{process.env.RFID_CREDENTIAL_PEPPER='test-only-pepper-that-is-at-least-32-bytes-long';});
 test('credential verifier is keyed and deterministic',()=>{const hash=RfidIngestionService.hash('secret');expect(hash).toMatch(/^[a-f0-9]{64}$/);expect(hash).not.toBe(require('crypto').createHash('sha256').update('secret').digest('hex'));});
 test('ambiguous timestamps are rejected',async()=>{const repo={transaction:fn=>fn({query:jest.fn()})};await expect(new RfidIngestionService(repo).ingest([{epc:'ABC1234',timestamp:'2026-09-09 10:42:14'}],{id:1,institute_id:2})).rejects.toThrow(/timezone/);});
 test('direction engine uses ordered portal sides',()=>{const {deriveDirection}=require('../services/rfidEventProcessor');const result=deriveDirection([{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'SIDE_A'},{read_timestamp:'2026-09-09T10:00:01Z',direction_role:'SIDE_B'}],{from_location_id:1,to_location_id:2});expect(result).toMatchObject({direction:'ENTERING',confidence:.8});});
 test('direction remains unknown without orientation',()=>{const {deriveDirection}=require('../services/rfidEventProcessor');expect(deriveDirection([{read_timestamp:'2026-09-09T10:00:00Z',direction_role:'SIDE_A'}],{}).direction).toBe('UNKNOWN');});
});
test('migration 017 has strict compatible, drift, dependency, function and index contracts',()=>{const sql=require('fs').readFileSync(require('path').join(__dirname,'../sql/manual/017_fixed_assets_rfid_core.sql'),'utf8');for(const marker of ['SQL_017_ALREADY_APPLIED_COMPATIBLE','SQL_017_PARTIAL_OR_DRIFTED_SCHEMA','SQL_017_DEPENDENCY_MISSING_OR_INCOMPATIBLE','next_asset_number','custody_records_asset_idx','rfid_read_processing_idx','asset_tags_active_epc_uq'])expect(sql).toContain(marker);expect(sql).not.toMatch(/CREATE TABLE IF NOT EXISTS/);});