
jest.mock('../services/auditService',()=>({writeAuditEvent:jest.fn()}));
const{MaintenanceService}=require('../services/maintenanceService');
const ctx={instituteId:7,userId:11,actor:{id:11,institute_id:7,permissions:['inventory.reserve','inventory.issue']}};
const setup=overrides=>{const tx={db:{transaction:true},get:jest.fn().mockResolvedValue({id:5,status:'IN_PROGRESS'}),part:jest.fn(),inventoryOperation:jest.fn().mockResolvedValue(null),addInventoryOperation:jest.fn(),updatePart:jest.fn()};Object.assign(tx,overrides);return{tx,repo:{transaction:jest.fn(fn=>fn(tx))},inventory:{reserve:jest.fn(),issue:jest.fn()}};};

test('reserves planned quantity through canonical inventory in the same transaction',async()=>{const part={id:9,stock_item_id:8,quantity_planned:2,quantity_used:0};const{tx,repo,inventory}=setup({part:jest.fn().mockResolvedValue(part),updatePart:jest.fn().mockResolvedValue({...part,reservation_id:20})});inventory.reserve.mockResolvedValue({reservation:{id:20}});await new MaintenanceService(repo,jest.fn(),inventory).reservePart(5,9,{warehouse_id:4,idempotency_key:'mwo-5-part-9-reserve'},ctx);expect(inventory.reserve).toHaveBeenCalledWith(expect.objectContaining({warehouseId:4,inventoryItemId:8,quantity:2,documentType:'maintenance_work_order',documentId:5,documentLineId:9}),tx.db);expect(tx.addInventoryOperation).toHaveBeenCalledWith(9,'RESERVE',2,'mwo-5-part-9-reserve',20,null,7,11);});
test('issue consumes the reservation and records its inventory movement',async()=>{const part={id:9,stock_item_id:8,reservation_id:20,quantity_planned:2,quantity_used:0,work_order_status:'IN_PROGRESS'};const{tx,repo,inventory}=setup({part:jest.fn().mockResolvedValue(part),updatePart:jest.fn().mockResolvedValue({...part,quantity_used:1})});inventory.issue.mockResolvedValue({movement:{id:30}});await new MaintenanceService(repo,jest.fn(),inventory).issuePart(5,9,{quantity:1,idempotency_key:'mwo-5-part-9-issue-1'},ctx);expect(inventory.issue).toHaveBeenCalledWith(expect.objectContaining({reservationId:20,quantity:1}),tx.db);expect(tx.addInventoryOperation).toHaveBeenCalledWith(9,'ISSUE',1,'mwo-5-part-9-issue-1',20,30,7,11);expect(tx.updatePart).toHaveBeenCalledWith(9,7,expect.objectContaining({quantity_used:1,issued_inventory_movement_id:30,action:'ISSUED'}));});
test('issue rejects quantities beyond the planned remainder',async()=>{const{repo,inventory}=setup({part:jest.fn().mockResolvedValue({id:9,reservation_id:20,quantity_planned:2,quantity_used:1.5,work_order_status:'IN_PROGRESS'})});await expect(new MaintenanceService(repo,jest.fn(),inventory).issuePart(5,9,{quantity:1,idempotency_key:'too-much'},ctx)).rejects.toMatchObject({statusCode:409});expect(inventory.issue).not.toHaveBeenCalled();});
test('idempotent issue retry does not post inventory twice',async()=>{const part={id:9,reservation_id:20,quantity_planned:2,quantity_used:1,work_order_status:'IN_PROGRESS'};const{repo,inventory}=setup({part:jest.fn().mockResolvedValue(part),inventoryOperation:jest.fn().mockResolvedValue({quantity:1})});await expect(new MaintenanceService(repo,jest.fn(),inventory).issuePart(5,9,{quantity:1,idempotency_key:'same-key'},ctx)).resolves.toBe(part);expect(inventory.issue).not.toHaveBeenCalled();});
test('same issue key with a different quantity fails closed',async()=>{const{repo,inventory}=setup({part:jest.fn().mockResolvedValue({id:9}),inventoryOperation:jest.fn().mockResolvedValue({quantity:1})});await expect(new MaintenanceService(repo,jest.fn(),inventory).issuePart(5,9,{quantity:2,idempotency_key:'same-key'},ctx)).rejects.toMatchObject({statusCode:409});expect(inventory.issue).not.toHaveBeenCalled();});
test('releases unused reserved stock and makes the part reservable again',async()=>{const part={id:9,reservation_id:20,quantity_planned:3,quantity_used:1,work_order_status:'IN_PROGRESS'};const{tx,repo,inventory}=setup({part:jest.fn().mockResolvedValue(part),updatePart:jest.fn().mockResolvedValue({...part,reservation_id:null,action:'ISSUED'})});inventory.release=jest.fn().mockResolvedValue({reservation:{id:20,status:'RELEASED'}});await new MaintenanceService(repo,jest.fn(),inventory).releasePart(5,9,{idempotency_key:'release-unused'},ctx);expect(inventory.release).toHaveBeenCalledWith({reservationId:20,actor:ctx.actor},tx.db);expect(tx.addInventoryOperation).toHaveBeenCalledWith(9,'RELEASE',2,'release-unused',20,null,7,11);expect(tx.updatePart).toHaveBeenCalledWith(9,7,expect.objectContaining({reservation_id:null,action:'ISSUED'}));});
test('release retry does not alter inventory twice',async()=>{const part={id:9,reservation_id:null};const{repo,inventory}=setup({part:jest.fn().mockResolvedValue(part),inventoryOperation:jest.fn().mockResolvedValue({id:44})});inventory.release=jest.fn();await expect(new MaintenanceService(repo,jest.fn(),inventory).releasePart(5,9,{idempotency_key:'release-unused'},ctx)).resolves.toBe(part);expect(inventory.release).not.toHaveBeenCalled();});