jest.mock('../services/auditService',()=>({writeAuditEvent:jest.fn()}));
const{MaintenanceService}=require('../services/maintenanceService');
const ctx={instituteId:7,userId:11};
const transactional=overrides=>{const tx={db:{},equipment:jest.fn(),coverage:jest.fn(),assignee:jest.fn(),get:jest.fn(),create:jest.fn(),transition:jest.fn(),spareForEquipment:jest.fn(),addPart:jest.fn(),activePartReservations:jest.fn().mockResolvedValue([])};Object.assign(tx,overrides);return{tx,repo:{transaction:jest.fn(fn=>fn(tx)),get:jest.fn(),parts:jest.fn(),list:jest.fn()}};};

test('creates an institute-scoped Equipment work order with applicable coverage',async()=>{const input={equipment_id:5,coverage_id:3,work_order_type:'CORRECTIVE',priority:'HIGH',problem_description:'Vacuum unstable'};const{repo,tx}=transactional({equipment:jest.fn().mockResolvedValue({id:5}),coverage:jest.fn().mockResolvedValue({id:3}),create:jest.fn().mockResolvedValue({id:9,status:'OPEN'})});const audit=jest.fn();await new MaintenanceService(repo,audit).create(input,ctx);expect(tx.coverage).toHaveBeenCalledWith(3,5,7);expect(tx.create).toHaveBeenCalledWith(expect.objectContaining({equipment_id:5,coverage_id:3}),7,11);expect(audit).toHaveBeenCalledWith(expect.objectContaining({client:tx.db,action:'MAINTENANCE_WORK_ORDER_CREATED'}));});
test('rejects coverage belonging to another Equipment',async()=>{const{repo,tx}=transactional({equipment:jest.fn().mockResolvedValue({id:5}),coverage:jest.fn().mockResolvedValue(null)});await expect(new MaintenanceService(repo).create({equipment_id:5,coverage_id:3,work_order_type:'CORRECTIVE',priority:'HIGH',problem_description:'Failure'},ctx)).rejects.toMatchObject({statusCode:400});expect(tx.create).not.toHaveBeenCalled();});
test('rejects an assignee outside the institute',async()=>{const{repo,tx}=transactional({equipment:jest.fn().mockResolvedValue({id:5}),assignee:jest.fn().mockResolvedValue(null)});await expect(new MaintenanceService(repo).create({equipment_id:5,assigned_to:99,work_order_type:'CORRECTIVE',priority:'HIGH',problem_description:'Failure'},ctx)).rejects.toMatchObject({statusCode:400});expect(tx.assignee).toHaveBeenCalledWith(99,7);});
test('requires resolution evidence when completing',async()=>{const before={id:9,status:'IN_PROGRESS',row_version:2};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue(before)});await expect(new MaintenanceService(repo).transition(9,'COMPLETED',{row_version:2},ctx)).rejects.toMatchObject({statusCode:400});expect(tx.transition).not.toHaveBeenCalled();});
test('completion records timestamps and uses optimistic concurrency',async()=>{const before={id:9,status:'IN_PROGRESS',row_version:2,downtime_started_at:new Date()};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue(before),transition:jest.fn().mockResolvedValue({...before,status:'COMPLETED'})});await new MaintenanceService(repo,jest.fn()).transition(9,'COMPLETED',{row_version:2,resolution_summary:'Seal replaced'},ctx);expect(tx.transition).toHaveBeenCalledWith(9,7,expect.objectContaining({status:'COMPLETED',resolution_summary:'Seal replaced',completed_at:expect.any(Date),downtime_ended_at:expect.any(Date)}),2,11);});
test('completion fails while a part reservation remains active',async()=>{const{repo,tx}=transactional({get:jest.fn().mockResolvedValue({id:9,status:'IN_PROGRESS'}),activePartReservations:jest.fn().mockResolvedValue([{id:12,reservation_id:20}])});await expect(new MaintenanceService(repo).transition(9,'COMPLETED',{row_version:2,resolution_summary:'Repair done'},ctx)).rejects.toMatchObject({statusCode:409});expect(tx.transition).not.toHaveBeenCalled();});
test('planned parts must be approved, compatible, and mapped to Stock Item',async()=>{const work={id:9,status:'IN_PROGRESS',equipment_id:5};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue(work),spareForEquipment:jest.fn().mockResolvedValue({id:4,stock_item_id:null})});await expect(new MaintenanceService(repo).addPart(9,{spare_part_id:4,quantity_planned:1},ctx)).rejects.toMatchObject({statusCode:409});expect(tx.addPart).not.toHaveBeenCalled();});
test('plans the canonical Stock Item from approved compatibility',async()=>{const work={id:9,status:'IN_PROGRESS',equipment_id:5};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue(work),spareForEquipment:jest.fn().mockResolvedValue({id:4,stock_item_id:8}),addPart:jest.fn().mockResolvedValue({id:12})});await new MaintenanceService(repo,jest.fn()).addPart(9,{spare_part_id:4,quantity_planned:2},ctx);expect(tx.addPart).toHaveBeenCalledWith(9,expect.objectContaining({spare_part_id:4,stock_item_id:8,quantity_planned:2}),7,11);});