'use strict';
const { validateRequestItemIdentity } = require('../services/procurementItemIdentityService');
const { resolveRequestItem } = require('../services/requestItemResolutionService');
const { createAward } = require('../services/procurementAwardService');
const user = (allowed=false) => ({ id:7, hasPermission:p => allowed && p==='item-master.free-text-exception' });
describe('Non-Stock request identity governance',()=>{
 test('free text submits unresolved without Product or Catalog identity',async()=>{const client={query:jest.fn()};const result=await validateRequestItemIdentity(client,{request_mode:'free_text',stocking_policy:'non_stock',item_name:'Requester original wording'},user());expect(result).toMatchObject({catalog_status:'pending_mapping',generic_item_id:null,preferred_product_id:null,item_name_snapshot:'Requester original wording'});expect(client.query).not.toHaveBeenCalled();});
 test('canonical selection preserves original description',async()=>{const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[{id:2,generic_name:'Canonical',canonical_description:'Master',inventory_uom:'EA'}]})};const result=await validateRequestItemIdentity(client,{request_mode:'generic_item',generic_item_id:2,item_name:'Detailed requester specification'},user());expect(result.item_name).toBe('Detailed requester specification');expect(result.item_name_snapshot).toBe('Detailed requester specification');});
 test('exception requires permission and reason',async()=>{await expect(validateRequestItemIdentity({query:jest.fn()},{request_mode:'approved_free_text_exception',item_name:'urgent',restriction_justification:'urgent'},user())).rejects.toMatchObject({statusCode:403});await expect(validateRequestItemIdentity({query:jest.fn()},{request_mode:'approved_free_text_exception',item_name:'urgent'},user(true))).rejects.toMatchObject({statusCode:400});await expect(validateRequestItemIdentity({query:jest.fn()},{request_mode:'approved_free_text_exception',item_name:'urgent',restriction_justification:'Proprietary emergency'},user(true))).resolves.toMatchObject({catalog_status:'approved_exception'});});
 test('Generic resolution is audited without rewriting text',async()=>{const original={id:11,request_id:3,request_status:'approved',item_name:'Original',item_name_snapshot:'Original'};const updated={...original,generic_item_id:22};const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[original]}).mockResolvedValueOnce({rowCount:1,rows:[{id:22}]}).mockResolvedValueOnce({rowCount:1,rows:[updated]}).mockResolvedValueOnce({rowCount:1,rows:[]})};const result=await resolveRequestItem(client,3,11,{generic_item_id:22,reason:'Steward confirmed'},user());expect(result.item_name).toBe('Original');expect(result.resolution).toMatchObject({state:'RESOLVED_GENERIC',resolved_generic_item_id:22,resolved_by:7});expect(client.query.mock.calls[3][1]).toEqual(expect.arrayContaining(['resolved.generic',7,'Steward confirmed']));});
 test('resolution waits for approval',async()=>{const client={query:jest.fn().mockResolvedValue({rowCount:1,rows:[{id:11,request_status:'pending'}]})};await expect(resolveRequestItem(client,3,11,{generic_item_id:22,reason:'match'},user())).rejects.toMatchObject({statusCode:409});});
 test('Stock mapping reuses identity and records stock source',async()=>{const original={id:11,request_id:3,request_status:'approved',item_name:'Free text'};const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[original]}).mockResolvedValueOnce({rowCount:1,rows:[{id:55,generic_item_id:22,approved_product_id:null}]}).mockResolvedValueOnce({rowCount:1,rows:[{id:22}]}).mockResolvedValueOnce({rowCount:1,rows:[{...original,generic_item_id:22}]}).mockResolvedValueOnce({rowCount:1,rows:[]})};const result=await resolveRequestItem(client,3,11,{stock_item_id:55,reason:'Warehouse verified'},user());expect(result.resolution.stock_item_id).toBe(55);expect(client.query.mock.calls.some(([sql])=>/INSERT INTO stock_items/.test(sql))).toBe(false);});
 test('physical award requires exact offered Product and Catalog',async()=>{const tx={lockRequestItem:jest.fn().mockResolvedValue({id:1,request_mode:'generic_item'})};const repository={withTransaction:fn=>fn(tx)};await expect(createAward({repository,requestItem:{id:1},supplier:{id:2},input:{awarded_quantity:1},actor:user()})).rejects.toMatchObject({code:'AWARD_CATALOG_IDENTITY_REQUIRED'});});
});