const {createOrganizationReconciliationService}=require('../services/organizationReconciliationService');
const unit={id:4,name:'Nursing',department_name:'Nursing',department_id:10,unit_type:'DEPARTMENT',institute_id:1,is_active:true};
const build=(legacy=[],heads=[])=>createOrganizationReconciliationService({list:jest.fn(async()=>[unit]),get:jest.fn(async()=>unit),positions:jest.fn(async()=>heads),legacyHeadCandidates:jest.fn(async()=>legacy)});
test.each([
 [[],[],'ORG_HEAD_MISSING',false],
 [[{id:1,name:'HOD',is_active:true,evidence:['users.role=HOD']}],[],'ORG_HEAD_MISSING',true],
 [[{id:1,is_active:true},{id:2,is_active:true}],[],'MULTIPLE_LEGACY_HODS',false],
 [[{id:1,is_active:true}],[{user_id:1,position_type:'DEPARTMENT_HEAD',is_active:true}],'MATCHED',false],
 [[{id:1,is_active:true}],[{user_id:2,position_type:'DEPARTMENT_HEAD',is_active:true}],'CONFLICT',false],
 [[],[{user_id:2,position_type:'DEPARTMENT_HEAD',is_active:true}],'LEGACY_HOD_MISSING',false]
])('classifies reconciliation %#',async(legacy,heads,status,safe)=>{const [row]=await build(legacy,heads).list(1);expect(row).toMatchObject({status,safeToAssign:safe})});
test('bulk preview includes only unambiguous active same-scope candidates',async()=>{const service=build([{id:1,is_active:true}],[]);expect(await service.bulkPreview(1)).toHaveLength(1);await expect(service.assign({instituteId:1,unitId:4,userId:2,fromLegacy:true})).rejects.toMatchObject({statusCode:409})});
test('foreign institute reconciliation fails closed',async()=>{const service=build([{id:1,is_active:true}],[]);await expect(service.assign({instituteId:2,unitId:4,userId:1})).rejects.toMatchObject({statusCode:404})});
test('inactive legacy HOD remains evidence but is never safe to assign',async()=>{const [row]=await build([{id:1,is_active:false,evidence:['users.role=HOD']}],[]).list(1);expect(row.legacyCandidates).toHaveLength(1);expect(row.safeToAssign).toBe(false);expect(row.suggestedAction).toBe('Manual assignment required')});
test('a durable decision resolves only the same legacy and organization-head conflict',async()=>{const legacy=[{id:1,is_active:true}],heads=[{id:7,user_id:2,position_type:'DEPARTMENT_HEAD',is_active:true}];const repo={list:jest.fn(async()=>[unit]),get:jest.fn(async()=>unit),positions:jest.fn(async()=>heads),legacyHeadCandidates:jest.fn(async()=>legacy),reconciliationDecision:jest.fn(async()=>({id:9,legacy_user_id:1,organization_head_position_id:7,organization_head_user_id:2,decision:'MARK_LEGACY_OBSOLETE'}))};const service=createOrganizationReconciliationService(repo,jest.fn());expect((await service.list(1))[0]).toMatchObject({status:'NO_ACTION_REQUIRED',decision:{decision:'MARK_LEGACY_OBSOLETE'}});legacy[0]={id:3,is_active:true};expect((await service.list(1))[0]).toMatchObject({status:'CONFLICT',decision:null});legacy[0]={id:1,is_active:true};heads[0]={id:8,user_id:4,position_type:'DEPARTMENT_HEAD',is_active:true};expect((await service.list(1))[0]).toMatchObject({status:'CONFLICT',decision:null})});

test('decision locks, re-reads, supersedes, inserts and audits on one transaction client',async()=>{const client={query:jest.fn()},head={id:7,user_id:2,position_type:'DEPARTMENT_HEAD',is_active:true};const saved={id:12,decision:'MARK_LEGACY_OBSOLETE'};const repo={transaction:jest.fn(work=>work(client)),get:jest.fn(async()=>unit),positions:jest.fn(async()=>[head]),legacyHeadCandidates:jest.fn(async()=>[{id:1,is_active:true}]),reconciliationDecision:jest.fn(async()=>({id:8})),saveReconciliationDecision:jest.fn(async()=>saved)};const audit=jest.fn();const result=await createOrganizationReconciliationService(repo,audit).decide({instituteId:1,unitId:4,decision:'MARK_LEGACY_OBSOLETE',reason:' stale ',actorId:5});expect(result).toBe(saved);expect(repo.get).toHaveBeenCalledWith(4,client,{lock:true});expect(repo.positions).toHaveBeenCalledWith(4,client);expect(repo.legacyHeadCandidates).toHaveBeenCalledWith(10,1,client);expect(repo.reconciliationDecision).toHaveBeenCalledWith(4,client);expect(repo.saveReconciliationDecision).toHaveBeenCalledWith(expect.objectContaining({legacyUserId:1,organizationHeadPositionId:7,organizationHeadUserId:2,reason:'stale'}),client);expect(audit).toHaveBeenCalledWith(expect.objectContaining({client,action:'ORGANIZATION_HEAD_CONFLICT_RESOLVED'}))});

test('audit failure rejects the governed decision transaction',async()=>{const repo={transaction:jest.fn(async work=>work({query:jest.fn()})),get:jest.fn(async()=>unit),positions:jest.fn(async()=>[{id:7,user_id:2,position_type:'DEPARTMENT_HEAD',is_active:true}]),legacyHeadCandidates:jest.fn(async()=>[{id:1,is_active:true}]),reconciliationDecision:jest.fn(async()=>null),saveReconciliationDecision:jest.fn(async()=>({id:12}))};await expect(createOrganizationReconciliationService(repo,jest.fn(async()=>{throw new Error('audit down')})).decide({instituteId:1,unitId:4,decision:'KEEP_EXISTING',reason:'reviewed',actorId:5})).rejects.toThrow('audit down');expect(repo.transaction).toHaveBeenCalledTimes(1)});