const {createOrganizationService}=require('../services/organizationService');
function fixture(){const units=[{id:1,name:'Institute',unit_type:'INSTITUTE',parent_unit_id:null,institute_id:1},{id:2,name:'CEO',unit_type:'EXECUTIVE_OFFICE',parent_unit_id:1,institute_id:1},{id:3,name:'CMO',unit_type:'EXECUTIVE_OFFICE',parent_unit_id:1,institute_id:1},{id:4,name:'Nursing',unit_type:'DEPARTMENT',parent_unit_id:2,institute_id:1,department_id:10,classification:'Medical'}];const positions=[{id:1,organization_unit_id:2,position_type:'EXECUTIVE_HEAD',position_name:'CEO',user_id:5,user_name:'A',is_active:true,is_unit_head:true},{id:2,organization_unit_id:4,position_type:'DEPARTMENT_HEAD',position_name:'Head of Nursing',user_id:17,user_name:'B',is_active:true,is_unit_head:true}];const ancestors=async id=>{const out=[];let u=units.find(x=>x.id==id);while(u?.parent_unit_id){u=units.find(x=>x.id===u.parent_unit_id);out.push(u)}return out.reverse().map((x,i)=>({...x,depth:out.length-i}))};const descendants=async id=>units.filter(x=>{let u=x;while(u?.parent_unit_id){if(u.parent_unit_id==id)return true;u=units.find(v=>v.id===u.parent_unit_id)}return false});const query=jest.fn(async(sql,args)=>{if(sql.includes('UPDATE organization_units SET parent_unit_id')){const u=units.find(x=>x.id==args[0]);u.parent_unit_id=args[1];return{rows:[u]}}if(sql.includes('UPDATE organization_units')){const u=units.find(x=>x.id==args[0]);u.is_active=args[5]??u.is_active;return{rows:[u]}}if(sql.includes('INSERT INTO organization_units')){const u={id:units.length+1,name:args[1],unit_type:args[3],parent_unit_id:args[4],institute_id:args[0]};units.push(u);return{rows:[u]}}return{rows:[]}});const client={query,release:jest.fn()};return{units,positions,repo:{pool:{connect:async()=>client},get:async id=>units.find(x=>x.id==id),list:async f=>units.filter(x=>f.parent===undefined||x.parent_unit_id==f.parent),ancestors,descendants,positions:async id=>positions.filter(x=>x.organization_unit_id==id)},audit:jest.fn()}};
test('creates root and child units',async()=>{const f=fixture(),s=createOrganizationService(f.repo,f.audit);expect((await s.create({name:'Root',unitType:'INSTITUTE',instituteId:1,actorId:1})).name).toBe('Root');expect((await s.create({name:'IT',unitType:'DEPARTMENT',parentUnitId:2,instituteId:1,actorId:1})).parent_unit_id).toBe(2)});
test('rejects self parent and circular move',async()=>{const f=fixture(),s=createOrganizationService(f.repo,f.audit);await expect(s.moveUnit(2,2,1)).rejects.toThrow('own parent');await expect(s.moveUnit(2,4,1)).rejects.toThrow('circular')});
test('resolves ancestors, executive owner and department head',async()=>{const f=fixture(),s=createOrganizationService(f.repo,f.audit);expect((await s.getAncestorUnits(4)).map(x=>x.name)).toEqual(['Institute','CEO']);expect((await s.resolveExecutiveOwner(10)).position).toBe('CEO');expect((await s.resolveDepartmentHead(10)).user_id).toBe(17)});
test('move changes owner but not classification and archive is soft',async()=>{const f=fixture(),s=createOrganizationService(f.repo,f.audit);f.positions.push({organization_unit_id:3,position_type:'EXECUTIVE_HEAD',position_name:'CMO',user_id:6,is_active:true});await s.moveUnit(4,3,1);expect((await s.resolveExecutiveOwner(10)).position).toBe('CMO');expect(f.units[3].classification).toBe('Medical');await s.archive(4,1);expect(f.units[3].is_active).toBe(false)});test('position resolution excludes future, expired and archived holders',async()=>{const f=fixture(),s=createOrganizationService(f.repo,f.audit);f.positions.length=0;f.positions.push(
 {organization_unit_id:4,position_type:'DEPARTMENT_HEAD',is_active:true,effective_from:'2999-01-01',user_id:1},
 {organization_unit_id:4,position_type:'DEPARTMENT_HEAD',is_active:true,effective_to:'2000-01-01',user_id:2},
 {organization_unit_id:4,position_type:'DEPARTMENT_HEAD',is_active:false,user_id:3});
 expect(await s.resolveDepartmentHead(10)).toBeNull();f.positions.push({organization_unit_id:4,position_type:'DEPARTMENT_HEAD',is_active:true,effective_from:'2020-01-01',effective_to:'2999-01-01',user_id:4});expect((await s.resolveDepartmentHead(10)).user_id).toBe(4)});
test('ambiguous effective authority fails closed',async()=>{const f=fixture(),s=createOrganizationService(f.repo,f.audit);f.positions.push({organization_unit_id:4,position_type:'DEPARTMENT_HEAD',is_active:true,user_id:99});await expect(s.resolveDepartmentHead(10)).rejects.toMatchObject({statusCode:409})});
test('cross-institute move fails before mutation and audit',async()=>{const f=fixture(),s=createOrganizationService(f.repo,f.audit);f.units.push({id:9,name:'Other',unit_type:'INSTITUTE',institute_id:2,parent_unit_id:null});await expect(s.moveUnit(4,9,1)).rejects.toThrow('same institute');expect(f.audit).not.toHaveBeenCalled()});
test('audit failure rolls transaction back',async()=>{const f=fixture();f.audit.mockRejectedValue(new Error('audit unavailable'));const s=createOrganizationService(f.repo,f.audit);await expect(s.archiveUnit(4,1)).rejects.toThrow('audit unavailable');expect(f.repo.pool.connect).toBeDefined();expect(f.repo.pool).toBeTruthy()});