const {PhysicalInventoryService,allowedTransitions}=require('../services/physicalInventoryService');
const ctx={instituteId:7,userId:9};
const make=(tx,audit=jest.fn(),assets={requestMovement:jest.fn(),create:jest.fn()})=>({service:new PhysicalInventoryService({transaction:fn=>fn(tx),query:tx.query},audit,assets),audit,assets});
const result=(rows=[],rowCount=rows.length)=>({rows,rowCount});

test('lifecycle permits only forward transitions and cancellation',()=>expect(allowedTransitions).toEqual({DRAFT:['OPEN','CANCELLED'],OPEN:['COUNTING','CANCELLED'],COUNTING:['REVIEW','CANCELLED'],REVIEW:['COMPLETED','CANCELLED']}));
test('invalid backward lifecycle transition fails while holding the session lock',async()=>{const tx={db:{},query:jest.fn().mockResolvedValue(result([{id:1,status:'COUNTING'}]))};await expect(make(tx).service.transition(1,'OPEN',ctx)).rejects.toMatchObject({code:'INVALID_INVENTORY_TRANSITION'});expect(tx.query).toHaveBeenCalledWith(expect.stringContaining('FOR UPDATE'),[1,7])});
test.each([
 ['LOCATION',{scopeType:'LOCATION',scopeLocationId:2},'current_location_id=$2'],
 ['LOCATION descendants',{scopeType:'LOCATION',scopeLocationId:2,includeDescendants:true},'WITH RECURSIVE'],
 ['DEPARTMENT',{scopeType:'DEPARTMENT',scopeDepartmentId:2},'responsible_department_id=$2'],
 ['FULL_INSTITUTE',{scopeType:'FULL_INSTITUTE'},'true'],
])('%s scope is institute constrained',async(_name,input,fragment)=>{const tx={query:jest.fn().mockResolvedValue(result([{id:2}]))};expect((await make(tx).service.scopeSql(input,ctx,tx)).sql).toContain(fragment);if(input.scopeType!=='FULL_INSTITUTE')expect(tx.query.mock.calls[0][1]).toContain(7)});
test('foreign session scope is rejected',async()=>{const tx={query:jest.fn().mockResolvedValue(result([]))};await expect(make(tx).service.scopeSql({scopeType:'LOCATION',scopeLocationId:88},ctx,tx)).rejects.toThrow('foreign')});

test('duplicate QR scans are idempotent and never mutate authoritative assets',async()=>{const asset={id:5,asset_number:'A'},observation={id:8};const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([{id:1,status:'COUNTING'}])).mockResolvedValueOnce(result([asset])).mockResolvedValueOnce(result([{id:3}])).mockResolvedValueOnce(result([],0)).mockResolvedValueOnce(result([observation])).mockResolvedValueOnce(result([{id:2,expected_location_id:3}]))};const out=await make(tx).service.observe(1,{observationMethod:'QR',observedIdentifier:'A',observedLocationId:3},ctx);expect(out.result).toBe('ALREADY_SCANNED');expect(tx.query.mock.calls.some(([q])=>/UPDATE\s+assets/i.test(q))).toBe(false)});
test('manual/QR unknown or foreign asset fails closed',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([{id:1}])).mockResolvedValueOnce(result([]))};await expect(make(tx).service.observe(1,{observationMethod:'MANUAL',observedIdentifier:'FOREIGN'},ctx)).rejects.toMatchObject({code:'INVENTORY_IDENTIFIER_UNKNOWN'});expect(tx.query.mock.calls[1][0]).toContain('institute_id=$2')});

test.each([
 ['location','observedLocationId',"asset_locations"],['department','observedDepartmentId','departments'],['custodian','observedCustodianUserId','users'],
])('cross-institute %s is rejected',async(_label,key,table)=>{const asset={id:5};const tx={db:{},query:jest.fn(async(sql)=>sql.includes("status='COUNTING'")?result([{id:1}]):sql.includes('FROM assets')?result([asset]):sql.includes(`FROM ${table}`)?result([]):result([{id:1}]))};await expect(make(tx).service.observe(1,{observationMethod:'MANUAL',observedIdentifier:'A',[key]:44},ctx)).rejects.toMatchObject({statusCode:400})});
test.each([['read','rfidReadEventId'],['business','rfidBusinessEventId']])('invalid/cross-institute RFID %s evidence is rejected',async(_label,key)=>{const tx={db:{},query:jest.fn(async(sql)=>sql.includes("status='COUNTING'")?result([{id:1}]):sql.includes('FROM asset_tags t JOIN assets')?result([{id:5}]):result([]))};await expect(make(tx).service.observe(1,{observationMethod:'RFID',observedIdentifier:'E200',[key]:44},ctx)).rejects.toThrow(/RFID/)});
test('related RFID evidence is accepted and retained',async()=>{const tx={db:{},query:jest.fn(async sql=>{if(sql.includes("status='COUNTING'"))return result([{id:1}]);if(sql.includes('FROM asset_tags t JOIN assets'))return result([{id:5,asset_number:'A'}]);if(sql.startsWith('SELECT 1 FROM rfid_'))return result([{ok:1}]);if(sql.startsWith('INSERT INTO asset_inventory_observations'))return result([{id:9}],1);if(sql.includes('expected_assets'))return result([{id:2}]);return result([])})};const out=await make(tx).service.observe(1,{observationMethod:'RFID',observedIdentifier:'E200',rfidReadEventId:4,rfidBusinessEventId:6},ctx);expect(out.result).toBe('VERIFIED')});

test('movement and finding resolution use the same transaction repository',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([{id:4,status:'OPEN',finding_type:'WRONG_LOCATION',asset_id:5}])).mockResolvedValueOnce(result([{id:4,status:'RESOLVED'}])).mockResolvedValueOnce(result([]))};const assets={requestMovement:jest.fn().mockResolvedValue({id:77}),create:jest.fn()},audit=jest.fn();await make(tx,audit,assets).service.resolve(4,{status:'RESOLVED',notes:'count verified',code:'CORRECTED',action:'CREATE_MOVEMENT',toLocationId:8},ctx);expect(assets.requestMovement).toHaveBeenCalledWith(5,expect.any(Object),ctx,tx);expect(audit).toHaveBeenCalledWith(expect.objectContaining({client:tx.db}))});
test('a reconciliation persistence failure rejects the composed movement transaction',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([{id:4,status:'OPEN',finding_type:'WRONG_LOCATION',asset_id:5}])).mockRejectedValueOnce(new Error('finding write failed'))};const assets={requestMovement:jest.fn().mockResolvedValue({id:77}),create:jest.fn()};await expect(make(tx,jest.fn(),assets).service.resolve(4,{status:'RESOLVED',notes:'x',action:'CREATE_MOVEMENT',toLocationId:8},ctx)).rejects.toThrow('finding write failed');expect(assets.requestMovement.mock.calls[0][3]).toBe(tx)});
test('legacy registration, discovery link, UNREGISTERED resolution and audits share one transaction',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([{id:2,description:'Old pump'}])).mockResolvedValueOnce(result([])).mockResolvedValueOnce(result([{id:10,status:'RESOLVED'}])).mockResolvedValueOnce(result([]))};const assets={create:jest.fn().mockResolvedValue({asset:{id:99}}),requestMovement:jest.fn()},audit=jest.fn();await make(tx,audit,assets).service.registerDiscovery(2,{assetClass:'CONTROLLED'},ctx);expect(assets.create.mock.calls[0][2]).toBe(tx);expect(tx.query.mock.calls[1][0]).toContain('registered_asset_id');expect(tx.query.mock.calls[2][0]).toContain("finding_type='UNREGISTERED'")});
test('legacy registration failure prevents discovery linking',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([{id:2,description:'Old pump'}]))};const assets={create:jest.fn().mockRejectedValue(new Error('asset audit failed')),requestMovement:jest.fn()};await expect(make(tx,jest.fn(),assets).service.registerDiscovery(2,{},ctx)).rejects.toThrow('asset audit failed');expect(tx.query).toHaveBeenCalledTimes(1)});

test('snapshot custody uses only canonically Approved custody, not later historical rows',async()=>{const tx={db:{},query:jest.fn(async sql=>{if(sql.includes('FOR UPDATE'))return result([{id:1,status:'OPEN',scope_type:'FULL_INSTITUTE'}]);if(sql.includes('INSERT INTO asset_inventory_expected_assets'))return result([]);if(sql.includes('UPDATE asset_inventory_sessions'))return result([{id:1,status:'COUNTING'}]);return result([])})};await make(tx).service.transition(1,'COUNTING',ctx);const snapshotSql=tx.query.mock.calls.find(([sql])=>sql.includes('INSERT INTO asset_inventory_expected_assets'))[0];expect(snapshotSql).toContain("cr.status='Approved'");expect(snapshotSql).toContain('ORDER BY cr.updated_at DESC,cr.id DESC')});
test('COUNTING transition locks before freezing snapshot, preventing a second freeze',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([{id:1,status:'OPEN',scope_type:'FULL_INSTITUTE'}])).mockResolvedValueOnce(result([])).mockResolvedValueOnce(result([{id:1,status:'COUNTING'}]))};await make(tx).service.transition(1,'COUNTING',ctx);expect(tx.query.mock.calls[0][0]).toContain('FOR UPDATE');expect(tx.query.mock.calls.filter(([q])=>q.includes('INSERT INTO asset_inventory_expected_assets'))).toHaveLength(1)});
test('observation locks COUNTING session so REVIEW cannot race it',async()=>{const tx={db:{},query:jest.fn().mockResolvedValueOnce(result([]))};await expect(make(tx).service.observe(1,{observationMethod:'QR',observedIdentifier:'A'},ctx)).rejects.toThrow('COUNTING');expect(tx.query.mock.calls[0][0]).toContain('FOR UPDATE')});