jest.mock('../services/auditService',()=>({writeAuditEvent:jest.fn()}));
const {SparePartsService}=require('../services/sparePartsService');
const ctx={instituteId:7,userId:11};
const base={spare_part_code:'SP-1',name:'Seal',spare_part_type:'GENERAL',criticality:'MEDIUM',failure_consequence:'NON_CRITICAL'};
const transactional=overrides=>{const tx={db:{},generic:jest.fn(),product:jest.fn(),create:jest.fn().mockResolvedValue({id:1,...base,technical_approval_status:'DRAFT'}),get:jest.fn(),update:jest.fn(),equipment:jest.fn(),department:jest.fn(),addCompatibility:jest.fn(),compatibilityById:jest.fn(),updateCompatibility:jest.fn(),saveEquipment:jest.fn()};Object.assign(tx,overrides);return {tx,repo:{transaction:jest.fn(fn=>fn(tx))}}};
test('creates a DRAFT without Item Master mapping and audits',async()=>{const{repo,tx}=transactional();const audit=jest.fn();const row=await new SparePartsService(repo,audit).create(base,ctx);expect(row.technical_approval_status).toBe('DRAFT');expect(tx.create).toHaveBeenCalledWith(expect.not.objectContaining({generic_item_id:expect.anything()}),7,11);expect(audit).toHaveBeenCalledWith(expect.objectContaining({action:'SPARE_PART_CREATED'}));});
test('rejects invalid quantity range before persistence',async()=>{const{repo}=transactional();await expect(new SparePartsService(repo,jest.fn()).create({...base,recommended_min_quantity:'5.5',recommended_max_quantity:'5.4'},ctx)).rejects.toMatchObject({statusCode:400});});
test('requires preferred product to match generic identity',async()=>{const{repo,tx}=transactional({generic:jest.fn().mockResolvedValue({id:2}),product:jest.fn().mockResolvedValue({id:3,generic_item_id:9,approval_status:'approved',is_active:true})});await expect(new SparePartsService(repo,jest.fn()).create({...base,generic_item_id:2,preferred_approved_product_id:3},ctx)).rejects.toMatchObject({statusCode:400});expect(tx.create).not.toHaveBeenCalled();});
test('requires evidence for critical approval and derives actor',async()=>{const before={id:1,row_version:3,technical_approval_status:'UNDER_REVIEW',criticality:'CRITICAL',is_safety_critical:false};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue(before),update:jest.fn().mockResolvedValue({...before,technical_approval_status:'APPROVED',technical_approved_by:11})});const service=new SparePartsService(repo,jest.fn());await expect(service.decision(1,'APPROVE','',ctx)).rejects.toMatchObject({statusCode:400});await service.decision(1,'APPROVE','OEM bulletin 4',ctx);expect(tx.update).toHaveBeenCalledWith(1,7,expect.objectContaining({technical_approved_by:11}),11,3);});
test('fails closed for cross-institute equipment compatibility',async()=>{const{repo,tx}=transactional({get:jest.fn().mockResolvedValue({id:1}),equipment:jest.fn().mockResolvedValue(null)});await expect(new SparePartsService(repo,jest.fn()).addCompatibility(1,{equipment_id:99,compatibility_type:'OEM_SPECIFIED'},ctx)).rejects.toMatchObject({statusCode:400});expect(tx.addCompatibility).not.toHaveBeenCalled();});
test('general edit fails closed when stock-policy field is present, including mixed payloads',async()=>{const{repo,tx}=transactional();await expect(new SparePartsService(repo,jest.fn()).update(1,{name:'Seal 2',recommended_min_quantity:4,row_version:1},ctx)).rejects.toMatchObject({statusCode:403});expect(repo.transaction).not.toHaveBeenCalled();expect(tx.update).not.toHaveBeenCalled();});
test('stock-policy mutation uses its transaction and dedicated audit event',async()=>{const before={id:1,row_version:2,recommended_min_quantity:1,recommended_max_quantity:5};const after={...before,row_version:3,recommended_min_quantity:2};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue(before),update:jest.fn().mockResolvedValue(after)});const audit=jest.fn();await new SparePartsService(repo,audit).updateStockPolicy(1,{recommended_min_quantity:2,row_version:2},ctx);expect(tx.update).toHaveBeenCalledWith(1,7,{recommended_min_quantity:2},11,2);expect(audit).toHaveBeenCalledWith(expect.objectContaining({client:tx.db,action:'STOCK_POLICY_CHANGED'}));});
test('approved compatibility technical edit resets approval and audits in transaction',async()=>{const before={id:8,equipment_id:2,compatibility_type:'OEM_SPECIFIED',compatibility_status:'APPROVED',approved_by:4,approved_at:new Date()};const after={...before,compatibility_type:'CONDITIONAL',compatibility_status:'PENDING',approved_by:null,approved_at:null};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue({id:1}),compatibilityById:jest.fn().mockResolvedValue(before),updateCompatibility:jest.fn().mockResolvedValue(after)});const audit=jest.fn();await new SparePartsService(repo,audit).updateCompatibility(1,8,{compatibility_type:'CONDITIONAL'},ctx);expect(tx.updateCompatibility).toHaveBeenCalledWith(8,1,expect.objectContaining({compatibility_status:'PENDING',approved_by:null,approved_at:null}));expect(audit).toHaveBeenCalledWith(expect.objectContaining({client:tx.db,action:'COMPATIBILITY_UPDATED'}));});
test('equipment department must belong to actor institute',async()=>{const{repo,tx}=transactional({department:jest.fn().mockResolvedValue(null)});await expect(new SparePartsService(repo,jest.fn()).saveEquipment(null,{equipment_code:'E1',name:'Pump',manufacturer:'Acme',model:'P1',department_id:99},ctx)).rejects.toMatchObject({statusCode:400});expect(tx.department).toHaveBeenCalledWith(99,7);expect(tx.saveEquipment).not.toHaveBeenCalled();});
test('archive and its audit share one transaction client',async()=>{const before={id:1,row_version:4};const after={...before,lifecycle_status:'INACTIVE'};const{repo,tx}=transactional({get:jest.fn().mockResolvedValue(before),update:jest.fn().mockResolvedValue(after)});const audit=jest.fn().mockRejectedValue(new Error('audit failed'));await expect(new SparePartsService(repo,audit).archive(1,ctx)).rejects.toThrow('audit failed');expect(repo.transaction).toHaveBeenCalled();expect(audit).toHaveBeenCalledWith(expect.objectContaining({client:tx.db,action:'SPARE_PART_ARCHIVED'}));});
describe('stale row_version acceptance',()=>{
 test.each([['SUBMIT','DRAFT',''],['APPROVE','UNDER_REVIEW',''],['CONDITIONALLY_APPROVE','UNDER_REVIEW','reason'],['REJECT','UNDER_REVIEW','reason']])('%s fails closed with no success audit',async(decision,status,reason)=>{const{repo,tx}=transactional({get:jest.fn().mockResolvedValue({id:1,row_version:3,technical_approval_status:status,criticality:'MEDIUM'}),update:jest.fn().mockResolvedValue(null)});const audit=jest.fn();await expect(new SparePartsService(repo,audit).decision(1,decision,reason,ctx)).rejects.toMatchObject({statusCode:409,code:'SPARE_PART_VERSION_CONFLICT'});expect(tx.update).toHaveBeenCalledWith(1,7,expect.any(Object),11,3);expect(audit).not.toHaveBeenCalled();});
 test('archive rejects its transaction with no success audit',async()=>{const{repo}=transactional({get:jest.fn().mockResolvedValue({id:1,row_version:3}),update:jest.fn().mockResolvedValue(null)});const audit=jest.fn();await expect(new SparePartsService(repo,audit).archive(1,ctx)).rejects.toMatchObject({statusCode:409,code:'SPARE_PART_VERSION_CONFLICT'});expect(audit).not.toHaveBeenCalled();});
 test.each([['general',(s)=>s.update(1,{name:'new',row_version:3},ctx)],['stock',(s)=>s.updateStockPolicy(1,{recommended_min_quantity:2,row_version:3},ctx)]])('%s mutation uses the coded conflict',async(_name,invoke)=>{const{repo}=transactional({get:jest.fn().mockResolvedValue({id:1,row_version:3}),update:jest.fn().mockResolvedValue(null)});const audit=jest.fn();await expect(invoke(new SparePartsService(repo,audit))).rejects.toMatchObject({statusCode:409,code:'SPARE_PART_VERSION_CONFLICT'});expect(audit).not.toHaveBeenCalled();});
});

describe('expanded Spare Parts acceptance contracts',()=>{
 test('maps an active approved preferred Product to its Generic',async()=>{const{repo,tx}=transactional({generic:jest.fn().mockResolvedValue({id:2}),product:jest.fn().mockResolvedValue({id:3,generic_item_id:2,approval_status:'approved',is_active:true})});await new SparePartsService(repo,jest.fn()).create({...base,generic_item_id:2,preferred_approved_product_id:3},ctx);expect(tx.create).toHaveBeenCalledWith(expect.objectContaining({generic_item_id:2,preferred_approved_product_id:3}),7,11);});
 test.each([{approval_status:'pending',is_active:true},{approval_status:'approved',is_active:false}])('rejects inactive or unapproved Product',async product=>{const{repo,tx}=transactional({generic:jest.fn().mockResolvedValue({id:2}),product:jest.fn().mockResolvedValue({id:3,generic_item_id:2,...product})});await expect(new SparePartsService(repo,jest.fn()).create({...base,generic_item_id:2,preferred_approved_product_id:3},ctx)).rejects.toMatchObject({statusCode:400});expect(tx.create).not.toHaveBeenCalled();});
 test.each([['SUBMIT','DRAFT','UNDER_REVIEW',''],['APPROVE','UNDER_REVIEW','APPROVED',''],['CONDITIONALLY_APPROVE','UNDER_REVIEW','CONDITIONALLY_APPROVED','reason'],['REJECT','UNDER_REVIEW','REJECTED','reason']])('%s transitions lifecycle',async(decision,from,to,reason)=>{const before={id:1,row_version:3,technical_approval_status:from,criticality:'MEDIUM'};const{repo}=transactional({get:jest.fn().mockResolvedValue(before),update:jest.fn().mockImplementation((_a,_b,data)=>Promise.resolve({...before,...data}))});const audit=jest.fn();expect((await new SparePartsService(repo,audit).decision(1,decision,reason,ctx)).technical_approval_status).toBe(to);expect(audit).toHaveBeenCalledWith(expect.objectContaining({actorUserId:11}));});
 test.each(['CONDITIONALLY_APPROVE','REJECT'])('%s requires reason',async decision=>{const{repo}=transactional({get:jest.fn().mockResolvedValue({id:1,row_version:1,technical_approval_status:'UNDER_REVIEW',criticality:'MEDIUM'})});await expect(new SparePartsService(repo,jest.fn()).decision(1,decision,' ',ctx)).rejects.toMatchObject({statusCode:400});});
 test('safety-critical approval requires evidence',async()=>{const{repo}=transactional({get:jest.fn().mockResolvedValue({id:1,row_version:1,technical_approval_status:'UNDER_REVIEW',criticality:'LOW',is_safety_critical:true})});await expect(new SparePartsService(repo,jest.fn()).decision(1,'APPROVE','',ctx)).rejects.toMatchObject({statusCode:400});});
 test('invalid transition is rejected',async()=>{const{repo}=transactional({get:jest.fn().mockResolvedValue({id:1,row_version:1,technical_approval_status:'APPROVED'})});await expect(new SparePartsService(repo,jest.fn()).decision(1,'REJECT','reason',ctx)).rejects.toMatchObject({statusCode:409});});
 test('add, approve and reject compatibility emit authenticated audit events',async()=>{const{repo}=transactional({get:jest.fn().mockResolvedValue({id:1}),equipment:jest.fn().mockResolvedValue({id:2}),addCompatibility:jest.fn().mockResolvedValue({id:8}),updateCompatibility:jest.fn().mockResolvedValue({id:8})});const audit=jest.fn(),service=new SparePartsService(repo,audit);await service.addCompatibility(1,{equipment_id:2,compatibility_type:'OEM_SPECIFIED'},ctx);await service.compatibilityDecision(1,8,'APPROVED',ctx);await service.compatibilityDecision(1,8,'REJECTED',ctx);expect(audit.mock.calls.map(x=>x[0].action)).toEqual(['COMPATIBILITY_ADDED','COMPATIBILITY_APPROVED','COMPATIBILITY_REJECTED']);expect(audit).toHaveBeenLastCalledWith(expect.objectContaining({actorUserId:11}));});
 test('database uniqueness conflict propagates without false success audit',async()=>{const duplicate=Object.assign(new Error('duplicate'),{code:'23505'});const{repo}=transactional({get:jest.fn().mockResolvedValue({id:1}),equipment:jest.fn().mockResolvedValue({id:2}),addCompatibility:jest.fn().mockRejectedValue(duplicate)});const audit=jest.fn();await expect(new SparePartsService(repo,audit).addCompatibility(1,{equipment_id:2,compatibility_type:'OEM_SPECIFIED'},ctx)).rejects.toBe(duplicate);expect(audit).not.toHaveBeenCalled();});
 test('equipment create and update are institute-scoped and audited',async()=>{const equipment={id:4,equipment_code:'E1',name:'Pump',manufacturer:'Acme',model:'P1'};const{repo,tx}=transactional({department:jest.fn().mockResolvedValue({id:6}),equipment:jest.fn().mockResolvedValue(equipment),saveEquipment:jest.fn().mockResolvedValue(equipment)});const audit=jest.fn(),service=new SparePartsService(repo,audit);await service.saveEquipment(null,{...equipment,department_id:6},ctx);await service.saveEquipment(4,{name:'Pump 2'},ctx);expect(tx.equipment).toHaveBeenCalledWith(4,7,true);expect(audit.mock.calls.map(x=>x[0].action)).toEqual(['MAINTAINABLE_EQUIPMENT_CREATED','MAINTAINABLE_EQUIPMENT_UPDATED']);});
 test.each([
  ['general',(s)=>s.update(1,{name:'new',row_version:2},ctx),{get:jest.fn().mockResolvedValue({id:1,row_version:2}),update:jest.fn().mockResolvedValue({id:1})}],
  ['stock',(s)=>s.updateStockPolicy(1,{recommended_min_quantity:2,row_version:2},ctx),{get:jest.fn().mockResolvedValue({id:1,row_version:2}),update:jest.fn().mockResolvedValue({id:1})}],
  ['decision',(s)=>s.decision(1,'APPROVE','',ctx),{get:jest.fn().mockResolvedValue({id:1,row_version:2,technical_approval_status:'UNDER_REVIEW',criticality:'LOW'}),update:jest.fn().mockResolvedValue({id:1})}],
  ['compatibility',(s)=>s.updateCompatibility(1,8,{technical_notes:'new'},ctx),{get:jest.fn().mockResolvedValue({id:1}),compatibilityById:jest.fn().mockResolvedValue({id:8,compatibility_status:'PENDING',technical_notes:'old'}),updateCompatibility:jest.fn().mockResolvedValue({id:8})}]
 ])('%s audit failure rejects the transaction',async(_name,invoke,overrides)=>{const{repo}=transactional(overrides);await expect(invoke(new SparePartsService(repo,jest.fn().mockRejectedValue(new Error('audit failed'))))).rejects.toThrow('audit failed');});
});