import React, { useEffect, useState } from 'react';
import { searchGenericItems } from '../../api/itemMaster';

export default function GenericItemSelector({ value, onChange, disabled = false }) {
  const [query,setQuery]=useState(value?.item_name || '');
  const [options,setOptions]=useState([]);
  const [loading,setLoading]=useState(false);
  useEffect(()=>{if(value?.request_mode==='pending_item_creation')return undefined;let active=true;const timer=setTimeout(async()=>{setLoading(true);try{const result=await searchGenericItems({q:query,status:'active',page_size:10});if(active)setOptions(result.data||[]);}finally{if(active)setLoading(false);}},300);return()=>{active=false;clearTimeout(timer);};},[query,value?.request_mode]);
  if(value?.request_mode==='pending_item_creation') return <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 space-y-2"><div className="flex justify-between"><strong className="text-sm text-amber-900">Pending Item Master review</strong><button type="button" className="text-sm underline" onClick={()=>onChange({request_mode:'generic_item',pending_item:null,item_name:''})}>Search catalog</button></div><input aria-label="Proposed item name" className="w-full border rounded p-2" placeholder="Proposed generic name" value={value.pending_item?.proposed_name||''} onChange={e=>onChange({item_name:e.target.value,pending_item:{...value.pending_item,proposed_name:e.target.value}})} /><div className="grid grid-cols-2 gap-2"><input aria-label="Pending item type" className="border rounded p-2" placeholder="Item type" value={value.pending_item?.item_type||''} onChange={e=>onChange({pending_item:{...value.pending_item,item_type:e.target.value}})} /><input aria-label="Pending category" className="border rounded p-2" placeholder="Category" value={value.pending_item?.category||''} onChange={e=>onChange({pending_item:{...value.pending_item,category:e.target.value}})} /></div><textarea aria-label="Pending item justification" className="w-full border rounded p-2" placeholder="Why no catalog item is suitable" value={value.pending_item?.justification||''} onChange={e=>onChange({restriction_justification:e.target.value,pending_item:{...value.pending_item,justification:e.target.value}})} /></div>;
  return <div className="space-y-2"><input aria-label="Search active Generic Items" className="w-full border rounded p-2" placeholder="Search active Generic Items by code, name or description" value={query} disabled={disabled} onChange={e=>setQuery(e.target.value)} />{loading&&<p className="text-xs text-slate-500">Searching Item Master…</p>}<div className="max-h-52 overflow-auto rounded border bg-white">{options.map(item=><button type="button" key={item.id} onClick={()=>{setQuery(item.generic_name);onChange({generic_item_id:item.id,item_name:item.generic_name,canonical_description_snapshot:item.canonical_description,unit_of_measure:item.inventory_uom,request_mode:'generic_item',catalog_status:'catalogued',pending_item:null});}} className={`block w-full border-b p-2 text-left hover:bg-blue-50 ${Number(value?.generic_item_id)===Number(item.id)?'bg-blue-50':''}`}><span className="font-mono text-xs text-blue-700">{item.item_code}</span> <strong>{item.generic_name}</strong><span className="block text-xs text-slate-600">{item.canonical_description}</span><span className="block text-xs text-slate-500">{item.category} · {item.inventory_uom} · {item.interchangeability_policy}</span></button>)}</div><button type="button" className="text-sm font-medium text-amber-700 underline" onClick={()=>onChange({generic_item_id:null,item_name:'',request_mode:'pending_item_creation',catalog_status:'pending_mapping',pending_item:{proposed_name:'',item_type:'',category:'',justification:''}})}>Cannot find the item</button></div>;
}