import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {listSpareParts} from '../api/spareParts';
import {useAuth} from '../hooks/useAuth';
import {hasPermission} from '../utils/permissions';
const FILTERS=['criticality','technical_approval_status','lifecycle_status','stocking_policy'];
export default function SparePartsRegisterPage(){const{t}=useTranslation();const{user}=useAuth();const[query,setQuery]=useState({page:1,limit:25,search:''});const[result,setResult]=useState({data:[],pagination:{}});const[state,setState]=useState('loading');
useEffect(()=>{let live=true;setState('loading');listSpareParts(query).then(x=>{if(live){setResult(x);setState('ready')}}).catch(()=>live&&setState('error'));return()=>{live=false}},[query]);
const set=(k,v)=>setQuery(q=>({...q,[k]:v,page:1}));return <main className="mx-auto max-w-7xl p-6"><header className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">{t('spareParts.register')}</h1><p className="text-gray-500">{t('spareParts.subtitle')}</p></div>{hasPermission(user,'spare-parts.create')&&<Link className="rounded bg-blue-600 px-4 py-2 text-white" to="/spare-parts/new">{t('spareParts.create')}</Link>}</header><section className="mb-4 grid gap-3 md:grid-cols-5"><input aria-label={t('spareParts.search')} className="rounded border p-2" placeholder={t('spareParts.search')} value={query.search} onChange={e=>set('search',e.target.value)}/>{FILTERS.map(k=><select aria-label={t(`spareParts.${k}`)} className="rounded border p-2" key={k} value={query[k]||''} onChange={e=>set(k,e.target.value)}><option value="">{t('spareParts.all')}</option>{(k==='criticality'?['CRITICAL','HIGH','MEDIUM','LOW']:k==='technical_approval_status'?['DRAFT','UNDER_REVIEW','APPROVED','CONDITIONALLY_APPROVED','REJECTED']:k==='lifecycle_status'?['ACTIVE','INACTIVE','OBSOLETE','SUPERSEDED']:['DO_NOT_STOCK','NORMAL_STOCK','SAFETY_STOCK','STRATEGIC_STOCK','ORDER_ON_DEMAND']).map(v=><option key={v}>{v}</option>)}</select>)}</section>{state==='loading'?<p>{t('common.loading')}</p>:state==='error'?<p role="alert">{t('spareParts.error')}</p>:!result.data.length?<p>{t('spareParts.empty')}</p>:<div className="overflow-x-auto rounded border"><table className="min-w-full text-sm"><thead className="bg-gray-100"><tr>{['code','name','manufacturer','oem','criticality','approval','stocking','equipmentCount','lifecycle','updated'].map(x=><th className="p-3 text-left" key={x}>{t(`spareParts.columns.${x}`)}</th>)}</tr></thead><tbody>{result.data.map(x=><tr className="border-t" key={x.id}><td className="p-3"><Link className="text-blue-600" to={`/spare-parts/${x.id}`}>{x.spare_part_code}</Link></td><td>{x.name}</td><td>{x.manufacturer_name||'—'}</td><td>{x.oem_part_number||'—'}</td><td>{x.criticality}</td><td>{x.technical_approval_status}</td><td>{x.recommended_stocking_policy}</td><td>{x.compatible_equipment_count}</td><td>{x.lifecycle_status}</td><td>{new Date(x.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}<footer className="mt-4 flex justify-between"><button disabled={query.page<=1} onClick={()=>setQuery(q=>({...q,page:q.page-1}))}>{t('common.previous')}</button><span>{query.page} / {Math.max(1,Math.ceil((result.pagination.total||0)/query.limit))}</span><button disabled={query.page*query.limit>=(result.pagination.total||0)} onClick={()=>setQuery(q=>({...q,page:q.page+1}))}>{t('common.next')}</button></footer></main>}