import React,{useEffect,useState} from 'react';
import{useNavigate,useParams}from'react-router-dom';
import{useTranslation}from'react-i18next';
import{createSparePart,getSparePart,updateSparePart,updateStockPolicy}from'../api/spareParts';
import{searchApprovedProducts,searchGenericItems}from'../api/itemMaster';
import{useAuth}from'../hooks/useAuth';
import{hasPermission}from'../utils/permissions';

const STOCK=['recommended_stocking_policy','recommended_min_quantity','recommended_max_quantity','recommended_safety_stock','typical_lead_time_days','estimated_annual_consumption'];
const initial={spare_part_code:'',name:'',spare_part_type:'GENERAL',criticality:'MEDIUM',failure_consequence:'NON_CRITICAL',interchangeability_status:'UNKNOWN',recommended_stocking_policy:'ORDER_ON_DEMAND',is_repairable:false,is_serialized:false,is_consumable:true,is_safety_critical:false};
const enums={spare_part_type:['GENERAL','MECHANICAL','ELECTRICAL','ELECTRONIC','CONSUMABLE'],criticality:['CRITICAL','HIGH','MEDIUM','LOW'],failure_consequence:['PATIENT_SAFETY','EQUIPMENT_SHUTDOWN','SERVICE_DEGRADATION','MAINTENANCE_EFFICIENCY','NON_CRITICAL'],interchangeability_status:['EXACT','INTERCHANGEABLE','CONDITIONAL','NOT_INTERCHANGEABLE','UNKNOWN'],recommended_stocking_policy:['DO_NOT_STOCK','NORMAL_STOCK','SAFETY_STOCK','STRATEGIC_STOCK','ORDER_ON_DEMAND']};
const numberFields=new Set(['shelf_life_days',...STOCK.slice(1)]);
export default function SparePartFormPage(){const{id}=useParams();const nav=useNavigate();const{t}=useTranslation();const{user}=useAuth();const[data,setData]=useState(initial);const[error,setError]=useState('');const[genericQuery,setGenericQuery]=useState('');const[generics,setGenerics]=useState([]);const[products,setProducts]=useState([]);const[itemState,setItemState]=useState('idle');const canStock=hasPermission(user,'spare-parts.manage-stock-policy');
useEffect(()=>{if(id)getSparePart(id).then(setData).catch(()=>setError(t('spareParts.error')))},[id,t]);
useEffect(()=>{let live=true;setItemState('loading');searchGenericItems({q:genericQuery,status:'active',page_size:20}).then(r=>{if(live){setGenerics(r.data||[]);setItemState('ready')}}).catch(()=>live&&setItemState('error'));return()=>{live=false}},[genericQuery]);
useEffect(()=>{if(!data.generic_item_id){setProducts([]);return}let live=true;setItemState('loading');searchApprovedProducts({generic_item_id:data.generic_item_id,status:'approved',page_size:50}).then(r=>{if(live){setProducts(r.data||[]);setItemState('ready')}}).catch(()=>live&&setItemState('error'));return()=>{live=false}},[data.generic_item_id]);
const change=e=>setData(d=>({...d,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
const submit=async e=>{e.preventDefault();setError('');try{let row;if(id){const technical=Object.fromEntries(Object.entries(data).filter(([k])=>!STOCK.includes(k)));row=await updateSparePart(id,technical);if(canStock)row=await updateStockPolicy(id,{...Object.fromEntries(STOCK.map(k=>[k,data[k]])),row_version:row.row_version})}else row=await createSparePart(canStock?data:Object.fromEntries(Object.entries(data).filter(([k])=>!STOCK.includes(k))));nav(`/spare-parts/${row.id}`)}catch(x){setError(x.response?.data?.message||t('spareParts.error'))}};
const field=(name,type='text')=><label key={name} className="text-sm">{t(`spareParts.fields.${name}`)}{enums[name]?<select className="mt-1 w-full rounded border p-2" name={name} value={data[name]??''} onChange={change}>{enums[name].map(x=><option key={x}>{x}</option>)}</select>:type==='textarea'?<textarea className="mt-1 w-full rounded border p-2" name={name} value={data[name]??''} onChange={change}/>:<input className="mt-1 w-full rounded border p-2" type={numberFields.has(name)?'number':type} min={numberFields.has(name)?0:undefined} step={name.includes('quantity')||name==='estimated_annual_consumption'?'any':undefined} name={name} value={data[name]??''} onChange={change} required={['spare_part_code','name'].includes(name)}/>}</label>;
return <main className="mx-auto max-w-4xl p-6"><h1 className="mb-5 text-2xl font-bold">{id?t('spareParts.edit'):t('spareParts.create')}</h1>{error&&<p role="alert" className="mb-3 text-red-600">{error}</p>}<form onSubmit={submit}>
<fieldset className="mb-5 rounded border p-4"><legend className="font-semibold">{t('spareParts.sections.identity')}</legend><div className="grid gap-3 md:grid-cols-2">{['spare_part_code','name','description','spare_part_type'].map(x=>field(x,x==='description'?'textarea':'text'))}</div></fieldset>
<fieldset className="mb-5 rounded border p-4"><legend className="font-semibold">{t('spareParts.sections.technical')}</legend><div className="grid gap-3 md:grid-cols-2">{['manufacturer_name','oem_part_number','manufacturer_part_number','drawing_number','revision','technical_specification','interchangeability_status','shelf_life_days','storage_conditions'].map(x=>field(x,['technical_specification','storage_conditions'].includes(x)?'textarea':'text'))}{['is_repairable','is_serialized','is_consumable','is_safety_critical'].map(name=><label key={name}><input type="checkbox" name={name} checked={!!data[name]} onChange={change}/> {t(`spareParts.fields.${name}`)}</label>)}</div></fieldset>
<fieldset className="mb-5 rounded border p-4"><legend className="font-semibold">{t('spareParts.sections.criticality')}</legend><div className="grid gap-3 md:grid-cols-2">{['criticality','failure_consequence'].map(x=>field(x))}</div></fieldset>
{canStock&&<fieldset className="mb-5 rounded border p-4"><legend className="font-semibold">{t('spareParts.sections.stocking')}</legend><div className="grid gap-3 md:grid-cols-2">{STOCK.map(x=>field(x))}</div></fieldset>}
<fieldset className="mb-5 rounded border p-4"><legend className="font-semibold">{t('spareParts.sections.mapping')}</legend><input aria-label={t('spareParts.searchGeneric')} className="mb-2 w-full rounded border p-2" value={genericQuery} onChange={e=>setGenericQuery(e.target.value)} placeholder={t('spareParts.searchGeneric')}/>{itemState==='loading'&&<p>{t('common.loading')}</p>}{itemState==='error'&&<p role="alert">{t('spareParts.itemMasterError')}</p>}<select aria-label={t('spareParts.fields.generic_item_id')} className="mb-2 w-full rounded border p-2" value={data.generic_item_id||''} onChange={e=>setData(d=>({...d,generic_item_id:e.target.value||null,preferred_approved_product_id:null}))}><option value="">{t('spareParts.noMapping')}</option>{generics.map(x=><option key={x.id} value={x.id}>{x.item_code} — {x.generic_name}</option>)}</select>{itemState==='ready'&&!generics.length&&<p>{t('spareParts.noGenericItems')}</p>}<select aria-label={t('spareParts.fields.preferred_approved_product_id')} disabled={!data.generic_item_id} className="w-full rounded border p-2" value={data.preferred_approved_product_id||''} onChange={e=>setData(d=>({...d,preferred_approved_product_id:e.target.value||null}))}><option value="">{t('spareParts.noMapping')}</option>{products.map(x=><option key={x.id} value={x.id}>{x.product_code||x.id} — {x.trade_name||x.product_name}</option>)}</select>{data.generic_item_id&&itemState==='ready'&&!products.length&&<p>{t('spareParts.noApprovedProducts')}</p>}</fieldset>
<fieldset className="mb-5 rounded border p-4"><legend>{t('spareParts.sections.approval')}</legend><p>{t('spareParts.approvalControlled')}</p></fieldset><button className="rounded bg-blue-600 px-4 py-2 text-white">{t('common.save')}</button></form></main>}