import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {useAuth} from '../hooks/useAuth';
import {hasAnyPermission} from '../utils/permissions';
import {listMappings,mappingCoverage,mappingAction} from '../api/stockItemMappings';
const FILTERS=['category','subcategory','uom','manufacturer','mapping_status','identity_source','confidence_min','confidence_max','import_batch','parser_version','positive_stock_balance','transaction_history'];
export function isBulkApprovalSafe(rows,user){return rows.length>0&&hasAnyPermission(user,['item-master.stock-map.bulk'])&&new Set(rows.map(r=>`${r.generic_item_id}:${r.approved_product_id||''}`)).size===1&&rows.every(r=>!(r.hard_exclusions||[]).length&&!r.required_attributes_unresolved&&!r.stale)&&new Set(rows.map(r=>r.parser_version)).size===1;}
export default function StockItemMappingWorkspace(){const{user}=useAuth();const[filters,setFilters]=useState({});const[rows,setRows]=useState([]);const[coverage,setCoverage]=useState({});const[error,setError]=useState('');const[selected,setSelected]=useState([]);const canOverride=hasAnyPermission(user,['item-master.stock-map.override']);
 const load=useCallback(async()=>{try{setError('');const[data,counts]=await Promise.all([listMappings(filters),mappingCoverage()]);setRows(data.data||[]);setCoverage(counts);}catch(e){setError(e.response?.data?.code==='database_capability_unavailable'?'Mapping capability is not available in this environment.':'Unable to load mapping workspace.');}},[filters]);useEffect(()=>{load();},[load]);
 const bulkSafe=useMemo(()=>isBulkApprovalSafe(rows.filter(r=>selected.includes(r.id)),user),[rows,selected,user]);
 const act=async(row,action)=>{await mappingAction(row.id,action,{stock_item_id:row.stock_item_id,expected_version:row.version,reason:`Steward ${action}`});load();};
 return <main className="p-6 space-y-5"><header><h1 className="text-2xl font-bold">Stock Item Mapping Steward Workspace</h1><p className="text-sm text-gray-600">Coverage, queue, candidates, import provenance and immutable mapping history.</p></header>{error&&<div role="alert" className="rounded bg-amber-100 p-3">{error}</div>}
 <section className="grid grid-cols-3 gap-3">{['total','mapped','unmapped'].map(k=><div key={k} className="rounded border p-3"><b>{k.replace('_',' ')}</b><div>{coverage[k]??'—'}</div></div>)}</section>
 <section className="grid grid-cols-2 md:grid-cols-4 gap-2">{FILTERS.map(name=><label key={name} className="text-xs">{name.replaceAll('_',' ')}<input className="w-full border rounded p-1" value={filters[name]||''} onChange={e=>setFilters(v=>({...v,[name]:e.target.value,page:1}))}/></label>)}</section>
 <div className="flex gap-2"><button disabled={!bulkSafe} className="border rounded px-3 py-1 disabled:opacity-40">Bulk approve</button><span className="text-xs text-gray-500">Bulk approval requires one safe target, one parser template, resolved attributes, fresh versions and bulk permission.</span></div>
 <div className="overflow-auto"><table className="min-w-full text-sm"><thead><tr>{['','Stock item','Source attributes','Target attributes','Status','Confidence','Parser','Actions'].map(x=><th className="border p-2" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id?`mapping-${row.id}`:`stock-${row.stock_item_id}`}><td className="border p-2">{row.id&&<input type="checkbox" aria-label={`Select mapping ${row.id}`} checked={selected.includes(row.id)} onChange={()=>setSelected(v=>v.includes(row.id)?v.filter(id=>id!==row.id):[...v,row.id])}/>}</td><td className="border p-2"><div className="font-medium">{row.stock_item_name||`Stock item #${row.stock_item_id}`}</div><div className="text-xs text-gray-500">#{row.stock_item_id}</div></td><td className="border p-2"><pre>{JSON.stringify(row.source_attributes||{},null,1)}</pre></td><td className="border p-2"><pre>{JSON.stringify(row.target_attributes||{generic_item_id:row.generic_item_id,approved_product_id:row.approved_product_id},null,1)}</pre></td><td className="border p-2">{row.mapping_status}</td><td className="border p-2">{row.confidence??'—'}</td><td className="border p-2">{row.parser_version||'—'}</td><td className="border p-2 space-x-1">{!row.id?<span className="text-xs text-gray-500">No mapping proposal</span>:<>{row.mapping_status==='proposed'&&<button onClick={()=>act(row,'review')}>Review</button>}{row.mapping_status==='review_required'&&<><button onClick={()=>act(row,'approve')}>Approve</button><button onClick={()=>act(row,'reject')}>Reject</button></>}<button onClick={()=>act(row,'mark-duplicate')}>Duplicate</button><button onClick={()=>act(row,'mark-obsolete')}>Obsolete</button><button onClick={()=>act(row,'exclude')}>Exclude</button>{canOverride&&row.mapping_status==='approved'&&<span> Supersede / Rollback available in detail</span>}</>}</td></tr>)}</tbody></table></div>
 <section><h2 className="font-semibold">Import batches, invalid rows, candidate comparison and audit history</h2><p className="text-sm text-gray-600">Select a mapping or import batch to inspect source fragments, hard conflicts, prior decisions and audit events.</p></section></main>}