const pool=require('../config/db');
const audit=require('./auditService').writeAuditEvent;
const failure=(statusCode,message)=>Object.assign(new Error(message),{statusCode});
const actorScope=actor=>{if(!actor?.instituteId)throw failure(403,'Institute context is required');return actor.instituteId;};
async function transaction(work){const c=await pool.connect();try{await c.query('BEGIN');const result=await work(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
async function list(actor){const instituteId=actorScope(actor);return (await pool.query(`SELECT d.*,du.name delegate_user_name,ou.name authority_unit_name,op.position_name FROM approval_authority_delegations d JOIN users du ON du.id=d.delegate_user_id LEFT JOIN organization_positions op ON op.id=d.organization_position_id LEFT JOIN organization_units ou ON ou.id=op.organization_unit_id WHERE d.institute_id=$1 ORDER BY d.effective_from DESC`,[instituteId])).rows;}
async function create(body,actor){const instituteId=actorScope(actor);if(!body.scope||!body.reason?.trim())throw failure(400,'Scope and reason are required');if(!body.delegatorUserId&&!body.organizationPositionId)throw failure(400,'Delegator or structural authority is required');if(String(body.delegatorUserId)===String(body.delegateUserId))throw failure(400,'Self-delegation is not permitted');if(!body.effectiveFrom||!body.effectiveTo||body.effectiveTo<body.effectiveFrom)throw failure(400,'A valid bounded effective period is required');return transaction(async c=>{const delegate=(await c.query('SELECT id FROM users WHERE id=$1 AND institute_id=$2 AND COALESCE(is_active,true)',[body.delegateUserId,instituteId])).rows[0];if(!delegate)throw failure(422,'Delegate must be active in the same institute');if(body.delegatorUserId){const owner=(await c.query('SELECT id FROM users WHERE id=$1 AND institute_id=$2',[body.delegatorUserId,instituteId])).rows[0];if(!owner)throw failure(422,'Delegator must belong to the same institute');}if(body.organizationPositionId){const position=(await c.query('SELECT op.user_id FROM organization_positions op JOIN organization_units ou ON ou.id=op.organization_unit_id WHERE op.id=$1 AND ou.institute_id=$2',[body.organizationPositionId,instituteId])).rows[0];if(!position)throw failure(422,'Structural authority must belong to the same institute');if(body.delegatorUserId&&String(position.user_id)!==String(body.delegatorUserId))throw failure(422,'Delegator is not the structural position holder');}
const conflict=(await c.query(`SELECT id FROM approval_authority_delegations WHERE institute_id=$1 AND status='ACTIVE' AND scope=$2 AND (($3::bigint IS NOT NULL AND organization_position_id=$3) OR ($3::bigint IS NULL AND organization_position_id IS NULL AND delegator_user_id=$4)) AND tstzrange(effective_from,effective_to,'[]') && tstzrange($5,$6,'[]') FOR UPDATE`,[instituteId,body.scope,body.organizationPositionId||null,body.delegatorUserId||null,body.effectiveFrom,body.effectiveTo])).rows;if(conflict.length)throw failure(409,'An overlapping delegation already exists for this authority and scope');
const row=(await c.query(`INSERT INTO approval_authority_delegations(institute_id,organization_position_id,delegator_user_id,delegate_user_id,effective_from,effective_to,scope,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[instituteId,body.organizationPositionId||null,body.delegatorUserId||null,body.delegateUserId,body.effectiveFrom,body.effectiveTo,body.scope,body.reason.trim(),actor.id])).rows[0];await audit({client:c,entityType:'approval_authority_delegation',entityId:row.id,action:'APPROVAL_AUTHORITY_DELEGATED',actorUserId:actor.id,afterData:row});return row;});}
async function revoke(id,body,actor){const instituteId=actorScope(actor);if(!body.reason?.trim())throw failure(400,'Revocation reason is required');return transaction(async c=>{const before=(await c.query("SELECT * FROM approval_authority_delegations WHERE id=$1 AND institute_id=$2 AND status='ACTIVE' FOR UPDATE",[id,instituteId])).rows[0];if(!before)throw failure(404,'Active delegation not found');const row=(await c.query("UPDATE approval_authority_delegations SET status='REVOKED',revoked_by=$3,revoked_at=now(),revocation_reason=$4,row_version=row_version+1 WHERE id=$1 AND institute_id=$2 RETURNING *",[id,instituteId,actor.id,body.reason.trim()])).rows[0];await audit({client:c,entityType:'approval_authority_delegation',entityId:id,action:'APPROVAL_AUTHORITY_DELEGATION_REVOKED',actorUserId:actor.id,beforeData:before,afterData:row});return row;});}
async function resolve(input,client=pool){const at=input.at||new Date();const rows=(await client.query(`SELECT d.id,d.delegate_user_id "delegateUserId",u.name "delegateUserName" FROM approval_authority_delegations d JOIN users u ON u.id=d.delegate_user_id AND u.institute_id=d.institute_id AND COALESCE(u.is_active,true) WHERE d.institute_id=$1 AND d.scope=$2 AND d.status='ACTIVE' AND d.effective_from<=$5 AND d.effective_to>=$5 AND (($3::bigint IS NOT NULL AND d.organization_position_id=$3) OR (d.organization_position_id IS NULL AND d.delegator_user_id=$4))`,[input.instituteId,input.scope,input.positionId||null,input.delegatorUserId,at])).rows;return rows.length>1?{ambiguous:true}:rows[0]||null;}
module.exports={list,create,revoke,resolve,transaction};