const FixedAssetRepository = require('../repositories/fixedAssetRepository');
const { values, transitions, assertOption } = require('../domain/fixedAssetConstants');
const { writeAuditEvent } = require('./auditService');
const error = (statusCode, message, code) => Object.assign(new Error(message), { statusCode, code });
const integer = value => value == null || value === '' ? null : Number.parseInt(value, 10);
const context = user => ({ instituteId: user.institute_id, userId: user.id });

class FixedAssetService {
  constructor(repo = new FixedAssetRepository(), audit = writeAuditEvent) { this.repo = repo; this.audit = audit; }
  options() { return values; }
  async list(query, ctx) {
    const page = Math.max(1, integer(query.page) || 1), limit = Math.min(100, Math.max(1, integer(query.limit) || 25));
    const clauses = ['a.institute_id=$1'], params = [ctx.instituteId];
    const filters = { category:'asset_category_id', department:'responsible_department_id', location:'current_location_id', assetClass:'asset_class', ownershipType:'ownership_type', condition:'condition', operationalStatus:'operational_status', reconciliationStatus:'reconciliation_status', acquisitionMethod:'acquisition_method', active:'is_active' };
    for (const [key, column] of Object.entries(filters)) if (query[key] !== undefined && query[key] !== '') { params.push(query[key]); clauses.push(`a.${column}=$${params.length}`); }
    if (query.search) { params.push(`%${query.search}%`); clauses.push(`(a.asset_number ILIKE $${params.length} OR a.description ILIKE $${params.length} OR a.serial_number ILIKE $${params.length} OR a.manufacturer ILIKE $${params.length} OR a.model ILIKE $${params.length})`); }
    if (query.tagged === 'true') clauses.push('EXISTS (SELECT 1 FROM asset_tags t WHERE t.asset_id=a.id AND t.tag_status=\'ACTIVE\')');
    if (query.tagged === 'false') clauses.push('NOT EXISTS (SELECT 1 FROM asset_tags t WHERE t.asset_id=a.id AND t.tag_status=\'ACTIVE\')');
    const sortMap = { assetNumber:'asset_number', description:'description', createdAt:'created_at', status:'operational_status' }, sort = sortMap[query.sort] || 'asset_number', direction = String(query.direction).toLowerCase() === 'desc' ? 'DESC' : 'ASC';
    const where = clauses.join(' AND '), count = await this.repo.query(`SELECT count(*)::int total FROM assets a WHERE ${where}`, params);
    params.push(limit, (page - 1) * limit);
    const result = await this.repo.query(`SELECT a.*,c.name category_name,d.name department_name,l.name location_name,EXISTS(SELECT 1 FROM asset_tags t WHERE t.asset_id=a.id AND t.tag_status='ACTIVE') rfid_tagged FROM assets a LEFT JOIN asset_categories c ON c.id=a.asset_category_id LEFT JOIN departments d ON d.id=a.responsible_department_id LEFT JOIN asset_locations l ON l.id=a.current_location_id WHERE ${where} ORDER BY a.${sort} ${direction},a.id LIMIT $${params.length-1} OFFSET $${params.length}`, params);
    return { data: result.rows, pagination: { page, limit, total: count.rows[0].total, pages: Math.ceil(count.rows[0].total / limit) } };
  }
  async get(id, ctx) { const row = await this.repo.asset(id, ctx.instituteId); if (!row) throw error(404, 'Asset not found'); return row; }
  async create(input, ctx) {
    if (!String(input.description || '').trim()) throw error(400, 'Description is required');
    ['assetClass','acquisitionMethod','ownershipType','condition','operationalStatus','reconciliationStatus','creationSource'].forEach(k => assertOption(k, input[k]));
    if (input.acquisitionCost != null && !/^\d+(\.\d{1,4})?$/.test(String(input.acquisitionCost))) throw error(400, 'Acquisition cost must be a non-negative decimal');
    return this.repo.transaction(async tx => {
      await this.validateLinks(input, ctx, tx);
      const result = await tx.query(`INSERT INTO assets(institute_id,asset_number,asset_class,asset_category_id,description,generic_item_id,approved_product_id,stock_item_id,manufacturer,model,serial_number,finance_asset_number,acquisition_method,purchase_request_id,requested_item_id,purchase_order_id,purchase_order_item_id,goods_receipt_id,goods_receipt_item_id,supplier_id,acquisition_date,acquisition_cost,currency,capitalization_status,ownership_type,owner_name,responsible_department_id,current_location_id,condition,operational_status,reconciliation_status,warranty_expiry,creation_source,notes,created_by,updated_by) VALUES($1,next_asset_number($1),$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$34) RETURNING *`, [ctx.instituteId,input.assetClass,integer(input.assetCategoryId),input.description.trim(),integer(input.genericItemId),integer(input.approvedProductId),integer(input.stockItemId),input.manufacturer||null,input.model||null,input.serialNumber||null,input.financeAssetNumber||null,input.acquisitionMethod,integer(input.purchaseRequestId),integer(input.requestedItemId),integer(input.purchaseOrderId),integer(input.purchaseOrderItemId),integer(input.goodsReceiptId),integer(input.goodsReceiptItemId),integer(input.supplierId),input.acquisitionDate||null,input.acquisitionCost??null,input.currency||null,input.capitalizationStatus||'NOT_ASSESSED',input.ownershipType,input.ownerName||null,integer(input.responsibleDepartmentId),integer(input.currentLocationId),input.condition,input.operationalStatus,input.reconciliationStatus,input.warrantyExpiry||null,input.creationSource,input.notes||null,ctx.userId]);
      const row = result.rows[0]; await this.audit({entityType:'ASSET',entityId:row.id,action:'ASSET_CREATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:row,client:tx.db}); return { asset: row, warnings: await this.duplicateSerialWarnings(row, ctx, tx) };
    });
  }
  async validateLinks(input, ctx, tx) {
    const checks = [
      ['asset_categories',integer(input.assetCategoryId),'SELECT id FROM asset_categories WHERE id=$1 AND institute_id=$2'],['asset_locations',integer(input.currentLocationId),'SELECT id FROM asset_locations WHERE id=$1 AND institute_id=$2'],['departments',integer(input.responsibleDepartmentId),'SELECT id FROM departments WHERE id=$1 AND institute_id=$2'],['generic_items',integer(input.genericItemId),'SELECT id FROM generic_items WHERE id=$1 AND institute_id=$2'],['approved_products',integer(input.approvedProductId),'SELECT id FROM approved_products WHERE id=$1 AND institute_id=$2'],['stock_items',integer(input.stockItemId),'SELECT id FROM stock_items WHERE id=$1 AND institute_id=$2'],['requests',integer(input.purchaseRequestId),'SELECT id FROM requests WHERE id=$1 AND institute_id=$2'],['requested_items',integer(input.requestedItemId),'SELECT ri.id FROM requested_items ri JOIN requests r ON r.id=ri.request_id WHERE ri.id=$1 AND r.institute_id=$2'],['purchase_orders',integer(input.purchaseOrderId),'SELECT po.id FROM purchase_orders po JOIN requests r ON r.id=po.request_id WHERE po.id=$1 AND r.institute_id=$2'],['purchase_order_items',integer(input.purchaseOrderItemId),'SELECT pi.id FROM purchase_order_items pi JOIN purchase_orders po ON po.id=pi.purchase_order_id JOIN requests r ON r.id=po.request_id WHERE pi.id=$1 AND r.institute_id=$2'],['goods_receipts',integer(input.goodsReceiptId),'SELECT gr.id FROM goods_receipts gr JOIN requests r ON r.id=gr.request_id WHERE gr.id=$1 AND r.institute_id=$2'],['goods_receipt_items',integer(input.goodsReceiptItemId),'SELECT gi.id FROM goods_receipt_items gi JOIN goods_receipts gr ON gr.id=gi.goods_receipt_id JOIN requests r ON r.id=gr.request_id WHERE gi.id=$1 AND r.institute_id=$2'],['suppliers',integer(input.supplierId),'SELECT id FROM suppliers WHERE id=$1 AND institute_id=$2']];
    for (const [table,id,sql] of checks) if (id) { const r=await tx.query(sql,[id,ctx.instituteId]); if(!r.rowCount) throw error(400,`Invalid or foreign ${table} reference`); }
  }
  async duplicateSerialWarnings(asset, ctx, tx=this.repo) { if (!asset.serial_number) return []; const r=await tx.query(`SELECT id,asset_number FROM assets WHERE institute_id=$1 AND id<>$2 AND lower(coalesce(manufacturer,''))=lower($3) AND lower(coalesce(model,''))=lower($4) AND lower(serial_number)=lower($5) LIMIT 10`,[ctx.instituteId,asset.id,asset.manufacturer||'',asset.model||'',asset.serial_number]); return r.rows.length ? [{code:'DUPLICATE_SERIAL_CANDIDATE',matches:r.rows}] : []; }
  async update(id, input, ctx) { return this.repo.transaction(async tx => { const before=await tx.asset(id,ctx.instituteId,true); if(!before) throw error(404,'Asset not found'); if(input.assetNumber && input.assetNumber!==before.asset_number) throw error(409,'Asset number is permanent'); const allowed={description:'description',manufacturer:'manufacturer',model:'model',serialNumber:'serial_number',notes:'notes',condition:'condition',operationalStatus:'operational_status',reconciliationStatus:'reconciliation_status',responsibleDepartmentId:'responsible_department_id',currentLocationId:'current_location_id',isActive:'is_active'}; const entries=Object.entries(input).filter(([k])=>allowed[k]); if(!entries.length) throw error(400,'No editable fields supplied'); if(input.operationalStatus) assertOption('operationalStatus',input.operationalStatus); const params=entries.map(([,v])=>v), sets=entries.map(([k],i)=>`${allowed[k]}=$${i+1}`); params.push(ctx.userId,id,ctx.instituteId,input.rowVersion); const r=await tx.query(`UPDATE assets SET ${sets.join(',')},updated_by=$${params.length-3},updated_at=now(),row_version=row_version+1 WHERE id=$${params.length-2} AND institute_id=$${params.length-1} AND row_version=$${params.length} RETURNING *`,params); if(!r.rowCount) throw error(409,'Asset was changed by another user','ASSET_VERSION_CONFLICT'); await this.audit({entityType:'ASSET',entityId:id,action:'ASSET_UPDATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,beforeData:before,afterData:r.rows[0],client:tx.db}); return {asset:r.rows[0],warnings:await this.duplicateSerialWarnings(r.rows[0],ctx,tx)}; }); }
  async categories(ctx) { return (await this.repo.query('SELECT * FROM asset_categories WHERE institute_id=$1 ORDER BY name',[ctx.instituteId])).rows; }
  async locations(ctx) { return (await this.repo.query('SELECT * FROM asset_locations WHERE institute_id=$1 ORDER BY name',[ctx.instituteId])).rows; }
  async saveLocation(id,input,ctx) { assertOption('locationType',input.locationType); return this.repo.transaction(async tx=>{ if(id&&Number(id)===integer(input.parentLocationId)) throw error(400,'Location cannot parent itself'); if(input.parentLocationId){const p=await tx.location(integer(input.parentLocationId),ctx.instituteId);if(!p||!p.is_active)throw error(400,'Parent must be active and in this institute');if(id){const cycle=await tx.query('WITH RECURSIVE d AS (SELECT id,parent_location_id FROM asset_locations WHERE id=$1 UNION ALL SELECT l.id,l.parent_location_id FROM asset_locations l JOIN d ON l.parent_location_id=d.id) SELECT 1 FROM d WHERE id=$2',[id,input.parentLocationId]);if(cycle.rowCount)throw error(400,'Location hierarchy cycle');}} const r=id?await tx.query('UPDATE asset_locations SET code=$1,name=$2,location_type=$3,parent_location_id=$4,department_id=$5,section_id=$6,is_active=$7,updated_by=$8,updated_at=now() WHERE id=$9 AND institute_id=$10 RETURNING *',[input.code,input.name,input.locationType,integer(input.parentLocationId),integer(input.departmentId),integer(input.sectionId),input.isActive!==false,ctx.userId,id,ctx.instituteId]):await tx.query('INSERT INTO asset_locations(institute_id,code,name,location_type,parent_location_id,department_id,section_id,is_active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING *',[ctx.instituteId,input.code,input.name,input.locationType,integer(input.parentLocationId),integer(input.departmentId),integer(input.sectionId),input.isActive!==false,ctx.userId]);if(!r.rowCount)throw error(404,'Location not found');await this.audit({entityType:'ASSET_LOCATION',entityId:r.rows[0].id,action:id?'ASSET_LOCATION_UPDATED':'ASSET_LOCATION_CREATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:r.rows[0],client:tx.db});return r.rows[0];}); }
  async movements(assetId,ctx){await this.get(assetId,ctx);return(await this.repo.query('SELECT * FROM asset_movements WHERE asset_id=$1 AND institute_id=$2 ORDER BY requested_at DESC',[assetId,ctx.instituteId])).rows;}
  async requestMovement(assetId,input,ctx){assertOption('movementType',input.movementType);return this.repo.transaction(async tx=>{const asset=await tx.asset(assetId,ctx.instituteId,true);if(!asset)throw error(404,'Asset not found');if(asset.operational_status==='DISPOSED')throw error(409,'Disposed assets cannot be moved');if(input.toLocationId&&!await tx.location(integer(input.toLocationId),ctx.instituteId))throw error(400,'Invalid or foreign destination');const r=await tx.query(`INSERT INTO asset_movements(institute_id,asset_id,from_department_id,from_location_id,to_department_id,to_location_id,movement_type,requested_by,expected_return_at,reason,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'PENDING_APPROVAL') RETURNING *`,[ctx.instituteId,asset.id,asset.responsible_department_id,asset.current_location_id,integer(input.toDepartmentId),integer(input.toLocationId),input.movementType,ctx.userId,input.expectedReturnAt||null,input.reason]);await this.audit({entityType:'ASSET_MOVEMENT',entityId:r.rows[0].id,action:'ASSET_MOVEMENT_REQUESTED',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:r.rows[0],client:tx.db});return r.rows[0];});}
  async transitionMovement(id,toStatus,ctx){assertOption('movementStatus',toStatus);return this.repo.transaction(async tx=>{const q=await tx.query('SELECT * FROM asset_movements WHERE id=$1 AND institute_id=$2 FOR UPDATE',[id,ctx.instituteId]);const before=q.rows[0];if(!before)throw error(404,'Movement not found');if(before.status===toStatus)return before;if(!transitions[before.status]?.includes(toStatus))throw error(409,`Cannot transition ${before.status} to ${toStatus}`);const fields={APPROVED:['approved_by','approved_at'],IN_TRANSIT:['dispatched_by','dispatched_at'],RECEIVED:['received_by','received_at'],RETURNED:['received_by','actual_return_at']}[toStatus];let sql='UPDATE asset_movements SET status=$1,updated_at=now()',params=[toStatus];if(fields){sql+=`,${fields[0]}=$2,${fields[1]}=now()`;params.push(ctx.userId);}params.push(id,ctx.instituteId);sql+=` WHERE id=$${params.length-1} AND institute_id=$${params.length} RETURNING *`;const row=(await tx.query(sql,params)).rows[0];if(toStatus==='RECEIVED'){await tx.query('UPDATE assets SET current_location_id=$1,responsible_department_id=COALESCE($2,responsible_department_id),row_version=row_version+1,updated_at=now(),updated_by=$3 WHERE id=$4 AND institute_id=$5',[row.to_location_id,row.to_department_id,ctx.userId,row.asset_id,ctx.instituteId]);}await this.audit({entityType:'ASSET_MOVEMENT',entityId:id,action:`ASSET_MOVEMENT_${toStatus}`,actorUserId:ctx.userId,instituteId:ctx.instituteId,beforeData:before,afterData:row,client:tx.db});return row;});}
}
module.exports={FixedAssetService,context};