const FixedAssetRepository = require('../repositories/fixedAssetRepository');
const { values, transitions, assertOption } = require('../domain/fixedAssetConstants');
const { writeAuditEvent } = require('./auditService');
const error = (statusCode, message, code) => Object.assign(new Error(message), { statusCode, code });
const integer = value => value == null || value === '' ? null : Number.parseInt(value, 10);
const context = user => ({ instituteId: user.institute_id, userId: user.id });
const dateOnly = (value, field) => {
  if (value == null || value === '') return null;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(String(value))) throw error(400, `${field} must be a date in YYYY-MM-DD format`);
  return String(value);
};
const decimal = (value, scale, field) => {
  if (value == null || value === '') return null;
  const pattern = new RegExp(`^\\d+(?:\\.\\d{1,${scale}})?$`);
  if (!pattern.test(String(value))) throw error(400, `${field} must be a non-negative decimal with at most ${scale} decimal places`);
  return String(value);
};
const baselineAssetCategories = [
  { code: 'IT_EQUIPMENT', name: 'IT Equipment', description: 'Computers, networking, communications, and related technology assets.' },
  { code: 'MEDICAL_EQUIPMENT', name: 'Medical Equipment', description: 'Clinical, diagnostic, laboratory, and patient-care equipment.' },
  { code: 'OFFICE_EQUIPMENT', name: 'Office Equipment', description: 'General office machines and operational equipment.' },
  { code: 'FURNITURE_FIXTURES', name: 'Furniture and Fixtures', description: 'Furniture, fittings, and installed fixtures.' },
  { code: 'PLANT_MACHINERY', name: 'Plant and Machinery', description: 'Plant, machinery, generators, and other heavy equipment.' },
  { code: 'VEHICLES', name: 'Vehicles', description: 'Road vehicles and other transport assets.' },
  { code: 'BUILDINGS_INFRASTRUCTURE', name: 'Buildings and Infrastructure', description: 'Buildings, structural improvements, and infrastructure.' },
  { code: 'OTHER', name: 'Other', description: 'Controlled or capital assets not covered by another governed category.' },
];

class FixedAssetService {
  constructor(repo = new FixedAssetRepository(), audit = writeAuditEvent) { this.repo = repo; this.audit = audit; }
  options() { return values; }
  async list(query, ctx) {
    const page = Math.max(1, integer(query.page) || 1), limit = Math.min(100, Math.max(1, integer(query.limit) || 25));
    const clauses = ['a.institute_id=$1'], params = [ctx.instituteId];
    const filters = { category:'asset_category_id', department:'responsible_department_id', location:'current_location_id', assetClass:'asset_class', ownershipType:'ownership_type', condition:'condition', operationalStatus:'operational_status', reconciliationStatus:'reconciliation_status', acquisitionMethod:'acquisition_method', active:'is_active' };
    for (const [key, column] of Object.entries(filters)) if (query[key] !== undefined && query[key] !== '') { params.push(query[key]); clauses.push(`a.${column}=$${params.length}`); }
    if (query.search) { params.push(`%${query.search}%`); clauses.push(`(a.asset_number ILIKE $${params.length} OR a.description ILIKE $${params.length} OR a.serial_number ILIKE $${params.length} OR a.manufacturer ILIKE $${params.length} OR a.model ILIKE $${params.length})`); }
    if (query.tagged === 'true') clauses.push('EXISTS (SELECT 1 FROM asset_tags t WHERE t.asset_id=a.id AND t.tag_status=\'ACTIVE\')');
    if (query.tagged === 'false') clauses.push('NOT EXISTS (SELECT 1 FROM asset_tags t WHERE t.asset_id=a.id AND t.tag_status=\'ACTIVE\')');
    const sortMap = { assetNumber:'asset_number', description:'description', createdAt:'created_at', status:'operational_status' }, sort = sortMap[query.sort] || 'asset_number', direction = String(query.direction).toLowerCase() === 'desc' ? 'DESC' : 'ASC';
    const where = clauses.join(' AND '), count = await this.repo.query(`SELECT count(*)::int total FROM assets a WHERE ${where}`, params);
    params.push(limit, (page - 1) * limit);
    const result = await this.repo.query(`SELECT a.*,c.name category_name,d.name department_name,l.name location_name,EXISTS(SELECT 1 FROM asset_tags t WHERE t.asset_id=a.id AND t.tag_status='ACTIVE') rfid_tagged FROM assets a LEFT JOIN asset_categories c ON c.id=a.asset_category_id LEFT JOIN departments d ON d.id=a.responsible_department_id LEFT JOIN asset_locations l ON l.id=a.current_location_id WHERE ${where} ORDER BY a.${sort} ${direction},a.id LIMIT $${params.length-1} OFFSET $${params.length}`, params);
    return { data: result.rows, pagination: { page, limit, total: count.rows[0].total, pages: Math.ceil(count.rows[0].total / limit) } };
  }
  async get(id, ctx) {
    const result=await this.repo.query(`SELECT a.*,c.name category_name,d.name responsible_department_name,s.name responsible_section_name,l.name current_location_name,l.code current_location_code,
        i.name institute_name,pr.id procurement_pr_id,ri.id procurement_requested_item_id,po.id procurement_po_id,poi.id procurement_po_item_id,gr.id procurement_gr_id,gri.id procurement_gr_item_id,sup.name supplier_name
      FROM assets a LEFT JOIN asset_categories c ON c.id=a.asset_category_id
      LEFT JOIN departments d ON d.id=a.responsible_department_id LEFT JOIN sections s ON s.id=a.responsible_section_id
      LEFT JOIN asset_locations l ON l.id=a.current_location_id LEFT JOIN institutes i ON i.id=a.institute_id
      LEFT JOIN requests pr ON pr.id=a.purchase_request_id LEFT JOIN requested_items ri ON ri.id=a.requested_item_id
      LEFT JOIN purchase_orders po ON po.id=a.purchase_order_id LEFT JOIN purchase_order_items poi ON poi.id=a.purchase_order_item_id
      LEFT JOIN goods_receipts gr ON gr.id=a.goods_receipt_id LEFT JOIN goods_receipt_items gri ON gri.id=a.goods_receipt_item_id LEFT JOIN suppliers sup ON sup.id=a.supplier_id
      WHERE a.id=$1 AND a.institute_id=$2`,[id,ctx.instituteId]);
    const row=result.rows[0];if(!row)throw error(404,'Asset not found');
    const [custody,movements,tags,events,exceptions]=await Promise.all([
      this.repo.query(`SELECT cr.*,u.name custodian_name,d.name custodian_department_name FROM custody_records cr LEFT JOIN users u ON u.id=cr.custodian_user_id LEFT JOIN departments d ON d.id=cr.custodian_department_id WHERE cr.asset_id=$1 ORDER BY cr.created_at DESC`,[id]),
      this.repo.query('SELECT * FROM asset_movements WHERE asset_id=$1 AND institute_id=$2 ORDER BY requested_at DESC',[id,ctx.instituteId]),
      this.repo.query('SELECT * FROM asset_tags WHERE asset_id=$1 AND institute_id=$2 ORDER BY created_at DESC',[id,ctx.instituteId]),
      this.repo.query('SELECT * FROM rfid_business_events WHERE asset_id=$1 AND institute_id=$2 ORDER BY first_seen_at DESC LIMIT 100',[id,ctx.instituteId]),
      this.repo.query("SELECT * FROM asset_exceptions WHERE asset_id=$1 AND institute_id=$2 AND status<>'RESOLVED' ORDER BY detected_at DESC",[id,ctx.instituteId]),
    ]);return{...row,custody:custody.rows,movements:movements.rows,tags:tags.rows,rfid_events:events.rows,open_exceptions:exceptions.rows};
  }
  async create(input, ctx) {
    if (!String(input.description || '').trim()) throw error(400, 'Description is required');
    ['assetClass','acquisitionMethod','ownershipType','condition','operationalStatus','reconciliationStatus','creationSource'].forEach(k => assertOption(k, input[k]));
    const amount=decimal(input.acquisitionCost,4,'Acquisition amount'), currency=amount?String(input.currency||'').toUpperCase():null;
    if(currency&&!/^[A-Z]{3}$/.test(currency))throw error(400,'A governed acquisition currency is required');
    const rate=amount?(currency==='IQD'?'1':decimal(input.exchangeRateToIqd,6,'Exchange rate to IQD')):null;
    if(amount&&!rate)throw error(400,'Exchange rate to IQD is required for foreign currency acquisition');
    const acquisitionDate=dateOnly(input.acquisitionDate,'Acquisition date'),deploymentDate=dateOnly(input.deploymentDate,'Deployment date');
    return this.repo.transaction(async tx => {
      await this.validateLinks(input, ctx, tx);
      const result = await tx.query(`INSERT INTO assets(institute_id,asset_number,asset_class,asset_category_id,description,generic_item_id,approved_product_id,stock_item_id,manufacturer,model,serial_number,finance_asset_number,acquisition_method,purchase_request_id,requested_item_id,purchase_order_id,purchase_order_item_id,goods_receipt_id,goods_receipt_item_id,supplier_id,acquisition_date,acquisition_cost,currency,acquisition_currency,exchange_rate_to_iqd,acquisition_amount_iqd,exchange_rate_effective_date,exchange_rate_source,capitalization_status,ownership_type,owner_name,responsible_department_id,responsible_section_id,current_location_id,deployment_date,condition,operational_status,reconciliation_status,warranty_expiry,creation_source,notes,created_by,updated_by) VALUES($1,next_asset_number($1),$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$22,$23,CASE WHEN $21::numeric IS NULL THEN NULL ELSE round($21::numeric*$23::numeric) END,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$39) RETURNING *`, [ctx.instituteId,input.assetClass,integer(input.assetCategoryId),input.description.trim(),integer(input.genericItemId),integer(input.approvedProductId),integer(input.stockItemId),input.manufacturer||null,input.model||null,input.serialNumber||null,input.financeAssetNumber||null,input.acquisitionMethod,integer(input.purchaseRequestId),integer(input.requestedItemId),integer(input.purchaseOrderId),integer(input.purchaseOrderItemId),integer(input.goodsReceiptId),integer(input.goodsReceiptItemId),integer(input.supplierId),acquisitionDate,amount,currency,rate,dateOnly(input.exchangeRateEffectiveDate,'Exchange-rate effective date'),input.exchangeRateSource||null,input.capitalizationStatus||'NOT_ASSESSED',input.ownershipType,input.ownerName||null,integer(input.responsibleDepartmentId),integer(input.responsibleSectionId),integer(input.currentLocationId),deploymentDate,input.condition,input.operationalStatus,input.reconciliationStatus,dateOnly(input.warrantyExpiry,'Warranty expiry'),input.creationSource,input.notes||null,ctx.userId]);
      const row = result.rows[0];
      await this.audit({entityType:'ASSET',entityId:row.id,action:'ASSET_CREATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:row,client:tx.db});
      if(integer(input.responsibleDepartmentId)||integer(input.responsibleSectionId)||integer(input.currentLocationId)||deploymentDate){
        const movement=(await tx.query(`INSERT INTO asset_movements(institute_id,asset_id,to_department_id,to_location_id,movement_type,requested_by,received_by,requested_at,received_at,reason,status) VALUES($1,$2,$3,$4,'INITIAL_DEPLOYMENT',$5,$5,COALESCE($6::date,now()::date),COALESCE($6::date,now()::date),'Initial asset deployment','RECEIVED') RETURNING *`,[ctx.instituteId,row.id,integer(input.responsibleDepartmentId),integer(input.currentLocationId),ctx.userId,deploymentDate])).rows[0];
        await this.audit({entityType:'ASSET_MOVEMENT',entityId:movement.id,action:'ASSET_INITIAL_DEPLOYMENT',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:{...movement,responsible_section_id:integer(input.responsibleSectionId)},client:tx.db});
      }
      return { asset: row, warnings: await this.duplicateSerialWarnings(row, ctx, tx) };
    });
  }
  async validateLinks(input, ctx, tx) {
    const checks = [
      ['asset_categories',integer(input.assetCategoryId),'SELECT id FROM asset_categories WHERE id=$1 AND institute_id=$2'],['asset_locations',integer(input.currentLocationId),'SELECT id FROM asset_locations WHERE id=$1 AND institute_id=$2 AND is_active=true'],['departments',integer(input.responsibleDepartmentId),'SELECT id FROM departments WHERE id=$1 AND institute_id=$2'],['generic_items',integer(input.genericItemId),'SELECT id FROM generic_items WHERE id=$1 AND institute_id=$2'],['approved_products',integer(input.approvedProductId),'SELECT id FROM approved_products WHERE id=$1 AND institute_id=$2'],['stock_items',integer(input.stockItemId),'SELECT id FROM stock_items WHERE id=$1 AND institute_id=$2'],['requests',integer(input.purchaseRequestId),'SELECT id FROM requests WHERE id=$1 AND institute_id=$2'],['requested_items',integer(input.requestedItemId),'SELECT ri.id FROM requested_items ri JOIN requests r ON r.id=ri.request_id WHERE ri.id=$1 AND r.institute_id=$2'],['purchase_orders',integer(input.purchaseOrderId),'SELECT po.id FROM purchase_orders po JOIN requests r ON r.id=po.request_id WHERE po.id=$1 AND r.institute_id=$2'],['purchase_order_items',integer(input.purchaseOrderItemId),'SELECT pi.id FROM purchase_order_items pi JOIN purchase_orders po ON po.id=pi.purchase_order_id JOIN requests r ON r.id=po.request_id WHERE pi.id=$1 AND r.institute_id=$2'],['goods_receipts',integer(input.goodsReceiptId),'SELECT gr.id FROM goods_receipts gr JOIN requests r ON r.id=gr.request_id WHERE gr.id=$1 AND r.institute_id=$2'],['goods_receipt_items',integer(input.goodsReceiptItemId),'SELECT gi.id FROM goods_receipt_items gi JOIN goods_receipts gr ON gr.id=gi.goods_receipt_id JOIN requests r ON r.id=gr.request_id WHERE gi.id=$1 AND r.institute_id=$2'],['suppliers',integer(input.supplierId),'SELECT id FROM suppliers WHERE id=$1 AND institute_id=$2']];
    for (const [table,id,sql] of checks) if (id) { const r=await tx.query(sql,[id,ctx.instituteId]); if(!r.rowCount) throw error(400,`Invalid or foreign ${table} reference`); }
    if(integer(input.responsibleSectionId)) { const section=await tx.query('SELECT s.id FROM sections s JOIN departments d ON d.id=s.department_id WHERE s.id=$1 AND s.department_id=$2 AND d.institute_id=$3',[integer(input.responsibleSectionId),integer(input.responsibleDepartmentId),ctx.instituteId]);if(!section.rowCount)throw error(400,'Section must belong to the selected department and institute'); }
    for (const [child,parent,sql] of [['requestedItemId','purchaseRequestId','SELECT 1 FROM requested_items WHERE id=$1 AND request_id=$2'],['purchaseOrderItemId','purchaseOrderId','SELECT 1 FROM purchase_order_items WHERE id=$1 AND purchase_order_id=$2'],['goodsReceiptItemId','goodsReceiptId','SELECT 1 FROM goods_receipt_items WHERE id=$1 AND goods_receipt_id=$2']]) if (integer(input[child]) && integer(input[parent]) && !(await tx.query(sql,[integer(input[child]),integer(input[parent])])).rowCount) throw error(400,`Inconsistent ${child}/${parent} provenance`);
    const relationships = [
      ['purchaseOrderId','purchaseRequestId','SELECT 1 FROM purchase_orders WHERE id=$1 AND request_id=$2'],
      ['goodsReceiptId','purchaseRequestId','SELECT 1 FROM goods_receipts WHERE id=$1 AND request_id=$2'],
      ['goodsReceiptId','purchaseOrderId','SELECT 1 FROM goods_receipts WHERE id=$1 AND purchase_order_id=$2'],
      ['purchaseOrderItemId','requestedItemId','SELECT 1 FROM purchase_order_items WHERE id=$1 AND requested_item_id=$2'],
      ['goodsReceiptItemId','requestedItemId','SELECT 1 FROM goods_receipt_items WHERE id=$1 AND requested_item_id=$2'],
      ['goodsReceiptItemId','purchaseOrderItemId','SELECT 1 FROM goods_receipt_items WHERE id=$1 AND purchase_order_item_id=$2'],
      ['purchaseOrderId','supplierId','SELECT 1 FROM purchase_orders WHERE id=$1 AND supplier_id=$2'],
    ];
    for (const [child,parent,sql] of relationships) if (integer(input[child]) && integer(input[parent]) && !(await tx.query(sql,[integer(input[child]),integer(input[parent])])).rowCount) throw error(400,`Inconsistent ${child}/${parent} provenance`);
  }
  async duplicateSerialWarnings(asset, ctx, tx=this.repo) { if (!asset.serial_number) return []; const r=await tx.query(`SELECT id,asset_number FROM assets WHERE institute_id=$1 AND id<>$2 AND lower(coalesce(manufacturer,''))=lower($3) AND lower(coalesce(model,''))=lower($4) AND lower(serial_number)=lower($5) LIMIT 10`,[ctx.instituteId,asset.id,asset.manufacturer||'',asset.model||'',asset.serial_number]); return r.rows.length ? [{code:'DUPLICATE_SERIAL_CANDIDATE',matches:r.rows}] : []; }
  async update(id, input, ctx) { return this.repo.transaction(async tx => { const before=await tx.asset(id,ctx.instituteId,true); if(!before) throw error(404,'Asset not found'); if(input.assetNumber && input.assetNumber!==before.asset_number) throw error(409,'Asset number is permanent'); const allowed={description:'description',manufacturer:'manufacturer',model:'model',serialNumber:'serial_number',notes:'notes',condition:'condition',operationalStatus:'operational_status',reconciliationStatus:'reconciliation_status',responsibleDepartmentId:'responsible_department_id',currentLocationId:'current_location_id',isActive:'is_active'}; const entries=Object.entries(input).filter(([k])=>allowed[k]); if(!entries.length) throw error(400,'No editable fields supplied'); ['condition','operationalStatus','reconciliationStatus'].forEach(k=>input[k]!==undefined&&assertOption(k,input[k])); await this.validateLinks({responsibleDepartmentId:input.responsibleDepartmentId,currentLocationId:input.currentLocationId},ctx,tx); const params=entries.map(([,v])=>v), sets=entries.map(([k],i)=>`${allowed[k]}=$${i+1}`); params.push(ctx.userId,id,ctx.instituteId,input.rowVersion); const r=await tx.query(`UPDATE assets SET ${sets.join(',')},updated_by=$${params.length-3},updated_at=now(),row_version=row_version+1 WHERE id=$${params.length-2} AND institute_id=$${params.length-1} AND row_version=$${params.length} RETURNING *`,params); if(!r.rowCount) throw error(409,'Asset was changed by another user','ASSET_VERSION_CONFLICT'); await this.audit({entityType:'ASSET',entityId:id,action:'ASSET_UPDATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,beforeData:before,afterData:r.rows[0],client:tx.db}); return {asset:r.rows[0],warnings:await this.duplicateSerialWarnings(r.rows[0],ctx,tx)}; }); }
  async categories(ctx) {
    await this.repo.query(`INSERT INTO asset_categories(institute_id,code,name,description,is_active,created_by,updated_by)
      SELECT $1,category.code,category.name,category.description,true,$2,$2
      FROM jsonb_to_recordset($3::jsonb) AS category(code text,name text,description text)
      ON CONFLICT (institute_id,code) DO NOTHING`, [ctx.instituteId, ctx.userId, JSON.stringify(baselineAssetCategories)]);
    return (await this.repo.query('SELECT * FROM asset_categories WHERE institute_id=$1 ORDER BY name',[ctx.instituteId])).rows;
  }
  async currencies(ctx){const result=await this.repo.query(`SELECT DISTINCT upper(currency) code FROM (SELECT currency FROM requested_items ri JOIN requests r ON r.id=ri.request_id WHERE r.institute_id=$1 UNION ALL SELECT currency FROM purchase_orders po JOIN requests r ON r.id=po.request_id WHERE r.institute_id=$1 UNION ALL SELECT unnest(ARRAY['IQD','USD'])) c WHERE currency ~ '^[A-Za-z]{3}$' ORDER BY code`,[ctx.instituteId]);return result.rows.map(x=>x.code);}
  async sections(ctx,departmentId){if(!integer(departmentId))return[];return(await this.repo.query('SELECT s.id,s.name FROM sections s JOIN departments d ON d.id=s.department_id WHERE s.department_id=$1 AND d.institute_id=$2 ORDER BY s.name',[integer(departmentId),ctx.instituteId])).rows;}
  async locations(ctx, query={}) { const params=[ctx.instituteId], where=['l.institute_id=$1'];
    if(query.type){params.push(query.type);where.push(`l.location_type=$${params.length}`);} if(query.active!==undefined&&query.active!==''){params.push(String(query.active)==='true');where.push(`l.is_active=$${params.length}`);} if(query.search){params.push(`%${query.search}%`);where.push(`(l.code ILIKE $${params.length} OR l.name ILIKE $${params.length})`);}
    return (await this.repo.query(`WITH RECURSIVE paths AS (SELECT id,parent_location_id,name,name::text display_path FROM asset_locations WHERE institute_id=$1 AND parent_location_id IS NULL UNION ALL SELECT c.id,c.parent_location_id,c.name,(p.display_path||' › '||c.name)::text FROM asset_locations c JOIN paths p ON p.id=c.parent_location_id WHERE c.institute_id=$1) SELECT l.*,p.display_path,d.name department_name,s.name section_name,(SELECT count(*)::int FROM assets a WHERE a.current_location_id=l.id AND a.institute_id=l.institute_id AND a.is_active) asset_count FROM asset_locations l LEFT JOIN paths p ON p.id=l.id LEFT JOIN departments d ON d.id=l.department_id LEFT JOIN sections s ON s.id=l.section_id WHERE ${where.join(' AND ')} ORDER BY coalesce(p.display_path,l.name),l.id`,params)).rows; }
  async saveLocation(id,input,ctx) { assertOption('locationType',input.locationType); return this.repo.transaction(async tx=>{ if(id){const existing=await tx.location(id,ctx.instituteId);if(!existing)throw error(404,'Location not found');input={...input,parentLocationId:existing.parent_location_id,isActive:existing.is_active};} if(id&&Number(id)===integer(input.parentLocationId)) throw error(400,'Location cannot parent itself'); if(input.parentLocationId){const p=await tx.location(integer(input.parentLocationId),ctx.instituteId);if(!p||!p.is_active)throw error(400,'Parent must be active and in this institute');if(id){const cycle=await tx.query('WITH RECURSIVE d AS (SELECT id,parent_location_id FROM asset_locations WHERE id=$1 UNION ALL SELECT l.id,l.parent_location_id FROM asset_locations l JOIN d ON l.parent_location_id=d.id) SELECT 1 FROM d WHERE id=$2',[id,input.parentLocationId]);if(cycle.rowCount)throw error(400,'Location hierarchy cycle');}} let department=null;if(input.departmentId){department=(await tx.query('SELECT id FROM departments WHERE id=$1 AND institute_id=$2',[integer(input.departmentId),ctx.instituteId])).rows[0];if(!department)throw error(400,'Invalid or foreign department');}if(input.sectionId){const section=(await tx.query('SELECT s.id,s.department_id FROM sections s JOIN departments d ON d.id=s.department_id WHERE s.id=$1 AND d.institute_id=$2',[integer(input.sectionId),ctx.instituteId])).rows[0];if(!section)throw error(400,'Invalid or foreign section');if(department&&section.department_id!==integer(input.departmentId))throw error(400,'Section does not belong to the selected department');} const r=id?await tx.query('UPDATE asset_locations SET code=$1,name=$2,location_type=$3,parent_location_id=$4,department_id=$5,section_id=$6,is_active=$7,updated_by=$8,updated_at=now() WHERE id=$9 AND institute_id=$10 RETURNING *',[input.code,input.name,input.locationType,integer(input.parentLocationId),integer(input.departmentId),integer(input.sectionId),input.isActive!==false,ctx.userId,id,ctx.instituteId]):await tx.query('INSERT INTO asset_locations(institute_id,code,name,location_type,parent_location_id,department_id,section_id,is_active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING *',[ctx.instituteId,input.code,input.name,input.locationType,integer(input.parentLocationId),integer(input.departmentId),integer(input.sectionId),input.isActive!==false,ctx.userId]);if(!r.rowCount)throw error(404,'Location not found');await this.audit({entityType:'ASSET_LOCATION',entityId:r.rows[0].id,action:id?'ASSET_LOCATION_UPDATED':'ASSET_LOCATION_CREATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:r.rows[0],client:tx.db});return r.rows[0];}); }
  async reparentLocation(id,parentLocationId,ctx){return this.repo.transaction(async tx=>{const before=await tx.location(id,ctx.instituteId);if(!before)throw error(404,'Location not found');if(Number(id)===integer(parentLocationId))throw error(400,'Location cannot parent itself','LOCATION_SELF_PARENT');if(parentLocationId){const parent=await tx.location(integer(parentLocationId),ctx.instituteId);if(!parent||!parent.is_active)throw error(400,'Parent must be active and in this institute','LOCATION_PARENT_INVALID');const cycle=await tx.query('WITH RECURSIVE descendants AS (SELECT id FROM asset_locations WHERE id=$1 AND institute_id=$2 UNION ALL SELECT l.id FROM asset_locations l JOIN descendants d ON l.parent_location_id=d.id WHERE l.institute_id=$2) SELECT 1 FROM descendants WHERE id=$3',[id,ctx.instituteId,parentLocationId]);if(cycle.rowCount)throw error(409,'Location hierarchy cycle','LOCATION_CYCLE');}const row=(await tx.query('UPDATE asset_locations SET parent_location_id=$1,updated_by=$2,updated_at=now() WHERE id=$3 AND institute_id=$4 RETURNING *',[integer(parentLocationId),ctx.userId,id,ctx.instituteId])).rows[0];await this.audit({entityType:'ASSET_LOCATION',entityId:id,action:'ASSET_LOCATION_REPARENTED',actorUserId:ctx.userId,instituteId:ctx.instituteId,beforeData:before,afterData:row,client:tx.db});return row;});}
  async setLocationActive(id,isActive,ctx){if(typeof isActive!=='boolean')throw error(400,'isActive must be boolean');return this.repo.transaction(async tx=>{const before=await tx.location(id,ctx.instituteId);if(!before)throw error(404,'Location not found');if(!isActive){const deps=await tx.query(`SELECT EXISTS(SELECT 1 FROM asset_locations WHERE parent_location_id=$1 AND institute_id=$2 AND is_active) active_children,EXISTS(SELECT 1 FROM assets WHERE current_location_id=$1 AND institute_id=$2 AND is_active) active_assets`,[id,ctx.instituteId]);if(deps.rows[0].active_children)throw error(409,'Deactivate active child locations first','LOCATION_HAS_ACTIVE_CHILDREN');if(deps.rows[0].active_assets)throw error(409,'Location has active assigned assets','LOCATION_HAS_ACTIVE_ASSETS');}const row=(await tx.query('UPDATE asset_locations SET is_active=$1,updated_by=$2,updated_at=now() WHERE id=$3 AND institute_id=$4 RETURNING *',[isActive,ctx.userId,id,ctx.instituteId])).rows[0];await this.audit({entityType:'ASSET_LOCATION',entityId:id,action:isActive?'ASSET_LOCATION_REACTIVATED':'ASSET_LOCATION_DEACTIVATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,beforeData:before,afterData:row,client:tx.db});return row;});}
  async listMovements(query,ctx){const params=[ctx.instituteId],where=['m.institute_id=$1'];for(const [key,col] of Object.entries({status:'status',movementType:'movement_type',asset:'asset_id',department:'to_department_id',location:'to_location_id'}))if(query[key]){params.push(query[key]);where.push(`m.${col}=$${params.length}`);}if(query.from){params.push(query.from);where.push(`m.requested_at>=$${params.length}`);}if(query.to){params.push(query.to);where.push(`m.requested_at<$${params.length}::date+1`);}if(query.search){params.push(`%${query.search}%`);where.push(`(a.asset_number ILIKE $${params.length} OR a.description ILIKE $${params.length} OR m.id::text ILIKE $${params.length})`);}return(await this.repo.query(`SELECT m.*,a.asset_number,a.description asset_description,fl.name from_location_name,tl.name to_location_name,fd.name from_department_name,td.name to_department_name,u.name requester_name FROM asset_movements m JOIN assets a ON a.id=m.asset_id LEFT JOIN asset_locations fl ON fl.id=m.from_location_id LEFT JOIN asset_locations tl ON tl.id=m.to_location_id LEFT JOIN departments fd ON fd.id=m.from_department_id LEFT JOIN departments td ON td.id=m.to_department_id LEFT JOIN users u ON u.id=m.requested_by WHERE ${where.join(' AND ')} ORDER BY m.requested_at DESC`,params)).rows;}
  async movements(assetId,ctx){await this.get(assetId,ctx);return(await this.repo.query('SELECT * FROM asset_movements WHERE asset_id=$1 AND institute_id=$2 ORDER BY requested_at DESC',[assetId,ctx.instituteId])).rows;}
  async assertNoActiveMovement(tx,assetId,instituteId,movementId){const conflict=await tx.query("SELECT id FROM asset_movements WHERE asset_id=$1 AND institute_id=$2 AND status IN ('PENDING_APPROVAL','APPROVED','IN_TRANSIT') AND id<>$3",[assetId,instituteId,movementId]);if(conflict.rowCount)throw error(409,'Asset already has an active movement','ASSET_MOVEMENT_CONFLICT');}
  async validateMovementDestination(tx,movementType,input,ctx){if(movementType==='RETURN')throw error(400,'Returns must be initiated from the originating movement','RETURN_ORIGIN_REQUIRED');if(!input.toLocationId)throw error(400,'Destination location is required');const destination=await tx.location(integer(input.toLocationId),ctx.instituteId);if(!destination||!destination.is_active)throw error(400,'Invalid, inactive, or foreign destination location');if(movementType==='EXTERNAL_MAINTENANCE'&&destination.location_type!=='EXTERNAL')throw error(400,'External maintenance requires an active EXTERNAL destination','EXTERNAL_LOCATION_REQUIRED');if(movementType==='MAINTENANCE_TRANSFER'&&destination.location_type!=='WORKSHOP')throw error(400,'Maintenance transfer requires an active WORKSHOP destination','WORKSHOP_LOCATION_REQUIRED');if(input.toDepartmentId&&movementType!=='PERMANENT_TRANSFER')throw error(400,'Destination department is only allowed for permanent transfers','DESTINATION_DEPARTMENT_NOT_ALLOWED');if(input.toDepartmentId&&!(await tx.query('SELECT id FROM departments WHERE id=$1 AND institute_id=$2',[integer(input.toDepartmentId),ctx.instituteId])).rowCount)throw error(400,'Invalid or foreign destination department');return destination;}
  async requestMovement(assetId,input,ctx){assertOption('movementType',input.movementType);return this.repo.transaction(async tx=>{const asset=await tx.asset(assetId,ctx.instituteId,true);if(!asset)throw error(404,'Asset not found');if(asset.operational_status==='DISPOSED')throw error(409,'Disposed assets cannot be moved');if(['TEMPORARY_LOAN','EXTERNAL_MAINTENANCE'].includes(input.movementType)&&!input.expectedReturnAt)throw error(400,'Expected return is required for this movement type');if(!String(input.reason||'').trim())throw error(400,'Movement reason is required');await this.validateMovementDestination(tx,input.movementType,input,ctx);await this.assertNoActiveMovement(tx,asset.id,ctx.instituteId,0);const r=await tx.query(`INSERT INTO asset_movements(institute_id,asset_id,from_department_id,from_location_id,to_department_id,to_location_id,movement_type,requested_by,expected_return_at,reason,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'DRAFT') RETURNING *`,[ctx.instituteId,asset.id,asset.responsible_department_id,asset.current_location_id,integer(input.toDepartmentId),integer(input.toLocationId),input.movementType,ctx.userId,input.expectedReturnAt||null,input.reason.trim()]);await this.audit({entityType:'ASSET_MOVEMENT',entityId:r.rows[0].id,action:'ASSET_MOVEMENT_CREATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:r.rows[0],client:tx.db});return r.rows[0];});}
  async initiateReturn(originId,input,ctx){return this.repo.transaction(async tx=>{const origin=(await tx.query('SELECT * FROM asset_movements WHERE id=$1 AND institute_id=$2 FOR UPDATE',[originId,ctx.instituteId])).rows[0];if(!origin)throw error(404,'Originating movement not found');if(origin.status!=='RECEIVED'||!['TEMPORARY_LOAN','MAINTENANCE_TRANSFER','EXTERNAL_MAINTENANCE'].includes(origin.movement_type))throw error(409,'Movement is not eligible for return','MOVEMENT_NOT_RETURNABLE');if(!origin.from_location_id)throw error(409,'Originating movement has no governed source location','RETURN_DESTINATION_UNAVAILABLE');const asset=await tx.asset(origin.asset_id,ctx.instituteId,true);if(!asset||asset.current_location_id!==origin.to_location_id)throw error(409,'Asset location changed since the originating receipt','MOVEMENT_STALE_SOURCE');const destination=await tx.location(origin.from_location_id,ctx.instituteId);if(!destination||!destination.is_active)throw error(409,'Original location is not an active governed destination','RETURN_DESTINATION_UNAVAILABLE');await this.assertNoActiveMovement(tx,asset.id,ctx.instituteId,0);const reason=String(input?.reason||`Return of movement MV-${origin.id}`).trim();const row=(await tx.query(`INSERT INTO asset_movements(institute_id,asset_id,from_department_id,from_location_id,to_location_id,movement_type,requested_by,reason,status,origin_movement_id) VALUES($1,$2,$3,$4,$5,'RETURN',$6,$7,'DRAFT',$8) RETURNING *`,[ctx.instituteId,asset.id,asset.responsible_department_id,asset.current_location_id,origin.from_location_id,ctx.userId,reason,origin.id])).rows[0];await this.audit({entityType:'ASSET_MOVEMENT',entityId:row.id,action:'ASSET_RETURN_INITIATED',actorUserId:ctx.userId,instituteId:ctx.instituteId,afterData:row,client:tx.db});return row;});}
  async transitionMovement(id,toStatus,ctx){assertOption('movementStatus',toStatus);return this.repo.transaction(async tx=>{const q=await tx.query('SELECT * FROM asset_movements WHERE id=$1 AND institute_id=$2 FOR UPDATE',[id,ctx.instituteId]);const before=q.rows[0];if(!before)throw error(404,'Movement not found');if(before.status===toStatus)throw error(409,`Movement is already ${toStatus}`,'DUPLICATE_MOVEMENT_TRANSITION');if(!transitions[before.status]?.includes(toStatus))throw error(409,`Cannot transition ${before.status} to ${toStatus}`,'INVALID_MOVEMENT_TRANSITION');const asset=await tx.asset(before.asset_id,ctx.instituteId,true);if(!asset)throw error(409,'Movement asset is unavailable');if(['PENDING_APPROVAL','APPROVED','IN_TRANSIT'].includes(toStatus))await this.assertNoActiveMovement(tx,asset.id,ctx.instituteId,id);if(toStatus==='RECEIVED'&&asset.current_location_id!==before.from_location_id)throw error(409,'Asset location changed since movement request','MOVEMENT_STALE_SOURCE');const fields={APPROVED:['approved_by','approved_at'],IN_TRANSIT:['dispatched_by','dispatched_at'],RECEIVED:['received_by','received_at']}[toStatus];let sql='UPDATE asset_movements SET status=$1,updated_at=now()',params=[toStatus];if(fields){sql+=`,${fields[0]}=$2,${fields[1]}=now()`;params.push(ctx.userId);}params.push(id,ctx.instituteId);sql+=` WHERE id=$${params.length-1} AND institute_id=$${params.length} RETURNING *`;const row=(await tx.query(sql,params)).rows[0];let assetAfter=asset;if(toStatus==='RECEIVED'){const transferResponsibility=row.movement_type==='PERMANENT_TRANSFER';assetAfter=(await tx.query('UPDATE assets SET current_location_id=$1,responsible_department_id=CASE WHEN $2 THEN COALESCE($3,responsible_department_id) ELSE responsible_department_id END,row_version=row_version+1,updated_at=now(),updated_by=$4 WHERE id=$5 AND institute_id=$6 RETURNING *',[row.to_location_id,transferResponsibility,row.to_department_id,ctx.userId,row.asset_id,ctx.instituteId])).rows[0];}await this.audit({entityType:'ASSET_MOVEMENT',entityId:id,action:`ASSET_MOVEMENT_${toStatus}`,actorUserId:ctx.userId,instituteId:ctx.instituteId,beforeData:before,afterData:toStatus==='RECEIVED'?{...row,asset_before:{current_location_id:asset.current_location_id,responsible_department_id:asset.responsible_department_id},asset_after:{current_location_id:assetAfter.current_location_id,responsible_department_id:assetAfter.responsible_department_id}}:row,client:tx.db});return row;});}
}
module.exports={FixedAssetService,context};