const defaultRepository=require('../repositories/organizationRepository');
const TYPES=['INSTITUTE','EXECUTIVE_OFFICE','DIRECTORATE','DEPARTMENT','SECTION','UNIT'];
const POSITION_TYPES=['UNIT_HEAD','EXECUTIVE_HEAD','DEPARTMENT_HEAD','SECTION_HEAD','CUSTOM'];
const httpError=(status,message)=>Object.assign(new Error(message),{statusCode:status});
function createOrganizationService(repo=defaultRepository,audit=require('./auditService').writeAuditEvent){
 const assertParent=async(id,parent,client)=>{if(parent==null)return;if(String(id)===String(parent))throw httpError(400,'A unit cannot be its own parent');const p=await repo.get(parent,client);if(!p)throw httpError(400,'Parent unit not found');if(id){const ds=await repo.descendants(id,client);if(ds.some(x=>String(x.id)===String(parent)))throw httpError(400,'Move would create a circular hierarchy');}};
 const getAncestors=(id,c)=>repo.ancestors(id,c); const getPath=async(id,c)=>[...(await repo.ancestors(id,c)),await repo.get(id,c)].filter(Boolean);
 const holder=async(id,type,c)=>(await repo.positions(id,c)).find(p=>p.is_active&&p.position_type===type)||null;
 const executive=async(id,c)=>{const chain=[await repo.get(id,c),...(await repo.ancestors(id,c)).slice().reverse()];for(const u of chain){if(u?.unit_type==='EXECUTIVE_OFFICE'){const p=await holder(u.id,'EXECUTIVE_HEAD',c)|| (await repo.positions(u.id,c)).find(x=>x.is_active&&x.is_unit_head);return p?{unitId:u.id,unitName:u.name,position:p.position_name,userId:p.user_id,userName:p.user_name}:null;}}return null;};
 const detail=async(id,c)=>{const unit=await repo.get(id,c);if(!unit)throw httpError(404,'Organization unit not found');const [children,ps,path,owner]=await Promise.all([repo.list({parent:id},c),repo.positions(id,c),getPath(id,c),executive(id,c)]);return {...unit,children,positions:ps,path:path.map(x=>x.name),ancestors:path.slice(0,-1),executiveOwner:owner,unitHead:ps.find(x=>x.is_active&&x.is_unit_head)||null};};
 const tree=async filters=>{const rows=await repo.list(filters);const map=new Map(rows.map(x=>[String(x.id),{...x,children:[]}])) ,roots=[];for(const n of map.values()){const p=map.get(String(n.parent_unit_id));p?p.children.push(n):roots.push(n);}return roots;};
 const tx=async fn=>{const c=await repo.pool.connect();try{await c.query('BEGIN');const v=await fn(c);await c.query('COMMIT');return v;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}};
 const create=payload=>tx(async c=>{if(!payload.name||!TYPES.includes(payload.unitType))throw httpError(400,'name and valid unitType are required');await assertParent(null,payload.parentUnitId,c);const r=await c.query(`INSERT INTO organization_units(institute_id,name,code,unit_type,parent_unit_id,department_id,section_id,classification,is_active,sort_order,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,COALESCE($9,true),COALESCE($10,0),$11,$11) RETURNING *`,[payload.instituteId||null,payload.name,payload.code||null,payload.unitType,payload.parentUnitId||null,payload.departmentId||null,payload.sectionId||null,payload.classification||null,payload.isActive,payload.sortOrder,payload.actorId]);await audit({client:c,entityType:'organization_unit',entityId:r.rows[0].id,action:'ORGANIZATION_UNIT_CREATED',actorUserId:payload.actorId,afterData:r.rows[0]});return r.rows[0];});
 const update=(id,payload)=>tx(async c=>{const before=await repo.get(id,c);if(!before)throw httpError(404,'Organization unit not found');if(payload.parentUnitId!==undefined)await assertParent(id,payload.parentUnitId,c);const r=await c.query(`UPDATE organization_units SET name=COALESCE($2,name),code=COALESCE($3,code),unit_type=COALESCE($4,unit_type),parent_unit_id=CASE WHEN $5 THEN $6 ELSE parent_unit_id END,classification=CASE WHEN $7 THEN $8 ELSE classification END,is_active=COALESCE($9,is_active),sort_order=COALESCE($10,sort_order),updated_by=$11,updated_at=now() WHERE id=$1 RETURNING *`,[id,payload.name,payload.code,payload.unitType,payload.parentUnitId!==undefined,payload.parentUnitId||null,payload.classification!==undefined,payload.classification||null,payload.isActive,payload.sortOrder,payload.actorId]);const action=payload.isActive===false?'ORGANIZATION_UNIT_ARCHIVED':payload.parentUnitId!==undefined&&String(before.parent_unit_id)!==String(payload.parentUnitId)?'ORGANIZATION_UNIT_MOVED':'ORGANIZATION_UNIT_UPDATED';await audit({client:c,entityType:'organization_unit',entityId:id,action,actorUserId:payload.actorId,beforeData:before,afterData:r.rows[0]});return r.rows[0];});
 const archive=(id,actorId)=>update(id,{isActive:false,actorId});
 const savePosition=(unitId,payload,id)=>tx(async c=>{if(!POSITION_TYPES.includes(payload.positionType))throw httpError(400,'Invalid positionType');let r,before=null,action;if(id){before=(await c.query('SELECT * FROM organization_positions WHERE id=$1',[id])).rows[0];if(!before)throw httpError(404,'Position not found');r=await c.query(`UPDATE organization_positions SET position_type=COALESCE($2,position_type),position_name=COALESCE($3,position_name),user_id=CASE WHEN $4 THEN $5 ELSE user_id END,is_unit_head=COALESCE($6,is_unit_head),is_active=COALESCE($7,is_active),effective_from=COALESCE($8,effective_from),effective_to=COALESCE($9,effective_to),updated_by=$10,updated_at=now() WHERE id=$1 RETURNING *`,[id,payload.positionType,payload.positionName,payload.userId!==undefined,payload.userId||null,payload.isUnitHead,payload.isActive,payload.effectiveFrom,payload.effectiveTo,payload.actorId]);action=payload.isActive===false?'ORGANIZATION_POSITION_REMOVED':'ORGANIZATION_POSITION_CHANGED';}else{r=await c.query(`INSERT INTO organization_positions(organization_unit_id,position_type,position_name,user_id,is_unit_head,effective_from,effective_to,created_by,updated_by) VALUES($1,$2,$3,$4,COALESCE($5,false),$6,$7,$8,$8) RETURNING *`,[unitId,payload.positionType,payload.positionName,payload.userId||null,payload.isUnitHead,payload.effectiveFrom,payload.effectiveTo,payload.actorId]);action='ORGANIZATION_POSITION_ASSIGNED';}await audit({client:c,entityType:'organization_position',entityId:r.rows[0].id,action,actorUserId:payload.actorId,beforeData:before,afterData:r.rows[0]});return r.rows[0];});
 return {tree,detail,create,update,archive,savePosition,getAncestorUnits:getAncestors,getOrganizationalPath:getPath,resolvePositionHolder:holder,resolveExecutiveOwner:async departmentId=>{const rows=await repo.list({});const u=rows.find(x=>String(x.department_id)===String(departmentId));return u?executive(u.id):null;},resolveDepartmentHead:async departmentId=>{const rows=await repo.list({});const u=rows.find(x=>String(x.department_id)===String(departmentId));return u?holder(u.id,'DEPARTMENT_HEAD'):null;},resolveSectionHead:async sectionId=>{const rows=await repo.list({});const u=rows.find(x=>String(x.section_id)===String(sectionId));return u?holder(u.id,'SECTION_HEAD'):null;},repo};
}
module.exports={createOrganizationService,TYPES,POSITION_TYPES};