const FixedAssetRepository=require('../repositories/fixedAssetRepository');

const roles={SIDE_A:'A',APPROACH:'A',SIDE_B:'B',DEPARTURE:'B'};
function deriveDirection(observations,portal){
 const ordered=[...observations].sort((a,b)=>new Date(a.read_timestamp)-new Date(b.read_timestamp));
 const sequence=ordered.map(x=>roles[x.direction_role]||'?').filter((x,i,a)=>i===0||x!==a[i-1]);
 const first=sequence.find(x=>x!=='?'),last=[...sequence].reverse().find(x=>x!=='?');
 let direction='UNKNOWN',confidence=0.2;if(first&&last&&first!==last&&portal?.from_location_id&&portal?.to_location_id){direction=first==='A'?'ENTERING':'EXITING';confidence=sequence.length>=3?.9:.8;}
 return{direction,confidence,evidence:{antennaSequence:sequence,timeSpanMs:ordered.length?new Date(ordered.at(-1).read_timestamp)-new Date(ordered[0].read_timestamp):0,contributors:direction==='UNKNOWN'?['insufficient ordered side evidence']:['ordered portal-side transition','portal orientation configured']}};
}
class RfidEventProcessor{
 constructor(repo=new FixedAssetRepository(),windowSeconds=10,maxAttempts=5){this.repo=repo;this.windowSeconds=windowSeconds;this.maxAttempts=maxAttempts;}
 async process(limit=100){const claimed=await this.repo.transaction(async tx=>(await tx.query("UPDATE rfid_read_events SET processing_status='PROCESSING',processing_attempts=processing_attempts+1 WHERE id IN (SELECT id FROM rfid_read_events WHERE processing_status IN ('PENDING','FAILED') AND processing_attempts<$2 ORDER BY read_timestamp,id FOR UPDATE SKIP LOCKED LIMIT $1) RETURNING id",[limit,this.maxAttempts])).rows.map(x=>x.id));let processed=0,failed=0;for(const id of claimed){try{await this.repo.transaction(tx=>this.processOne(tx,id));processed++;}catch(e){failed++;await this.repo.query("UPDATE rfid_read_events SET processing_status='FAILED',processing_error=left($1,1000) WHERE id=$2",[e.message,id]);}}return{selected:claimed.length,processed,failed};}
 async processOne(tx,id){const read=(await tx.query('SELECT r.*,pa.direction_role,p.from_location_id portal_from_location_id,p.to_location_id portal_to_location_id FROM rfid_read_events r LEFT JOIN rfid_portal_antennas pa ON pa.portal_id=r.portal_id AND pa.antenna_id=r.antenna_id LEFT JOIN rfid_portals p ON p.id=r.portal_id WHERE r.id=$1 FOR UPDATE',[id])).rows[0];if(!read)return;
  // Serialize one EPC/portal aggregation key without globally blocking other tags.
  await tx.query("SELECT pg_advisory_xact_lock(hashtextextended($1, 17))",[`${read.institute_id}:${read.epc}:${read.portal_id||'NO_PORTAL'}`]);
  const nearby=(await tx.query(`SELECT r.read_timestamp,pa.direction_role FROM rfid_read_events r LEFT JOIN rfid_portal_antennas pa ON pa.portal_id=r.portal_id AND pa.antenna_id=r.antenna_id WHERE r.institute_id=$1 AND r.epc=$2 AND r.portal_id IS NOT DISTINCT FROM $3 AND r.read_timestamp BETWEEN $4::timestamptz-make_interval(secs=>$5) AND $4::timestamptz+make_interval(secs=>$5) ORDER BY r.read_timestamp,r.id`,[read.institute_id,read.epc,read.portal_id,read.read_timestamp,this.windowSeconds])).rows;
  const portal=read.portal_id?{from_location_id:read.portal_from_location_id,to_location_id:read.portal_to_location_id}:null,{direction,confidence,evidence}=deriveDirection(nearby,portal);let eventType=read.asset_id?'ASSET_SEEN':'UNKNOWN_TAG',auth='NOT_APPLICABLE',movement=null,derivedFrom=null,derivedTo=null;
  if(read.asset_id&&read.portal_id&&direction!=='UNKNOWN'){derivedFrom=direction==='ENTERING'?portal.from_location_id:portal.to_location_id;derivedTo=direction==='ENTERING'?portal.to_location_id:portal.from_location_id;const matches=(await tx.query("SELECT id FROM asset_movements WHERE institute_id=$1 AND asset_id=$2 AND status IN ('APPROVED','IN_TRANSIT') AND from_location_id IS NOT DISTINCT FROM $3 AND to_location_id IS NOT DISTINCT FROM $4 AND requested_at BETWEEN $5::timestamptz-interval '24 hours' AND $5::timestamptz+interval '24 hours'",[read.institute_id,read.asset_id,derivedFrom,derivedTo,read.read_timestamp])).rows;if(matches.length===1){auth='AUTHORIZED';eventType='AUTHORIZED_MOVEMENT';movement=matches[0].id;}else if(matches.length===0){auth='UNAUTHORIZED';eventType='UNAUTHORIZED_MOVEMENT';}else{auth='UNKNOWN';evidence.authorization='multiple matching movements';}}
  const existing=(await tx.query(`SELECT * FROM rfid_business_events WHERE institute_id=$1 AND epc=$2 AND portal_id IS NOT DISTINCT FROM $3 AND last_seen_at BETWEEN $4::timestamptz-make_interval(secs=>$5) AND $4::timestamptz+make_interval(secs=>$5) ORDER BY last_seen_at DESC LIMIT 2 FOR UPDATE`,[read.institute_id,read.epc,read.portal_id,read.read_timestamp,this.windowSeconds])).rows;if(existing.length>1)throw new Error('Ambiguous RFID aggregation state');let business=existing[0];if(business)business=(await tx.query('UPDATE rfid_business_events SET first_seen_at=LEAST(first_seen_at,$1),last_seen_at=GREATEST(last_seen_at,$1),observation_count=observation_count+1,event_type=$2,direction=$3,confidence_score=$4,authorization_status=$5,related_asset_movement_id=$6,from_location_id=$7,to_location_id=$8,metadata=$9 WHERE id=$10 RETURNING *',[read.read_timestamp,eventType,direction,confidence,auth,movement,derivedFrom,derivedTo,{evidence},business.id])).rows[0];else business=(await tx.query(`INSERT INTO rfid_business_events(institute_id,event_type,asset_id,asset_tag_id,epc,portal_id,reader_id,from_location_id,to_location_id,direction,first_seen_at,last_seen_at,observation_count,confidence_score,authorization_status,related_asset_movement_id,status,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11,1,$12,$13,$14,'OPEN',$15) RETURNING *`,[read.institute_id,eventType,read.asset_id,read.asset_tag_id,read.epc,read.portal_id,read.reader_id,derivedFrom,derivedTo,direction,read.read_timestamp,confidence,auth,movement,{evidence}])).rows[0];if(['UNKNOWN_TAG','UNAUTHORIZED_MOVEMENT'].includes(eventType))await tx.query(`INSERT INTO asset_exceptions(institute_id,asset_id,asset_tag_id,rfid_business_event_id,exception_type,severity,status,detected_at) VALUES($1,$2,$3,$4,$5,$6,'OPEN',$7) ON CONFLICT(rfid_business_event_id,exception_type) DO NOTHING`,[read.institute_id,read.asset_id,read.asset_tag_id,business.id,eventType,eventType==='UNAUTHORIZED_MOVEMENT'?'HIGH':'MEDIUM',read.read_timestamp]);await tx.query("UPDATE rfid_read_events SET processing_status='PROCESSED',business_event_id=$1,processed_at=now(),processing_error=NULL WHERE id=$2",[business.id,id]);}
}
module.exports=RfidEventProcessor;module.exports.deriveDirection=deriveDirection;