const crypto = require('crypto');
const FixedAssetRepository = require('../repositories/fixedAssetRepository');
const { normalizeEpc, values } = require('../domain/rfidConstants');
const { writeAuditEvent } = require('./auditService');
const error=(statusCode,message,code)=>Object.assign(new Error(message),{statusCode,code});
const ctx=user=>({instituteId:user.institute_id,userId:user.id});
class RfidService {
 constructor(repo=new FixedAssetRepository(),audit=writeAuditEvent){this.repo=repo;this.audit=audit;}
 async tags(assetId,c){if(!await this.repo.asset(assetId,c.instituteId))throw error(404,'Asset not found');return(await this.repo.query('SELECT * FROM asset_tags WHERE asset_id=$1 AND institute_id=$2 ORDER BY created_at DESC',[assetId,c.instituteId])).rows;}
 async lookup(epc,c){const normalized=normalizeEpc(epc);const r=await this.repo.query("SELECT a.*,t.id asset_tag_id,t.tag_status FROM asset_tags t JOIN assets a ON a.id=t.asset_id AND a.institute_id=t.institute_id WHERE t.institute_id=$1 AND t.epc=$2 AND t.tag_status='ACTIVE'",[c.instituteId,normalized]);if(!r.rowCount)throw error(404,'Active tag not found');return r.rows[0];}
 async assign(assetId,input,c){const epc=input.epc?normalizeEpc(input.epc):null;if(!values.tagType.includes(input.tagType))throw error(400,'Invalid tag type');return this.repo.transaction(async tx=>{const asset=await tx.asset(assetId,c.instituteId,true);if(!asset)throw error(404,'Asset not found');const r=await tx.query(`INSERT INTO asset_tags(institute_id,asset_id,tag_type,epc,tid,qr_value,tag_status,is_primary,installed_at,installed_by,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $7='ACTIVE' THEN now() END,$9,$10) RETURNING *`,[c.instituteId,assetId,input.tagType,epc,input.tid||null,input.qrValue||null,input.tagStatus||'ACTIVE',input.isPrimary!==false,c.userId,input.notes||null]);await this.audit({entityType:'ASSET_TAG',entityId:r.rows[0].id,action:'RFID_TAG_ASSIGNED',actorUserId:c.userId,instituteId:c.instituteId,afterData:r.rows[0],client:tx.db});return r.rows[0];});}
 async status(tagId,status,c,reason){if(!['DAMAGED','LOST','RETIRED'].includes(status))throw error(400,'Invalid tag lifecycle action');return this.repo.transaction(async tx=>{const before=(await tx.query('SELECT * FROM asset_tags WHERE id=$1 AND institute_id=$2 FOR UPDATE',[tagId,c.instituteId])).rows[0];if(!before)throw error(404,'Tag not found');const row=(await tx.query("UPDATE asset_tags SET tag_status=$1,is_primary=false,retired_at=CASE WHEN $1='RETIRED' THEN now() ELSE retired_at END,retired_by=CASE WHEN $1='RETIRED' THEN $2 ELSE retired_by END,replacement_reason=COALESCE($3,replacement_reason),updated_at=now() WHERE id=$4 RETURNING *",[status,c.userId,reason||null,tagId])).rows[0];await this.audit({entityType:'ASSET_TAG',entityId:tagId,action:`RFID_TAG_${status}`,actorUserId:c.userId,instituteId:c.instituteId,beforeData:before,afterData:row,client:tx.db});return row;});}
 async replace(tagId,input,c){return this.repo.transaction(async tx=>{const old=(await tx.query('SELECT * FROM asset_tags WHERE id=$1 AND institute_id=$2 FOR UPDATE',[tagId,c.instituteId])).rows[0];if(!old)throw error(404,'Tag not found');await tx.query("UPDATE asset_tags SET tag_status='REPLACED',is_primary=false,retired_at=now(),retired_by=$1,replacement_reason=$2,updated_at=now() WHERE id=$3",[c.userId,input.reason||'Replacement',tagId]);const epc=normalizeEpc(input.epc);const row=(await tx.query("INSERT INTO asset_tags(institute_id,asset_id,tag_type,epc,tid,tag_status,is_primary,installed_at,installed_by,notes) VALUES($1,$2,$3,$4,$5,'ACTIVE',true,now(),$6,$7) RETURNING *",[c.instituteId,old.asset_id,input.tagType||old.tag_type,epc,input.tid||null,c.userId,input.notes||null])).rows[0];await this.audit({entityType:'ASSET_TAG',entityId:row.id,action:'RFID_TAG_REPLACED',actorUserId:c.userId,instituteId:c.instituteId,beforeData:old,afterData:row,client:tx.db});return row;});}
 async list(table,query,c){const allowed={events:['rfid_business_events','first_seen_at'],reads:['rfid_read_events','read_timestamp'],readers:['rfid_readers','created_at'],portals:['rfid_portals','created_at'],exceptions:['asset_exceptions','detected_at']};const selected=allowed[table];if(!selected)throw error(400,'Invalid RFID resource');const[name,order]=selected,limit=Math.min(100,Math.max(1,parseInt(query.limit,10)||25)),page=Math.max(1,parseInt(query.page,10)||1);const clauses=['institute_id=$1'],params=[c.instituteId];const filters={eventType:'event_type',epc:'epc',reader:'reader_id',portal:'portal_id',direction:'direction',authorizationStatus:'authorization_status',status:'status',asset:'asset_id'};for(const[k,col]of Object.entries(filters))if(query[k]){params.push(query[k]);clauses.push(`${col}=$${params.length}`);}params.push(limit,(page-1)*limit);const rows=(await this.repo.query(`SELECT * FROM ${name} WHERE ${clauses.join(' AND ')} ORDER BY ${order} DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params)).rows;return{data:rows,pagination:{page,limit}};}
 async dashboard(c){const r=await this.repo.query(`SELECT count(*) FILTER(WHERE is_active)::int total_active,count(*) FILTER(WHERE asset_class='CAPITAL' AND is_active)::int capital,count(*) FILTER(WHERE asset_class='CONTROLLED' AND is_active)::int controlled,count(*) FILTER(WHERE operational_status='UNDER_MAINTENANCE')::int under_maintenance,count(*) FILTER(WHERE operational_status='MISSING')::int missing,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM asset_tags t WHERE t.asset_id=assets.id AND t.tag_status='ACTIVE'))::int tagged FROM assets WHERE institute_id=$1`,[c.instituteId]);const open=(await this.repo.query("SELECT count(*)::int count FROM asset_exceptions WHERE institute_id=$1 AND status<>'RESOLVED'",[c.instituteId])).rows[0].count;return{...r.rows[0],untagged:r.rows[0].total_active-r.rows[0].tagged,exceptions:open};}
 async createInfrastructure(type,input,c){return this.repo.transaction(async tx=>{let r,action;if(type==='readers'){if(!values.readerType.includes(input.readerType))throw error(400,'Invalid reader type');r=await tx.query(`INSERT INTO rfid_readers(institute_id,code,name,reader_type,manufacturer,model,serial_number,device_identifier,firmware_version,ip_address,location_id,status,configuration,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[c.instituteId,input.code,input.name,input.readerType,input.manufacturer||null,input.model||null,input.serialNumber||null,input.deviceIdentifier,input.firmwareVersion||null,input.ipAddress||null,input.locationId||null,input.status||'OFFLINE',input.configuration||{},input.isActive!==false]);action='RFID_READER_CREATED';}else if(type==='portals'){r=await tx.query(`INSERT INTO rfid_portals(institute_id,code,name,location_id,portal_type,from_location_id,to_location_id,enabled,configuration) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[c.instituteId,input.code,input.name,input.locationId||null,input.portalType,input.fromLocationId||null,input.toLocationId||null,input.enabled!==false,input.configuration||{}]);action='RFID_PORTAL_CREATED';}else if(type==='antennas'){const reader=(await tx.query('SELECT id FROM rfid_readers WHERE id=$1 AND institute_id=$2',[input.readerId,c.instituteId])).rows[0];if(!reader)throw error(400,'Invalid or foreign reader');r=await tx.query('INSERT INTO rfid_antennas(institute_id,reader_id,antenna_port,name,location_id,antenna_type,enabled,configuration) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[c.instituteId,input.readerId,input.antennaPort,input.name,input.locationId||null,input.antennaType||null,input.enabled!==false,input.configuration||{}]);action='RFID_ANTENNA_CREATED';}else throw error(400,'Invalid infrastructure resource');await this.audit({entityType:type.toUpperCase(),entityId:r.rows[0].id,action,actorUserId:c.userId,instituteId:c.instituteId,afterData:r.rows[0],client:tx.db});return r.rows[0];});}
 async exceptionAction(id,action,notes,c){if(!['ACKNOWLEDGED','RESOLVED'].includes(action))throw error(400,'Invalid action');if(action==='RESOLVED'&&!String(notes||'').trim())throw error(400,'Resolution notes are required');return this.repo.transaction(async tx=>{const row=(await tx.query(`UPDATE asset_exceptions SET status=$1,${action==='ACKNOWLEDGED'?'acknowledged_by=$2,acknowledged_at=now()':'resolved_by=$2,resolved_at=now(),resolution_notes=$3'} WHERE id=$${action==='ACKNOWLEDGED'?3:4} AND institute_id=$${action==='ACKNOWLEDGED'?4:5} RETURNING *`,action==='ACKNOWLEDGED'?[action,c.userId,id,c.instituteId]:[action,c.userId,notes,id,c.instituteId])).rows[0];if(!row)throw error(404,'Exception not found');await this.audit({entityType:'ASSET_EXCEPTION',entityId:id,action:`RFID_EXCEPTION_${action}`,actorUserId:c.userId,instituteId:c.instituteId,afterData:row,client:tx.db});return row;});}
}
class RfidIngestionService {
 constructor(repo=new FixedAssetRepository()){this.repo=repo;}
 static hash(secret){return crypto.createHash('sha256').update(secret).digest('hex');}
 async authenticate(header){const match=/^RFID ([A-Za-z0-9._-]+):([^\s]+)$/.exec(header||'');if(!match)throw error(401,'Malformed RFID service credential');const r=await this.repo.query("SELECT id,institute_id,scopes FROM rfid_integration_clients WHERE client_identifier=$1 AND credential_hash=$2 AND enabled=true",[match[1],RfidIngestionService.hash(match[2])]);if(!r.rowCount||!r.rows[0].scopes.includes('rfid:ingest'))throw error(401,'Invalid or disabled RFID service credential');return r.rows[0];}
 async ingest(items,client){if(!Array.isArray(items)||!items.length||items.length>500)throw error(400,'Batch must contain 1-500 observations');return this.repo.transaction(async tx=>{const accepted=[];for(const input of items){const epc=normalizeEpc(input.epc),timestamp=new Date(input.timestamp);if(Number.isNaN(timestamp.getTime()))throw error(400,'Valid timestamp with timezone is required');if(input.rssi!=null&&(input.rssi < -120||input.rssi>0))throw error(400,'RSSI must be between -120 and 0');const reader=(await tx.query('SELECT * FROM rfid_readers WHERE institute_id=$1 AND code=$2 AND is_active=true',[client.institute_id,input.readerCode])).rows[0];if(!reader)throw error(400,'Active reader not found in client institute');let antenna=null,portal=null;if(input.antennaPort!=null){antenna=(await tx.query('SELECT * FROM rfid_antennas WHERE institute_id=$1 AND reader_id=$2 AND antenna_port=$3 AND enabled=true',[client.institute_id,reader.id,input.antennaPort])).rows[0];if(!antenna)throw error(400,'Enabled antenna does not belong to reader');portal=(await tx.query('SELECT p.* FROM rfid_portal_antennas pa JOIN rfid_portals p ON p.id=pa.portal_id WHERE pa.antenna_id=$1 AND p.institute_id=$2 AND p.enabled=true LIMIT 1',[antenna.id,client.institute_id])).rows[0]||null;}const tag=(await tx.query("SELECT id,asset_id FROM asset_tags WHERE institute_id=$1 AND epc=$2 AND tag_status='ACTIVE'",[client.institute_id,epc])).rows[0]||null;const r=await tx.query(`INSERT INTO rfid_read_events(institute_id,integration_client_id,epc,tid,asset_tag_id,asset_id,reader_id,antenna_id,portal_id,rssi,read_timestamp,source_type,external_event_id,raw_payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(integration_client_id,external_event_id) WHERE external_event_id IS NOT NULL DO NOTHING RETURNING *`,[client.institute_id,client.id,epc,input.tid||null,tag?.id||null,tag?.asset_id||null,reader.id,antenna?.id||null,portal?.id||null,input.rssi??null,timestamp,input.sourceType||reader.reader_type,input.externalEventId||null,input.rawPayload||null]);if(r.rowCount)accepted.push(r.rows[0]);}await tx.query('UPDATE rfid_integration_clients SET last_used_at=now() WHERE id=$1',[client.id]);return{accepted:accepted.length,duplicates:items.length-accepted.length,events:accepted};});}
}
module.exports={RfidService,RfidIngestionService,ctx};