const SparePartsRepository = require('../repositories/sparePartsRepository');
const { writeAuditEvent } = require('./auditService');

const error = (statusCode, message) => Object.assign(new Error(message), { statusCode });
const STOCK_FIELDS = ['recommended_stocking_policy', 'recommended_min_quantity', 'recommended_max_quantity', 'recommended_safety_stock', 'typical_lead_time_days', 'estimated_annual_consumption'];
const EDITABLE = ['spare_part_code', 'name', 'description', 'generic_item_id', 'preferred_approved_product_id', 'manufacturer_name', 'oem_part_number', 'manufacturer_part_number', 'drawing_number', 'revision', 'technical_specification', 'spare_part_type', 'criticality', 'failure_consequence', 'interchangeability_status', 'is_repairable', 'is_serialized', 'is_consumable', 'is_safety_critical', 'shelf_life_days', 'storage_conditions'];
const COMPATIBILITY_FIELDS = ['equipment_id', 'compatibility_type', 'serial_number_from', 'serial_number_to', 'oem_confirmed', 'confirmation_reference', 'technical_notes'];
const EQUIPMENT_FIELDS = ['equipment_code', 'name', 'manufacturer', 'model', 'serial_number', 'department_id', 'lifecycle_status'];
const pick = (input, keys) => Object.fromEntries(keys.filter(k => Object.prototype.hasOwnProperty.call(input, k)).map(k => [k, input[k] === '' ? null : input[k]]));

class SparePartsService {
  constructor(repo = new SparePartsRepository(), audit = writeAuditEvent) { this.repo = repo; this.audit = audit; }
  validateQuantities(d) { for (const k of ['recommended_min_quantity', 'recommended_max_quantity', 'recommended_safety_stock', 'estimated_annual_consumption']) if (d[k] != null && (!/^\d+(\.\d+)?$/.test(String(d[k])) || Number(d[k]) < 0)) throw error(400, `${k} must be a non-negative decimal`); if (d.recommended_min_quantity != null && d.recommended_max_quantity != null && Number(d.recommended_max_quantity) < Number(d.recommended_min_quantity)) throw error(400, 'recommended_max_quantity must be greater than or equal to minimum'); for (const k of ['typical_lead_time_days', 'shelf_life_days']) if (d[k] != null && (!Number.isInteger(Number(d[k])) || Number(d[k]) < 0)) throw error(400, `${k} must be a non-negative integer`); }
  async validateMapping(repo, d) { const generic = d.generic_item_id ? await repo.generic(d.generic_item_id) : null; if (d.generic_item_id && !generic) throw error(400, 'Generic item not found'); if (d.preferred_approved_product_id) { const p = await repo.product(d.preferred_approved_product_id); if (!p) throw error(400, 'Approved product not found'); if (!['approved', 'active'].includes(String(p.approval_status).toLowerCase()) || p.is_active === false) throw error(400, 'Preferred approved product is not active and approved'); if (!d.generic_item_id || String(p.generic_item_id) !== String(d.generic_item_id)) throw error(400, 'Preferred approved product must belong to selected generic item'); } }
  async create(input, ctx) { const data = pick(input, [...EDITABLE, ...STOCK_FIELDS]); if (!data.spare_part_code || !data.name || !data.spare_part_type || !data.criticality || !data.failure_consequence) throw error(400, 'Code, name, type, criticality and failure consequence are required'); this.validateQuantities(data); return this.repo.transaction(async repo => { await this.validateMapping(repo, data); const row = await repo.create(data, ctx.instituteId, ctx.userId); await this.audit({ client: repo.db, entityType: 'approved_spare_part', entityId: row.id, action: 'SPARE_PART_CREATED', actorUserId: ctx.userId, instituteId: ctx.instituteId, afterData: row }); return row; }); }
  async update(id, input, ctx) { if (STOCK_FIELDS.some(k => Object.prototype.hasOwnProperty.call(input, k))) throw error(403, 'Stock policy requires spare-parts.manage-stock-policy'); const data = pick(input, EDITABLE); this.validateQuantities(data); return this.repo.transaction(async repo => { const before = await repo.get(id, ctx.instituteId, true); if (!before) throw error(404, 'Spare part not found'); await this.validateMapping(repo, { ...before, ...data }); const row = await repo.update(id, ctx.instituteId, data, ctx.userId, input.row_version); if (!row) throw error(409, 'Spare part was modified; reload and retry'); await this.audit({ client: repo.db, entityType: 'approved_spare_part', entityId: id, action: 'SPARE_PART_UPDATED', actorUserId: ctx.userId, instituteId: ctx.instituteId, beforeData: before, afterData: row }); return row; }); }
  async updateStockPolicy(id, input, ctx) { const supplied = Object.keys(input || {}).filter(k => k !== 'row_version'); if (supplied.some(k => !STOCK_FIELDS.includes(k))) throw error(400, 'Stock-policy endpoint accepts stock-policy fields only'); const data = pick(input, STOCK_FIELDS); if (!Object.keys(data).length) throw error(400, 'At least one stock-policy field is required'); return this.repo.transaction(async repo => { const before = await repo.get(id, ctx.instituteId, true); if (!before) throw error(404, 'Spare part not found'); this.validateQuantities({ ...before, ...data }); const row = await repo.update(id, ctx.instituteId, data, ctx.userId, input.row_version); if (!row) throw error(409, 'Spare part was modified; reload and retry'); await this.audit({ client: repo.db, entityType: 'approved_spare_part', entityId: id, action: 'STOCK_POLICY_CHANGED', actorUserId: ctx.userId, instituteId: ctx.instituteId, beforeData: before, afterData: row }); return row; }); }
  async decision(id, decision, reason, ctx) { const target = { SUBMIT: 'UNDER_REVIEW', APPROVE: 'APPROVED', CONDITIONALLY_APPROVE: 'CONDITIONALLY_APPROVED', REJECT: 'REJECTED' }[decision]; if (!target) throw error(400, 'Invalid technical approval decision'); return this.repo.transaction(async repo => { const before = await repo.get(id, ctx.instituteId, true); if (!before) throw error(404, 'Spare part not found'); const allowed = { DRAFT: ['UNDER_REVIEW'], REJECTED: ['UNDER_REVIEW'], UNDER_REVIEW: ['APPROVED', 'CONDITIONALLY_APPROVED', 'REJECTED'] }[before.technical_approval_status] || []; if (!allowed.includes(target)) throw error(409, `Invalid transition from ${before.technical_approval_status} to ${target}`); if ((['CONDITIONALLY_APPROVED', 'REJECTED'].includes(target) || ((before.criticality === 'CRITICAL' || before.is_safety_critical) && target === 'APPROVED')) && !String(reason || '').trim()) throw error(400, 'Approval reason/reference is required'); const approval = target === 'UNDER_REVIEW' ? { technical_approval_status: target, technical_approved_by: null, technical_approved_at: null, technical_approval_reason: null } : { technical_approval_status: target, technical_approved_by: ctx.userId, technical_approved_at: new Date(), technical_approval_reason: reason || null }; const row = await repo.update(id, ctx.instituteId, approval, ctx.userId, before.row_version); const action = { UNDER_REVIEW: 'SPARE_PART_SUBMITTED_FOR_REVIEW', APPROVED: 'SPARE_PART_TECHNICALLY_APPROVED', CONDITIONALLY_APPROVED: 'SPARE_PART_CONDITIONALLY_APPROVED', REJECTED: 'SPARE_PART_REJECTED' }[target]; await this.audit({ client: repo.db, entityType: 'approved_spare_part', entityId: id, action, actorUserId: ctx.userId, instituteId: ctx.instituteId, beforeData: before, afterData: row, reason }); return row; }); }
  async archive(id, ctx) { return this.repo.transaction(async repo => { const before = await repo.get(id, ctx.instituteId, true); if (!before) throw error(404, 'Spare part not found'); const row = await repo.update(id, ctx.instituteId, { lifecycle_status: 'INACTIVE' }, ctx.userId, before.row_version); await this.audit({ client: repo.db, entityType: 'approved_spare_part', entityId: id, action: 'SPARE_PART_ARCHIVED', actorUserId: ctx.userId, instituteId: ctx.instituteId, beforeData: before, afterData: row }); return row; }); }
  async addCompatibility(id, input, ctx) { return this.repo.transaction(async repo => { if (!await repo.get(id, ctx.instituteId, true)) throw error(404, 'Spare part not found'); if (!await repo.equipment(input.equipment_id, ctx.instituteId)) throw error(400, 'Equipment not found in institute'); const data = pick(input, COMPATIBILITY_FIELDS); if (!data.equipment_id || !data.compatibility_type) throw error(400, 'Equipment and compatibility type are required'); const row = await repo.addCompatibility(id, data, ctx.userId); await this.audit({ client: repo.db, entityType: 'spare_part_compatibility', entityId: row.id, action: 'COMPATIBILITY_ADDED', actorUserId: ctx.userId, instituteId: ctx.instituteId, afterData: row }); return row; }); }
  async updateCompatibility(spareId, compatibilityId, input, ctx) { return this.repo.transaction(async repo => { if (!await repo.get(spareId, ctx.instituteId, true)) throw error(404, 'Spare part not found'); const before = await repo.compatibilityById(compatibilityId, spareId, true); if (!before) throw error(404, 'Compatibility not found'); const data = pick(input, COMPATIBILITY_FIELDS); if (data.equipment_id && !await repo.equipment(data.equipment_id, ctx.instituteId)) throw error(400, 'Equipment not found in institute'); const changed = Object.keys(data).some(k => String(data[k] ?? '') !== String(before[k] ?? '')); if (changed && before.compatibility_status === 'APPROVED') Object.assign(data, { compatibility_status: 'PENDING', approved_by: null, approved_at: null }); const row = changed ? await repo.updateCompatibility(compatibilityId, spareId, data) : before; await this.audit({ client: repo.db, entityType: 'spare_part_compatibility', entityId: compatibilityId, action: 'COMPATIBILITY_UPDATED', actorUserId: ctx.userId, instituteId: ctx.instituteId, beforeData: before, afterData: row }); return row; }); }
  async compatibilityDecision(spareId, compatibilityId, status, ctx) { if (!['APPROVED', 'REJECTED', 'INACTIVE'].includes(status)) throw error(400, 'Invalid compatibility decision'); return this.repo.transaction(async repo => { if (!await repo.get(spareId, ctx.instituteId, true)) throw error(404, 'Spare part not found'); const data = { compatibility_status: status, ...(status === 'APPROVED' ? { approved_by: ctx.userId, approved_at: new Date() } : { approved_by: null, approved_at: null }) }; const row = await repo.updateCompatibility(compatibilityId, spareId, data); if (!row) throw error(404, 'Compatibility not found'); const action = status === 'APPROVED' ? 'COMPATIBILITY_APPROVED' : status === 'REJECTED' ? 'COMPATIBILITY_REJECTED' : 'COMPATIBILITY_INACTIVATED'; await this.audit({ client: repo.db, entityType: 'spare_part_compatibility', entityId: compatibilityId, action, actorUserId: ctx.userId, instituteId: ctx.instituteId, afterData: row }); return row; }); }
  async saveEquipment(id, input, ctx) { const data = pick(input, EQUIPMENT_FIELDS); for (const field of ['equipment_code', 'name', 'manufacturer', 'model']) if (!id && !String(data[field] || '').trim()) throw error(400, 'Code, name, manufacturer and model are required'); if (data.lifecycle_status && !['ACTIVE', 'INACTIVE', 'OBSOLETE', 'SUPERSEDED'].includes(data.lifecycle_status)) throw error(400, 'Invalid equipment lifecycle status'); return this.repo.transaction(async repo => { const before = id ? await repo.equipment(id, ctx.instituteId, true) : null; if (id && !before) throw error(404, 'Equipment not found'); const merged = { ...before, ...data }; for (const field of ['equipment_code', 'name', 'manufacturer', 'model']) if (!String(merged[field] || '').trim()) throw error(400, `${field} is required`); if (merged.department_id && !await repo.department(merged.department_id, ctx.instituteId)) throw error(400, 'Department not found in institute'); const row = await repo.saveEquipment(id, ctx.instituteId, data); await this.audit({ client: repo.db, entityType: 'maintainable_equipment', entityId: row.id, action: id ? 'MAINTAINABLE_EQUIPMENT_UPDATED' : 'MAINTAINABLE_EQUIPMENT_CREATED', actorUserId: ctx.userId, instituteId: ctx.instituteId, beforeData: before, afterData: row }); return row; }); }
}
module.exports = { SparePartsService, EDITABLE, STOCK_FIELDS };