const crypto = require('crypto');
const pool = require('../config/db');
const { InventoryItemCreationService } = require('./inventoryItemCreationService');
const { StockItemMappingService } = require('./stockItemMappingService');
const HEADER_ALIASES = Object.freeze({ source_stock_item_id:['stock item id','stock_item_id','id'],source_name:['stock item name','name','item name'],source_brand:['brand','manufacturer'],source_category:['category'],source_subcategory:['subcategory','sub category','sub_category'],source_uom:['uom','unit','unit of measure'],source_description:['description'] });
const normalizeHeader=(value)=>String(value??'').normalize('NFKC').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');
const validateHeaders=(headers)=>{const normalized=headers.map(normalizeHeader);const columns={};for(const [field,aliases] of Object.entries(HEADER_ALIASES)){const i=normalized.findIndex((h)=>aliases.includes(h));if(i>=0)columns[field]=headers[i];}const missing=['source_stock_item_id','source_name'].filter((f)=>!columns[f]);if(missing.length){const e=new Error(`Missing required spreadsheet headers: ${missing.join(', ')}`);e.statusCode=400;e.code='import_headers_invalid';throw e;}return columns;};
const normalizeText=(value)=>String(value??'').normalize('NFKC').replace(/[‐‑‒–—―]/g,'-').replace(/[×✕]/g,'x').replace(/\s+/g,' ').trim().toLowerCase().replace(/\bmillimet(?:er|re)s?\b/g,'mm').replace(/\bcentimet(?:er|re)s?\b/g,'cm').replace(/\bmillilit(?:er|re)s?\b/g,'ml');
const checksumRow=(row)=>crypto.createHash('sha256').update(JSON.stringify(Object.keys(row).sort().map((k)=>[k,row[k]??null]))).digest('hex');
const HARD_CONFLICTS=new Set(['strength','route','dosage_form','french_size','gauge','lumen_count','sterility','absorbability','needle_size','needle_curvature','suture_size']);
const suggestAttributes=(input)=>{const text=normalizeText(input);const suggestions=[];const add=(attribute_key,suggested_value,source_fragment,normalization_rule,confidence=.9)=>suggestions.push({attribute_key,suggested_value,confidence,source_fragment,normalization_rule});let m;if((m=text.match(/\b(\d{1,2})\s*(?:fr|french)\b/)))add('french_size',Number(m[1]),m[0],'vascular.v1');if((m=text.match(/\b(\d{1,2})\s*(?:g|gauge)\b/)))add('gauge',Number(m[1]),m[0],'gauge.v1');if(/non[- ]?absorbable/.test(text))add('absorbability','non_absorbable','non-absorbable','suture.v1',.98);else if(/absorbable/.test(text))add('absorbability','absorbable','absorbable','suture.v1');if(/\bsterile\b/.test(text))add('sterility',true,'sterile','sterility.v1');return suggestions;};
const scoreCandidate=(source,candidate)=>{const matching=[],conflicting=[],hard_exclusions=[];for(const [key,value] of Object.entries(source.attributes||{})){if(candidate.attributes?.[key]===undefined)continue;if(JSON.stringify(value)===JSON.stringify(candidate.attributes[key]))matching.push(key);else{conflicting.push(key);if(HARD_CONFLICTS.has(key))hard_exclusions.push(`${key}_conflict`);}}const a=new Set(normalizeText(source.name).split(/\W+/).filter(Boolean));const b=new Set(normalizeText(candidate.name).split(/\W+/).filter(Boolean));const common=[...a].filter((x)=>b.has(x));const score=hard_exclusions.length?0:(new Set([...a,...b]).size?common.length/new Set([...a,...b]).size:0);return{candidate_id:candidate.id,candidate_type:candidate.type,score:Number(score.toFixed(4)),matching_attributes:matching,conflicting_attributes:conflicting,hard_exclusions,match_explanation:hard_exclusions.length?`Excluded: ${hard_exclusions.join(', ')}`:`${common.length} normalized name tokens`,parser_version:'phase1b.v1'};};
class StockItemIdentityService { constructor(db=pool){this.creation=new InventoryItemCreationService(db);this.mapping=new StockItemMappingService(db);} addToInventory(payload,actorId){return this.creation.create(payload,actorId);} }
module.exports={HEADER_ALIASES,validateHeaders,normalizeText,checksumRow,suggestAttributes,scoreCandidate,HARD_CONFLICTS,StockItemIdentityService};