'use strict';
const pool=require('../config/db');
const withTransaction=require('../utils/withTransaction');
const InventoryError=require('../errors/inventoryError');
const { hasPermission }=require('../policies/inventoryPolicy');
const { postMovement }=require('./inventoryPostingService');
const { reverseMovement }=require('./inventoryReversalService');

const compatibleStatus=Object.freeze({Pending:'REQUESTED',Approved:'APPROVED',Dispatched:'IN_TRANSIT','In Transit':'IN_TRANSIT',Received:'RECEIVED',Closed:'CLOSED',Cancelled:'CANCELLED',Rejected:'CANCELLED'});
const assertPermission=(actor)=>{if(!hasPermission(actor,'inventory.transfer')) throw new InventoryError('INVENTORY_PERMISSION_DENIED','Permission required: inventory.transfer',403);};
async function lockedTransfer(client,id){const result=await client.query('SELECT * FROM warehouse_transfer_requests WHERE id=$1 FOR UPDATE',[id]);if(!result.rowCount)throw new InventoryError('TRANSFER_NOT_FOUND','Transfer not found',404);return result.rows[0];}

async function dispatchTransfer(input,suppliedClient=null){assertPermission(input.actor);return withTransaction(async(client)=>{
  const transfer=await lockedTransfer(client,input.transferId); const state=compatibleStatus[transfer.status]||String(transfer.status).toUpperCase();
  if(state==='IN_TRANSIT') return {idempotent:true,transfer}; if(!['REQUESTED','APPROVED'].includes(state)) throw new InventoryError('INVALID_TRANSFER_STATE','Transfer cannot be dispatched from its current state',409);
  const warehouse=await client.query('SELECT institute_id FROM warehouses WHERE id=$1 FOR SHARE',[transfer.origin_warehouse_id]);
  const lines=await client.query('SELECT * FROM warehouse_transfer_items WHERE transfer_id=$1 ORDER BY id FOR UPDATE',[transfer.id]); const movements=[];
  for(const line of lines.rows){const posted=await postMovement({movementType:'TRANSFER_DISPATCH',coordinator:'warehouseTransferService',inventoryItemId:line.stock_item_id,instituteId:warehouse.rows[0].institute_id,warehouseId:transfer.origin_warehouse_id,destinationWarehouseId:transfer.destination_warehouse_id,quantity:Number(line.quantity),stockStatus:'AVAILABLE',sourceDocumentType:'warehouse_transfer',sourceDocumentId:transfer.id,sourceDocumentLineId:line.id,reason:input.reason||transfer.notes,actor:input.actor,idempotencyKey:`transfer:${transfer.id}:dispatch:${line.id}`,correlationId:`transfer:${transfer.id}`,metadata:{transferId:transfer.id,transferLineId:line.id}},client);
    await client.query(`INSERT INTO inventory_transfer_movement_links(transfer_id,transfer_line_id,dispatch_movement_id,dispatched_quantity) VALUES($1,$2,$3,$4) ON CONFLICT(transfer_line_id) DO NOTHING`,[transfer.id,line.id,posted.movement.id,line.quantity]);movements.push(posted);}
  const updated=await client.query(`UPDATE warehouse_transfer_requests SET status='Dispatched',dispatched_at=CURRENT_TIMESTAMP,dispatched_by=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *`,[transfer.id,input.actor.id]);return{idempotent:false,transfer:updated.rows[0],movements};
},{client:suppliedClient,pool});}

async function receiveTransfer(input,suppliedClient=null){assertPermission(input.actor);return withTransaction(async(client)=>{
 const transfer=await lockedTransfer(client,input.transferId);const warehouse=await client.query('SELECT institute_id FROM warehouses WHERE id=$1 FOR SHARE',[transfer.destination_warehouse_id]);
 const lines=await client.query(`SELECT wti.*,l.dispatch_movement_id,l.dispatched_quantity,l.received_quantity FROM warehouse_transfer_items wti JOIN inventory_transfer_movement_links l ON l.transfer_line_id=wti.id WHERE wti.transfer_id=$1 ORDER BY wti.id FOR UPDATE OF wti,l`,[transfer.id]);const results=[];
 for(const line of lines.rows){const requested=Number(input.quantities?.[line.id] ?? Number(line.dispatched_quantity)-Number(line.received_quantity));const remaining=Number(line.dispatched_quantity)-Number(line.received_quantity);if(!(requested>0)||requested>remaining)throw new InventoryError('TRANSFER_OVER_RECEIPT',`Receipt quantity exceeds remaining dispatched quantity for line ${line.id}`,409);
  const allocationRows=await client.query('SELECT * FROM inventory_transaction_allocations WHERE inventory_transaction_id=$1 ORDER BY allocation_sequence,id',[line.dispatch_movement_id]);let left=requested;const sequence=Number(input.receiptSequence||1);const movements=[];
  for(const allocation of allocationRows.rows){if(left<=0)break;const quantity=Math.min(left,Math.abs(Number(allocation.quantity)));const posted=await postMovement({movementType:'TRANSFER_RECEIPT',coordinator:'warehouseTransferService',inventoryItemId:line.stock_item_id,instituteId:warehouse.rows[0].institute_id,warehouseId:transfer.destination_warehouse_id,destinationWarehouseId:transfer.destination_warehouse_id,quantity,stockStatus:'AVAILABLE',batchNumber:allocation.batch_number,lotNumber:allocation.lot_number,serialNumber:allocation.serial_number,expiryDate:allocation.expiry_date,sourceDocumentType:'warehouse_transfer',sourceDocumentId:transfer.id,sourceDocumentLineId:line.id,actor:input.actor,idempotencyKey:`transfer:${transfer.id}:receipt:${line.id}:${sequence}:allocation:${allocation.allocation_sequence}`,correlationId:`transfer:${transfer.id}`,metadata:{transferId:transfer.id,transferLineId:line.id,dispatchMovementId:line.dispatch_movement_id,dispatchAllocationId:allocation.id,receiptSequence:sequence}},client);movements.push(posted);left-=quantity;}
  if(left)throw new InventoryError('TRANSFER_ALLOCATION_MISMATCH','Dispatched allocation trace cannot satisfy receipt',409);const receiptIds=movements.map(m=>m.movement.id);await client.query(`UPDATE inventory_transfer_movement_links SET received_quantity=received_quantity+$2,receipt_movement_ids=receipt_movement_ids||$3::jsonb,updated_at=CURRENT_TIMESTAMP WHERE transfer_line_id=$1`,[line.id,requested,JSON.stringify(receiptIds)]);results.push(...movements);}
 const outstanding=await client.query('SELECT COALESCE(SUM(dispatched_quantity-received_quantity),0) remaining FROM inventory_transfer_movement_links WHERE transfer_id=$1',[transfer.id]);const done=Number(outstanding.rows[0].remaining)===0;const updated=await client.query(`UPDATE warehouse_transfer_requests SET status=$2,received_at=CASE WHEN $3 THEN CURRENT_TIMESTAMP ELSE received_at END,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *`,[transfer.id,done?'Received':'In Transit',done]);return{transfer:updated.rows[0],movements:results};
},{client:suppliedClient,pool});}

async function cancelTransfer(input,suppliedClient=null){assertPermission(input.actor);return withTransaction(async(client)=>{const transfer=await lockedTransfer(client,input.transferId);const links=await client.query('SELECT * FROM inventory_transfer_movement_links WHERE transfer_id=$1 ORDER BY transfer_line_id FOR UPDATE',[transfer.id]);for(const link of links.rows){if(Number(link.received_quantity)>0)throw new InventoryError('PARTIAL_TRANSFER_CANCELLATION_REQUIRES_REVIEW','Received transfer quantities cannot be cancelled automatically',409);if(link.dispatch_movement_id)await reverseMovement({movementId:link.dispatch_movement_id,reason:input.reason,actor:input.actor,idempotencyKey:`transfer:${transfer.id}:cancel:${link.transfer_line_id}`},client);}const updated=await client.query(`UPDATE warehouse_transfer_requests SET status='Cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *`,[transfer.id]);return{transfer:updated.rows[0]};},{client:suppliedClient,pool});}
module.exports={compatibleStatus,dispatchTransfer,receiveTransfer,cancelTransfer};