import api from './axios';

export const listContractDocuments = (contractId) => api.get(`/contracts/${contractId}/documents`).then(r => r.data);
export const createContractDocument = (contractId, payload) => api.post(`/contracts/${contractId}/documents`, payload).then(r => r.data);
export const getContractDocument = (contractId, documentId) => api.get(`/contracts/${contractId}/documents/${documentId}`).then(r => r.data);
export const updateContractDocument = (contractId, documentId, payload) => api.patch(`/contracts/${contractId}/documents/${documentId}`, payload).then(r => r.data);
export const addContractDocumentVersion = (contractId, documentId, payload) => api.post(`/contracts/${contractId}/documents/${documentId}/versions`, payload).then(r => r.data);
export const markContractDocumentVersionCurrent = (contractId, documentId, versionId) => api.patch(`/contracts/${contractId}/documents/${documentId}/versions/${versionId}/current`).then(r => r.data);
export const archiveContractDocument = (contractId, documentId) => api.patch(`/contracts/${contractId}/documents/${documentId}/archive`).then(r => r.data);
export const listContractObligations = (contractId, filters = {}) => api.get(`/contracts/${contractId}/obligations`, { params: filters }).then(r => r.data);
export const createContractObligation = (contractId, payload) => api.post(`/contracts/${contractId}/obligations`, payload).then(r => r.data);
export const getContractObligation = (contractId, obligationId) => api.get(`/contracts/${contractId}/obligations/${obligationId}`).then(r => r.data);
export const updateContractObligation = (contractId, obligationId, payload) => api.patch(`/contracts/${contractId}/obligations/${obligationId}`, payload).then(r => r.data);
export const completeContractObligation = (contractId, obligationId, payload) => api.patch(`/contracts/${contractId}/obligations/${obligationId}/complete`, payload).then(r => r.data);
export const waiveContractObligation = (contractId, obligationId, payload) => api.patch(`/contracts/${contractId}/obligations/${obligationId}/waive`, payload).then(r => r.data);
export const cancelContractObligation = (contractId, obligationId, payload) => api.patch(`/contracts/${contractId}/obligations/${obligationId}/cancel`, payload).then(r => r.data);
export const listDueSoonContractObligations = (params = {}) => api.get('/contracts/obligations/due-soon', { params }).then(r => r.data);
export const listContractRenewalEvents = (contractId) => api.get(`/contracts/${contractId}/renewal-events`).then(r => r.data);
export const createContractRenewalEvent = (contractId, payload) => api.post(`/contracts/${contractId}/renewal-events`, payload).then(r => r.data);
export const updateContractRenewalEvent = (contractId, renewalEventId, payload) => api.patch(`/contracts/${contractId}/renewal-events/${renewalEventId}`, payload).then(r => r.data);
export const decideContractRenewalEvent = (contractId, renewalEventId, payload) => api.patch(`/contracts/${contractId}/renewal-events/${renewalEventId}/decision`, payload).then(r => r.data);
export const listDueSoonContractRenewals = (params = {}) => api.get('/contracts/renewals/due-soon', { params }).then(r => r.data);
export const listContractInvoices = (contractId) => api.get(`/contracts/${contractId}/invoices`).then(r => r.data);
export const createContractInvoice = (contractId, payload) => api.post(`/contracts/${contractId}/invoices`, payload).then(r => r.data);
export const getContractInvoice = (contractId, invoiceId) => api.get(`/contracts/${contractId}/invoices/${invoiceId}`).then(r => r.data);
export const updateContractInvoice = (contractId, invoiceId, payload) => api.patch(`/contracts/${contractId}/invoices/${invoiceId}`, payload).then(r => r.data);
export const matchContractInvoice = (contractId, invoiceId) => api.patch(`/contracts/${contractId}/invoices/${invoiceId}/match`).then(r => r.data);
export const updateContractInvoiceStatus = (contractId, invoiceId, payload) => api.patch(`/contracts/${contractId}/invoices/${invoiceId}/status`, payload).then(r => r.data);
export const listContractPayments = (contractId) => api.get(`/contracts/${contractId}/payments`).then(r => r.data);
export const createContractPayment = (contractId, payload) => api.post(`/contracts/${contractId}/payments`, payload).then(r => r.data);
export const updateContractPayment = (contractId, paymentId, payload) => api.patch(`/contracts/${contractId}/payments/${paymentId}`, payload).then(r => r.data);
export const updateContractPaymentStatus = (contractId, paymentId, payload) => api.patch(`/contracts/${contractId}/payments/${paymentId}/status`, payload).then(r => r.data);
export const listContractConsumption = (contractId) => api.get(`/contracts/${contractId}/consumption-entries`).then(r => r.data);
export const createContractConsumption = (contractId, payload) => api.post(`/contracts/${contractId}/consumption-entries`, payload).then(r => r.data);
export const getContractFinancialSummary = (contractId) => api.get(`/contracts/${contractId}/financial-summary`).then(r => r.data);
export const getContractRisk = (contractId, params = {}) => api.get(`/contracts/${contractId}/risk`, { params }).then(r => r.data);
export const recalculateContractRisk = (contractId, payload = {}) => api.post(`/contracts/${contractId}/risk/recalculate`, payload).then(r => r.data);
export const listContractRiskHistory = (contractId) => api.get(`/contracts/${contractId}/risk/history`).then(r => r.data);
export const getContractRiskDashboard = (params = {}) => api.get('/contracts/dashboard/risk', { params }).then(r => r.data);
export const listHighRiskContracts = (params = {}) => api.get('/contracts/risk/high', { params }).then(r => r.data);
export const runContractAiExtraction = (contractId, payload = {}) => api.post(`/contracts/${contractId}/ai-extract`, payload).then(r => r.data);
export const listContractAiExtractions = (contractId) => api.get(`/contracts/${contractId}/ai-extractions`).then(r => r.data);
export const getContractAiExtraction = (contractId, extractionId) => api.get(`/contracts/${contractId}/ai-extractions/${extractionId}`).then(r => r.data);