import axios from './axios';
const data = request => request.then(response => response.data);
export const getPublicPriorityQueue = params => data(axios.get('/procurement-priority/public',{params}));
export const getDepartmentPriorityQueue = () => data(axios.get('/procurement-priority/department'));
export const reorderDepartmentPriority = (ordered_case_ids,version) => data(axios.put('/procurement-priority/department/reorder',{ordered_case_ids,version}));
export const getPriorityProfile = id => data(axios.get(`/procurement-priority/cases/${id}`));
export const getPriorityHistory = id => data(axios.get(`/procurement-priority/cases/${id}/history`));
export const updatePriorityAssessment = (id,input) => data(axios.put(`/procurement-priority/cases/${id}/assessment`,input));
export const overrideInstitutionalRank = (id,institutional_rank,reason) => data(axios.put(`/procurement-priority/cases/${id}/institutional-rank`,{institutional_rank,reason}));
export const createPriorityGroup = input => data(axios.post('/procurement-priority/groups',input));