const service = require('../services/approvalPolicyService');
const actor = req => ({ id: req.user?.id || req.user?.userId, instituteId: req.user?.institute_id || req.user?.instituteId });
const handle = fn => async (req, res, next) => { try { await fn(req, res); } catch (error) { next(error); } };
exports.list = handle(async (req, res) => res.json(await service.listPolicies(actor(req))));
exports.create = handle(async (req, res) => res.status(201).json(await service.createPolicy(req.body, actor(req))));
exports.detail = handle(async (req, res) => { const value = await service.getPolicyDetail(req.params.id, actor(req)); if (!value) return res.status(404).json({ error: 'Policy not found' }); res.json(value); });
exports.update = handle(async (req, res) => res.json(await service.updatePolicy(req.params.id, req.body, actor(req))));
exports.createVersion = handle(async (req, res) => res.status(201).json(await service.createVersion(req.params.id, req.body, actor(req))));
exports.versions = handle(async (req, res) => res.json(await service.getVersions(req.params.id, actor(req))));
exports.version = handle(async (req, res) => { const value=await service.hydrateVersion(req.params.id,actor(req)); if(!value)return res.status(404).json({error:'Version not found'}); res.json(value); });
exports.patchVersion = handle(async (req, res) => res.json(await service.replaceDraft(req.params.id, req.body, actor(req))));
exports.validate = handle(async (req, res) => res.json(await service.validate(req.params.id, actor(req))));
exports.enterShadow = handle(async (req, res) => res.json(await service.enterShadow(req.params.id, actor(req))));
exports.run = handle(async (req, res) => res.status(201).json(await service.runShadow(req.params.requestId, req.params.id, actor(req))));
exports.runs = handle(async (req, res) => res.json(await service.listShadowRuns(req.query, actor(req))));
exports.runDetail = handle(async (req, res) => { const value=await service.getShadowRun(req.params.id,actor(req)); if(!value)return res.status(404).json({error:'Shadow run not found'}); res.json(value); });
exports.batch = handle(async (req,res)=>res.status(201).json(await service.runShadowBatch(req.body,actor(req))));