-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ap_payables (
  id bigint NOT NULL DEFAULT nextval('ap_payables_id_seq'::regclass),
  request_id integer NOT NULL,
  supplier_invoice_id bigint NOT NULL,
  supplier_name text NOT NULL,
  invoice_total numeric NOT NULL,
  open_balance numeric NOT NULL,
  due_date date,
  payable_status text NOT NULL DEFAULT 'OPEN'::text,
  posted_by integer,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ap_payables_pkey PRIMARY KEY (id),
  CONSTRAINT ap_payables_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT ap_payables_supplier_invoice_id_fkey FOREIGN KEY (supplier_invoice_id) REFERENCES public.supplier_invoices(id),
  CONSTRAINT ap_payables_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id)
);
CREATE TABLE public.ap_voucher_lines (
  id bigint NOT NULL DEFAULT nextval('ap_voucher_lines_id_seq'::regclass),
  ap_voucher_id bigint NOT NULL,
  line_number integer NOT NULL,
  account_code text,
  description text NOT NULL,
  debit_amount numeric NOT NULL DEFAULT 0,
  credit_amount numeric NOT NULL DEFAULT 0,
  reference_type text,
  reference_id text,
  CONSTRAINT ap_voucher_lines_pkey PRIMARY KEY (id),
  CONSTRAINT ap_voucher_lines_ap_voucher_id_fkey FOREIGN KEY (ap_voucher_id) REFERENCES public.ap_vouchers(id)
);
CREATE TABLE public.ap_vouchers (
  id bigint NOT NULL DEFAULT nextval('ap_vouchers_id_seq'::regclass),
  request_id integer NOT NULL,
  supplier_invoice_id bigint,
  voucher_number text NOT NULL UNIQUE,
  voucher_status text NOT NULL DEFAULT 'draft'::text,
  currency text DEFAULT 'USD'::text,
  total_amount numeric NOT NULL,
  created_by integer,
  verified_by integer,
  posted_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  verified_at timestamp with time zone,
  posted_at timestamp with time zone,
  voided_at timestamp with time zone,
  CONSTRAINT ap_vouchers_pkey PRIMARY KEY (id),
  CONSTRAINT ap_vouchers_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT ap_vouchers_supplier_invoice_id_fkey FOREIGN KEY (supplier_invoice_id) REFERENCES public.supplier_invoices(id),
  CONSTRAINT ap_vouchers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT ap_vouchers_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT ap_vouchers_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id)
);
CREATE TABLE public.approval_logs (
  id integer NOT NULL DEFAULT nextval('approval_logs_id_seq'::regclass),
  approval_id integer,
  request_id integer,
  approver_id integer,
  action character varying,
  comments text,
  timestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT approval_logs_pkey PRIMARY KEY (id),
  CONSTRAINT approval_logs_approval_id_fkey FOREIGN KEY (approval_id) REFERENCES public.approvals(id),
  CONSTRAINT approval_logs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT approval_logs_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.users(id)
);
CREATE TABLE public.approval_route_rules (
  id integer NOT NULL DEFAULT nextval('approval_route_rules_id_seq'::regclass),
  version_id integer NOT NULL,
  request_type character varying NOT NULL,
  department_type character varying NOT NULL,
  approval_level integer NOT NULL,
  role character varying NOT NULL,
  min_amount bigint DEFAULT 0,
  max_amount bigint DEFAULT 999999999,
  CONSTRAINT approval_route_rules_pkey PRIMARY KEY (id),
  CONSTRAINT approval_route_rules_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.approval_route_versions(id)
);
CREATE TABLE public.approval_route_versions (
  id integer NOT NULL DEFAULT nextval('approval_route_versions_id_seq'::regclass),
  version_label character varying NOT NULL,
  change_summary text,
  is_active boolean NOT NULL DEFAULT false,
  created_by integer,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT approval_route_versions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.approval_routes (
  id integer NOT NULL DEFAULT nextval('approval_routes_id_seq'::regclass),
  request_type character varying NOT NULL,
  department_type character varying NOT NULL,
  approval_level integer NOT NULL,
  role character varying NOT NULL,
  min_amount bigint DEFAULT 0,
  max_amount bigint DEFAULT 999999999,
  CONSTRAINT approval_routes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.approvals (
  id integer NOT NULL DEFAULT nextval('approvals_id_seq'::regclass),
  request_id integer,
  approver_id integer,
  approval_level integer,
  status character varying DEFAULT 'Pending'::character varying,
  comments text,
  approved_at timestamp without time zone,
  is_active boolean DEFAULT false,
  is_urgent boolean DEFAULT false,
  reminder_sent_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT approvals_pkey PRIMARY KEY (id),
  CONSTRAINT approvals_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.users(id)
);
CREATE TABLE public.attachments (
  id integer NOT NULL DEFAULT nextval('attachments_id_seq'::regclass),
  request_id integer,
  file_name text NOT NULL,
  file_path text NOT NULL,
  uploaded_by integer,
  uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  item_id bigint,
  contract_id bigint,
  CONSTRAINT attachments_pkey PRIMARY KEY (id),
  CONSTRAINT attachments_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT attachments_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.requested_items(id),
  CONSTRAINT attachments_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.audit_logs (
  id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass),
  action text,
  action_type text,
  actor_id integer,
  user_id integer,
  target_type text,
  target_id integer,
  description text,
  details text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_registry_entries (
  id bigint NOT NULL DEFAULT nextval('audit_registry_entries_id_seq'::regclass),
  request_id integer NOT NULL,
  requester_id integer NOT NULL,
  requester_type text NOT NULL CHECK (requester_type = ANY (ARRAY['INDIVIDUAL'::text, 'COMMITTEE'::text])),
  account_name text,
  notes text,
  required_before_payment text,
  required_after_payment text,
  audit_status text NOT NULL DEFAULT 'PENDING_AUDIT'::text CHECK (audit_status = ANY (ARRAY['PENDING_AUDIT'::text, 'ACTION_REQUIRED'::text, 'READY_FOR_FINANCE'::text, 'FINANCE_PROCESSING'::text, 'COMPLETED'::text])),
  finance_issued_amount numeric NOT NULL DEFAULT 0,
  returned_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  completed_at timestamp with time zone,
  created_by integer,
  updated_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_registry_entries_pkey PRIMARY KEY (id),
  CONSTRAINT audit_registry_entries_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT audit_registry_entries_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.users(id),
  CONSTRAINT audit_registry_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT audit_registry_entries_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.budget_envelopes (
  id bigint NOT NULL DEFAULT nextval('budget_envelopes_id_seq'::regclass),
  department_id integer NOT NULL,
  project_id uuid,
  fiscal_year integer NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  allocated_amount numeric NOT NULL DEFAULT 0,
  consumed_amount numeric NOT NULL DEFAULT 0,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_envelopes_pkey PRIMARY KEY (id),
  CONSTRAINT budget_envelopes_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT budget_envelopes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_envelopes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.commitment_ledger (
  id bigint NOT NULL DEFAULT nextval('commitment_ledger_id_seq'::regclass),
  request_id integer NOT NULL,
  budget_envelope_id bigint NOT NULL,
  stage text NOT NULL CHECK (stage = ANY (ARRAY['reservation'::text, 'encumbrance'::text, 'actual'::text])),
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  source_type text,
  source_id text,
  notes text,
  actor_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT commitment_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT commitment_ledger_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT commitment_ledger_budget_envelope_id_fkey FOREIGN KEY (budget_envelope_id) REFERENCES public.budget_envelopes(id),
  CONSTRAINT commitment_ledger_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.contract_evaluations (
  id integer NOT NULL DEFAULT nextval('contract_evaluations_id_seq'::regclass),
  contract_id integer NOT NULL,
  evaluator_id integer NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  evaluation_notes text,
  evaluation_criteria jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  criterion_id integer,
  criterion_name text,
  criterion_role text,
  criterion_code text,
  technical_inspection_results jsonb,
  request_fulfillment_metrics jsonb,
  CONSTRAINT contract_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT contract_evaluations_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_evaluations_evaluator_id_fkey FOREIGN KEY (evaluator_id) REFERENCES public.users(id),
  CONSTRAINT contract_evaluations_criterion_id_fkey FOREIGN KEY (criterion_id) REFERENCES public.evaluation_criteria(id)
);
CREATE TABLE public.contracts (
  id integer NOT NULL DEFAULT nextval('contracts_id_seq'::regclass),
  title text NOT NULL,
  vendor text NOT NULL,
  reference_number text,
  start_date date,
  end_date date,
  contract_value numeric,
  status text NOT NULL DEFAULT 'active'::text,
  description text,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  delivery_terms text,
  warranty_terms text,
  performance_management text,
  end_user_department_id integer,
  contract_manager_id integer,
  technical_department_ids jsonb,
  supplier_id integer,
  source_request_id integer,
  amount_paid numeric DEFAULT 0,
  signing_date date,
  contract_type text,
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT contracts_end_user_department_id_fkey FOREIGN KEY (end_user_department_id) REFERENCES public.departments(id),
  CONSTRAINT contracts_contract_manager_id_fkey FOREIGN KEY (contract_manager_id) REFERENCES public.users(id),
  CONSTRAINT contracts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT contracts_source_request_id_fkey FOREIGN KEY (source_request_id) REFERENCES public.requests(id)
);
CREATE TABLE public.custody_records (
  id integer NOT NULL DEFAULT nextval('custody_records_id_seq'::regclass),
  item_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  description text,
  custody_type text NOT NULL CHECK (custody_type = ANY (ARRAY['Personal'::text, 'Departmental'::text])),
  custody_code text,
  issued_by integer NOT NULL,
  custodian_user_id integer,
  custodian_department_id integer,
  hod_user_id integer,
  user_approval_status text NOT NULL DEFAULT 'Pending'::text,
  user_approved_at timestamp without time zone,
  hod_approval_status text NOT NULL DEFAULT 'Pending'::text,
  hod_approved_at timestamp without time zone,
  status text NOT NULL DEFAULT 'Pending'::text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT custody_records_pkey PRIMARY KEY (id),
  CONSTRAINT custody_records_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.users(id),
  CONSTRAINT custody_records_custodian_user_id_fkey FOREIGN KEY (custodian_user_id) REFERENCES public.users(id),
  CONSTRAINT custody_records_custodian_department_id_fkey FOREIGN KEY (custodian_department_id) REFERENCES public.departments(id),
  CONSTRAINT custody_records_hod_user_id_fkey FOREIGN KEY (hod_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.data_scopes (
  id integer NOT NULL DEFAULT nextval('data_scopes_id_seq'::regclass),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  CONSTRAINT data_scopes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.department_stock_levels (
  id integer NOT NULL DEFAULT nextval('department_stock_levels_id_seq'::regclass),
  department_id integer NOT NULL,
  section_id integer,
  warehouse_batch_id integer,
  stock_item_id integer NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  updated_by integer,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  lot_number text,
  expiry_date date,
  serial_number text,
  CONSTRAINT department_stock_levels_pkey PRIMARY KEY (id),
  CONSTRAINT department_stock_levels_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT department_stock_levels_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT department_stock_levels_warehouse_batch_id_fkey FOREIGN KEY (warehouse_batch_id) REFERENCES public.warehouse_item_batches(id),
  CONSTRAINT department_stock_levels_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id)
);
CREATE TABLE public.department_stock_movements (
  id integer NOT NULL DEFAULT nextval('department_stock_movements_id_seq'::regclass),
  department_stock_level_id integer NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['in'::text, 'out'::text])),
  quantity numeric NOT NULL,
  source_warehouse_id integer,
  source_batch_id integer,
  reference_request_id integer,
  notes text,
  created_by integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  lot_number text,
  expiry_date date,
  serial_number text,
  CONSTRAINT department_stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT department_stock_movements_level_id_fkey FOREIGN KEY (department_stock_level_id) REFERENCES public.department_stock_levels(id),
  CONSTRAINT department_stock_movements_source_warehouse_id_fkey FOREIGN KEY (source_warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT department_stock_movements_source_batch_id_fkey FOREIGN KEY (source_batch_id) REFERENCES public.warehouse_item_batches(id),
  CONSTRAINT department_stock_movements_reference_request_id_fkey FOREIGN KEY (reference_request_id) REFERENCES public.requests(id),
  CONSTRAINT department_stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.departments (
  id integer NOT NULL DEFAULT nextval('departments_id_seq'::regclass),
  name character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['Medical'::character varying::text, 'Operational'::character varying::text])),
  institute_id integer,
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.institutes(id)
);
CREATE TABLE public.document_flow_links (
  id bigint NOT NULL DEFAULT nextval('document_flow_links_id_seq'::regclass),
  request_id integer NOT NULL,
  source_document_type text NOT NULL,
  source_document_id text NOT NULL,
  target_document_type text NOT NULL,
  target_document_id text NOT NULL,
  metadata jsonb,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_flow_links_pkey PRIMARY KEY (id),
  CONSTRAINT document_flow_links_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT document_flow_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.evaluation_criteria (
  id integer NOT NULL DEFAULT nextval('evaluation_criteria_id_seq'::regclass),
  name text NOT NULL,
  role text NOT NULL,
  components jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  code text,
  assignment_config jsonb,
  CONSTRAINT evaluation_criteria_pkey PRIMARY KEY (id)
);
CREATE TABLE public.finance_action_history (
  id bigint NOT NULL DEFAULT nextval('finance_action_history_id_seq'::regclass),
  request_id integer NOT NULL,
  action_type text NOT NULL,
  actor_id integer,
  action_payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT finance_action_history_pkey PRIMARY KEY (id),
  CONSTRAINT finance_action_history_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT finance_action_history_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.finance_chart_of_accounts (
  id integer NOT NULL DEFAULT nextval('finance_chart_of_accounts_id_seq'::regclass),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['asset'::text, 'liability'::text, 'equity'::text, 'revenue'::text, 'expense'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT finance_chart_of_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.finance_cost_centers (
  id integer NOT NULL DEFAULT nextval('finance_cost_centers_id_seq'::regclass),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  department_id integer,
  project_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT finance_cost_centers_pkey PRIMARY KEY (id),
  CONSTRAINT finance_cost_centers_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT finance_cost_centers_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.finance_postings (
  id bigint NOT NULL DEFAULT nextval('finance_postings_id_seq'::regclass),
  request_id integer NOT NULL,
  ap_voucher_id bigint,
  posting_status text NOT NULL DEFAULT 'draft'::text,
  posting_reference text,
  liability_recognized_amount numeric NOT NULL DEFAULT 0,
  posted_by integer,
  posted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT finance_postings_pkey PRIMARY KEY (id),
  CONSTRAINT finance_postings_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT finance_postings_ap_voucher_id_fkey FOREIGN KEY (ap_voucher_id) REFERENCES public.ap_vouchers(id),
  CONSTRAINT finance_postings_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id)
);
CREATE TABLE public.gl_posting_lines (
  id bigint NOT NULL DEFAULT nextval('gl_posting_lines_id_seq'::regclass),
  gl_posting_id bigint NOT NULL,
  line_no integer NOT NULL,
  account_code text NOT NULL,
  cost_center_id integer,
  debit_amount numeric NOT NULL DEFAULT 0,
  credit_amount numeric NOT NULL DEFAULT 0,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gl_posting_lines_pkey PRIMARY KEY (id),
  CONSTRAINT gl_posting_lines_gl_posting_id_fkey FOREIGN KEY (gl_posting_id) REFERENCES public.gl_postings(id),
  CONSTRAINT gl_posting_lines_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES public.finance_cost_centers(id)
);
CREATE TABLE public.gl_postings (
  id bigint NOT NULL DEFAULT nextval('gl_postings_id_seq'::regclass),
  request_id integer NOT NULL,
  source_type text NOT NULL,
  source_id text,
  posting_reference text NOT NULL UNIQUE,
  posting_status text NOT NULL DEFAULT 'posted'::text,
  currency text NOT NULL DEFAULT 'USD'::text,
  total_amount numeric NOT NULL DEFAULT 0,
  posted_by integer,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gl_postings_pkey PRIMARY KEY (id),
  CONSTRAINT gl_postings_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT gl_postings_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id)
);
CREATE TABLE public.goods_receipt_items (
  id bigint NOT NULL DEFAULT nextval('goods_receipt_items_id_seq'::regclass),
  goods_receipt_id bigint NOT NULL,
  requested_item_id integer,
  item_name text NOT NULL,
  ordered_quantity numeric,
  received_quantity numeric NOT NULL,
  damaged_quantity numeric DEFAULT 0,
  short_quantity numeric DEFAULT 0,
  unit_price numeric,
  line_notes text,
  CONSTRAINT goods_receipt_items_pkey PRIMARY KEY (id),
  CONSTRAINT goods_receipt_items_goods_receipt_id_fkey FOREIGN KEY (goods_receipt_id) REFERENCES public.goods_receipts(id),
  CONSTRAINT goods_receipt_items_requested_item_id_fkey FOREIGN KEY (requested_item_id) REFERENCES public.requested_items(id)
);
CREATE TABLE public.goods_receipts (
  id bigint NOT NULL DEFAULT nextval('goods_receipts_id_seq'::regclass),
  request_id integer NOT NULL,
  receipt_number text,
  warehouse_location text,
  received_by integer NOT NULL,
  received_at timestamp with time zone NOT NULL,
  notes text,
  discrepancy_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  purchase_order_id bigint,
  CONSTRAINT goods_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT goods_receipts_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT goods_receipts_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.users(id),
  CONSTRAINT goods_receipts_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.governance_audit_trail (
  id bigint NOT NULL DEFAULT nextval('governance_audit_trail_id_seq'::regclass),
  actor_id integer,
  actor_role text,
  request_path text NOT NULL,
  method text NOT NULL,
  status_code integer NOT NULL,
  module text NOT NULL,
  resource text NOT NULL,
  action text NOT NULL,
  required_permissions ARRAY NOT NULL DEFAULT '{}'::text[],
  request_id text,
  ip_address text,
  user_agent text,
  payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_audit_trail_pkey PRIMARY KEY (id)
);
CREATE TABLE public.institutes (
  id integer NOT NULL DEFAULT nextval('institutes_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  governance_group text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT institutes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transactions (
  id integer NOT NULL DEFAULT nextval('inventory_transactions_id_seq'::regclass),
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['warehouse'::text, 'department'::text, 'transfer'::text, 'receipt'::text, 'issue'::text, 'adjustment'::text, 'recall'::text])),
  source_location text,
  destination_location text,
  warehouse_id integer,
  department_id integer,
  section_id integer,
  batch_id integer,
  stock_item_id integer NOT NULL,
  quantity numeric NOT NULL,
  unit_cost numeric,
  reference_document text,
  reference_request_id integer,
  reference_transfer_id integer,
  warehouse_stock_movement_id integer,
  department_stock_movement_id integer,
  notes text,
  created_by integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT inventory_transactions_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT inventory_transactions_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT inventory_transactions_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.warehouse_item_batches(id),
  CONSTRAINT inventory_transactions_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT inventory_transactions_reference_request_id_fkey FOREIGN KEY (reference_request_id) REFERENCES public.requests(id),
  CONSTRAINT inventory_transactions_warehouse_movement_id_fkey FOREIGN KEY (warehouse_stock_movement_id) REFERENCES public.warehouse_stock_movements(id),
  CONSTRAINT inventory_transactions_department_movement_id_fkey FOREIGN KEY (department_stock_movement_id) REFERENCES public.department_stock_movements(id),
  CONSTRAINT inventory_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_items (
  id bigint NOT NULL DEFAULT nextval('invoice_items_id_seq'::regclass),
  supplier_invoice_id bigint NOT NULL,
  requested_item_id integer,
  description text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  line_total numeric NOT NULL,
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_supplier_invoice_id_fkey FOREIGN KEY (supplier_invoice_id) REFERENCES public.supplier_invoices(id),
  CONSTRAINT invoice_items_requested_item_id_fkey FOREIGN KEY (requested_item_id) REFERENCES public.requested_items(id)
);
CREATE TABLE public.invoice_match_results (
  id bigint NOT NULL DEFAULT nextval('invoice_match_results_id_seq'::regclass),
  request_id integer NOT NULL,
  supplier_invoice_id bigint NOT NULL,
  match_policy text NOT NULL,
  match_status text NOT NULL,
  mismatch_reasons jsonb,
  matched_by integer,
  matched_at timestamp with time zone NOT NULL DEFAULT now(),
  override_approved boolean NOT NULL DEFAULT false,
  override_by integer,
  override_reason text,
  override_at timestamp with time zone,
  CONSTRAINT invoice_match_results_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_match_results_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT invoice_match_results_supplier_invoice_id_fkey FOREIGN KEY (supplier_invoice_id) REFERENCES public.supplier_invoices(id),
  CONSTRAINT invoice_match_results_matched_by_fkey FOREIGN KEY (matched_by) REFERENCES public.users(id),
  CONSTRAINT invoice_match_results_override_by_fkey FOREIGN KEY (override_by) REFERENCES public.users(id)
);
CREATE TABLE public.item_brands (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  brand_name text NOT NULL UNIQUE,
  manufacturer_id integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_brands_pkey PRIMARY KEY (id),
  CONSTRAINT item_brands_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.item_manufacturers(id)
);
CREATE TABLE public.item_categories (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  category_name text NOT NULL UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.item_conversion (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  item_master_id integer,
  from_uom_id integer NOT NULL,
  to_uom_id integer NOT NULL,
  conversion_factor numeric NOT NULL CHECK (conversion_factor > 0::numeric),
  is_bidirectional boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_conversion_pkey PRIMARY KEY (id),
  CONSTRAINT item_conversion_item_master_id_fkey FOREIGN KEY (item_master_id) REFERENCES public.item_master(id),
  CONSTRAINT item_conversion_from_uom_id_fkey FOREIGN KEY (from_uom_id) REFERENCES public.item_uom(id),
  CONSTRAINT item_conversion_to_uom_id_fkey FOREIGN KEY (to_uom_id) REFERENCES public.item_uom(id)
);
CREATE TABLE public.item_manufacturers (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  manufacturer_name text NOT NULL UNIQUE,
  country_of_origin text,
  contact_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_manufacturers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.item_master (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  item_code text NOT NULL UNIQUE,
  item_name text NOT NULL,
  generic_name text,
  category_id integer,
  base_uom_id integer,
  manufacturer_id integer,
  brand_id integer,
  description text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'inactive'::text, 'archived'::text])),
  created_by integer,
  updated_by integer,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_master_pkey PRIMARY KEY (id),
  CONSTRAINT item_master_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.item_categories(id),
  CONSTRAINT item_master_base_uom_id_fkey FOREIGN KEY (base_uom_id) REFERENCES public.item_uom(id),
  CONSTRAINT item_master_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.item_manufacturers(id),
  CONSTRAINT item_master_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.item_brands(id),
  CONSTRAINT item_master_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT item_master_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.item_master_documents (
  id integer NOT NULL DEFAULT nextval('item_master_documents_id_seq'::regclass),
  item_id integer NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['catalogue'::text, 'coa_coc'::text, 'msds'::text, 'registration_certificate'::text, 'technical_datasheet'::text])),
  document_name text NOT NULL,
  file_path text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  uploaded_by integer,
  uploaded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_master_documents_pkey PRIMARY KEY (id),
  CONSTRAINT item_master_documents_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master_items(id),
  CONSTRAINT item_master_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.item_master_items (
  id integer NOT NULL DEFAULT nextval('item_master_items_id_seq'::regclass),
  item_code text NOT NULL UNIQUE,
  item_name text NOT NULL,
  generic_name text,
  brand_name text,
  category text NOT NULL,
  subcategory text,
  item_classification text NOT NULL CHECK (item_classification = ANY (ARRAY['medication'::text, 'medical_supply'::text, 'medical_device'::text, 'laboratory_item'::text, 'maintenance_spare_part'::text, 'it_item'::text, 'stationery'::text, 'general_item'::text])),
  unit_of_measure text NOT NULL,
  pack_size text,
  specifications text,
  storage_condition text,
  batch_controlled boolean NOT NULL DEFAULT false,
  expiry_controlled boolean NOT NULL DEFAULT false,
  serial_controlled boolean NOT NULL DEFAULT false,
  standard_cost numeric,
  preferred_suppliers jsonb NOT NULL DEFAULT '[]'::jsonb,
  contract_eligibility boolean NOT NULL DEFAULT false,
  reorder_level numeric,
  safety_stock numeric,
  institute_applicability jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_approval'::text, 'active'::text, 'rejected'::text])),
  submitted_by integer,
  submitted_at timestamp without time zone,
  approved_by integer,
  approved_at timestamp without time zone,
  rejection_reason text,
  created_by integer,
  updated_by integer,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_master_items_pkey PRIMARY KEY (id),
  CONSTRAINT item_master_items_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.users(id),
  CONSTRAINT item_master_items_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT item_master_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT item_master_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.item_recalls (
  id integer NOT NULL DEFAULT nextval('item_recalls_id_seq'::regclass),
  item_id integer,
  item_name text NOT NULL,
  quantity integer,
  reason text NOT NULL,
  notes text,
  department_id integer NOT NULL,
  initiated_by_user_id integer NOT NULL,
  recall_type text NOT NULL CHECK (recall_type = ANY (ARRAY['department_to_warehouse'::text, 'warehouse_to_procurement'::text])),
  status text NOT NULL DEFAULT 'Pending Warehouse Review'::text,
  escalated_to_procurement boolean NOT NULL DEFAULT false,
  escalated_at timestamp without time zone,
  escalated_by_user_id integer,
  warehouse_notes text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  recall_notice text,
  supplier_letters text,
  ncr_reference text,
  capa_reference text,
  final_report text,
  lot_number text,
  quarantine_active boolean DEFAULT false,
  quarantine_reason text,
  quarantine_started_at timestamp with time zone,
  CONSTRAINT item_recalls_pkey PRIMARY KEY (id),
  CONSTRAINT item_recalls_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.stock_items(id),
  CONSTRAINT item_recalls_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT item_recalls_initiated_by_user_id_fkey FOREIGN KEY (initiated_by_user_id) REFERENCES public.users(id),
  CONSTRAINT item_recalls_escalated_by_user_id_fkey FOREIGN KEY (escalated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.item_uom (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  uom_code text NOT NULL UNIQUE,
  uom_name text NOT NULL UNIQUE,
  description text,
  is_base_uom boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_uom_pkey PRIMARY KEY (id)
);
CREATE TABLE public.item_variants (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  item_master_id integer NOT NULL,
  variant_code text UNIQUE,
  variant_name text NOT NULL,
  sku text UNIQUE,
  variant_attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT item_variants_pkey PRIMARY KEY (id),
  CONSTRAINT item_variants_item_master_id_fkey FOREIGN KEY (item_master_id) REFERENCES public.item_master(id)
);
CREATE TABLE public.maintenance_stock (
  id integer NOT NULL DEFAULT nextval('maintenance_stock_id_seq'::regclass),
  item_name text NOT NULL UNIQUE,
  quantity integer NOT NULL DEFAULT 0,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT maintenance_stock_pkey PRIMARY KEY (id)
);
CREATE TABLE public.monthly_dispensing (
  id integer NOT NULL DEFAULT nextval('monthly_dispensing_id_seq'::regclass),
  month_start date NOT NULL,
  item_name text NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  unit text,
  facility_name text,
  notes text,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT monthly_dispensing_pkey PRIMARY KEY (id),
  CONSTRAINT monthly_dispensing_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.non_po_receipt_approvals (
  id bigint NOT NULL DEFAULT nextval('non_po_receipt_approvals_id_seq'::regclass),
  goods_receipt_id bigint NOT NULL,
  request_id integer NOT NULL,
  approval_step text NOT NULL,
  approval_status text NOT NULL DEFAULT 'PENDING'::text,
  assigned_role text,
  approved_by integer,
  approved_at timestamp with time zone,
  comments text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT non_po_receipt_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT non_po_receipt_approvals_goods_receipt_id_fkey FOREIGN KEY (goods_receipt_id) REFERENCES public.goods_receipts(id),
  CONSTRAINT non_po_receipt_approvals_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT non_po_receipt_approvals_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id integer NOT NULL DEFAULT nextval('notifications_id_seq'::regclass),
  user_id integer NOT NULL,
  title text,
  message text NOT NULL,
  link text,
  metadata jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_allocations (
  id bigint NOT NULL DEFAULT nextval('payment_allocations_id_seq'::regclass),
  payment_record_id bigint NOT NULL,
  ap_payable_id bigint NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT payment_allocations_payment_record_id_fkey FOREIGN KEY (payment_record_id) REFERENCES public.payment_records(id),
  CONSTRAINT payment_allocations_ap_payable_id_fkey FOREIGN KEY (ap_payable_id) REFERENCES public.ap_payables(id)
);
CREATE TABLE public.payment_records (
  id bigint NOT NULL DEFAULT nextval('payment_records_id_seq'::regclass),
  request_id integer NOT NULL,
  ap_voucher_id bigint,
  payment_status text NOT NULL DEFAULT 'payment_pending'::text,
  payment_reference text,
  payment_method text,
  amount_paid numeric NOT NULL DEFAULT 0,
  paid_by integer,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_records_pkey PRIMARY KEY (id),
  CONSTRAINT payment_records_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT payment_records_ap_voucher_id_fkey FOREIGN KEY (ap_voucher_id) REFERENCES public.ap_vouchers(id),
  CONSTRAINT payment_records_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(id)
);
CREATE TABLE public.permissions (
  id integer NOT NULL DEFAULT nextval('permissions_id_seq'::regclass),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.procurement_lifecycle_states (
  id integer NOT NULL DEFAULT nextval('procurement_lifecycle_states_id_seq'::regclass),
  request_id integer NOT NULL UNIQUE,
  procurement_state text NOT NULL DEFAULT 'REQUEST_CREATED'::text,
  finance_state text NOT NULL DEFAULT 'draft'::text,
  finance_match_policy text NOT NULL DEFAULT 'THREE_WAY'::text,
  payment_state text NOT NULL DEFAULT 'unpaid'::text,
  last_transition_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT procurement_lifecycle_states_pkey PRIMARY KEY (id),
  CONSTRAINT procurement_lifecycle_states_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT procurement_lifecycle_states_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.procurement_plan_item_consumptions (
  id integer NOT NULL DEFAULT nextval('procurement_plan_item_consumptions_id_seq'::regclass),
  plan_item_id integer NOT NULL,
  warehouse_stock_movement_id integer,
  department_stock_movement_id integer,
  quantity numeric NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT procurement_plan_item_consumptions_pkey PRIMARY KEY (id),
  CONSTRAINT procurement_plan_item_consumptions_warehouse_stock_movement_id_ FOREIGN KEY (warehouse_stock_movement_id) REFERENCES public.warehouse_stock_movements(id),
  CONSTRAINT procurement_plan_item_consumptions_department_stock_movement_id FOREIGN KEY (department_stock_movement_id) REFERENCES public.department_stock_movements(id),
  CONSTRAINT procurement_plan_item_consumptions_plan_item_id_fkey FOREIGN KEY (plan_item_id) REFERENCES public.procurement_plan_items(id)
);
CREATE TABLE public.procurement_plan_item_requests (
  id integer NOT NULL DEFAULT nextval('procurement_plan_item_requests_id_seq'::regclass),
  plan_item_id integer NOT NULL,
  request_id integer,
  requested_item_id integer,
  quantity numeric NOT NULL,
  unit_cost numeric,
  total_cost numeric,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT procurement_plan_item_requests_pkey PRIMARY KEY (id),
  CONSTRAINT procurement_plan_item_requests_plan_item_id_fkey FOREIGN KEY (plan_item_id) REFERENCES public.procurement_plan_items(id),
  CONSTRAINT procurement_plan_item_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT procurement_plan_item_requests_requested_item_id_fkey FOREIGN KEY (requested_item_id) REFERENCES public.requested_items(id)
);
CREATE TABLE public.procurement_plan_items (
  id integer NOT NULL DEFAULT nextval('procurement_plan_items_id_seq'::regclass),
  plan_id integer NOT NULL,
  stock_item_id integer,
  item_name text NOT NULL,
  description text,
  unit_of_measure text,
  planned_quantity numeric NOT NULL,
  planned_unit_cost numeric,
  planned_total_cost numeric,
  currency text,
  needed_by_date date,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT procurement_plan_items_pkey PRIMARY KEY (id),
  CONSTRAINT procurement_plan_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.procurement_plans(id),
  CONSTRAINT procurement_plan_items_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id)
);
CREATE TABLE public.procurement_plans (
  id integer NOT NULL DEFAULT nextval('procurement_plans_id_seq'::regclass),
  department_id integer,
  plan_year integer NOT NULL,
  file_name character varying,
  file_path text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT procurement_plans_pkey PRIMARY KEY (id),
  CONSTRAINT procurement_plans_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.procurement_state_history (
  id bigint NOT NULL DEFAULT nextval('procurement_state_history_id_seq'::regclass),
  request_id integer NOT NULL,
  from_state text,
  to_state text NOT NULL,
  changed_by integer,
  reason text,
  metadata jsonb,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT procurement_state_history_pkey PRIMARY KEY (id),
  CONSTRAINT procurement_state_history_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT procurement_state_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by integer,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.purchase_order_items (
  id bigint NOT NULL DEFAULT nextval('purchase_order_items_id_seq'::regclass),
  purchase_order_id bigint NOT NULL,
  requested_item_id integer,
  item_name text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL DEFAULT 0,
  received_quantity numeric NOT NULL DEFAULT 0,
  invoiced_quantity numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_requested_item_id_fkey FOREIGN KEY (requested_item_id) REFERENCES public.requested_items(id),
  CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.purchase_orders (
  id bigint NOT NULL DEFAULT nextval('purchase_orders_id_seq'::regclass),
  request_id integer NOT NULL,
  rfx_id integer,
  rfx_response_id integer,
  supplier_id integer,
  po_number text UNIQUE,
  status text NOT NULL DEFAULT 'PO_DRAFT'::text,
  currency text DEFAULT 'USD'::text,
  total_amount numeric,
  notes text,
  created_by integer,
  issued_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  supplier_name text,
  source_document_type text NOT NULL DEFAULT 'PURCHASE_REQUEST'::text,
  source_document_id text,
  contract_reference text,
  expected_delivery_date date,
  delivery_location text,
  budget_cost_center text,
  tax_terms text,
  payment_terms text,
  terms text,
  supplier_contact_email text,
  approval_required boolean NOT NULL DEFAULT false,
  approval_route text,
  approved_by integer,
  approved_at timestamp with time zone,
  issue_event_at timestamp with time zone,
  issued_to_supplier_at timestamp with time zone,
  cancellation_reason text,
  amendment_reason text,
  last_amended_at timestamp with time zone,
  issued_by integer,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT purchase_orders_rfx_id_fkey FOREIGN KEY (rfx_id) REFERENCES public.rfx_events(id),
  CONSTRAINT purchase_orders_rfx_response_id_fkey FOREIGN KEY (rfx_response_id) REFERENCES public.rfx_responses(id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT purchase_orders_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT purchase_orders_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.users(id)
);
CREATE TABLE public.request_logs (
  id integer NOT NULL DEFAULT nextval('request_logs_id_seq'::regclass),
  request_id integer,
  action character varying NOT NULL,
  actor_id integer,
  comments text,
  timestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT request_logs_pkey PRIMARY KEY (id),
  CONSTRAINT request_logs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT request_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.requested_item_financials (
  id integer NOT NULL DEFAULT nextval('requested_item_financials_id_seq'::regclass),
  requested_item_id integer NOT NULL UNIQUE,
  request_id integer NOT NULL,
  po_number text,
  invoice_number text,
  committed_cost numeric,
  paid_cost numeric,
  currency text,
  savings_driver text,
  savings_notes text,
  savings_baseline numeric,
  contract_id integer,
  contract_value_snapshot numeric,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT requested_item_financials_pkey PRIMARY KEY (id),
  CONSTRAINT requested_item_financials_requested_item_id_fkey FOREIGN KEY (requested_item_id) REFERENCES public.requested_items(id),
  CONSTRAINT requested_item_financials_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT requested_item_financials_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.requested_items (
  id integer NOT NULL DEFAULT nextval('requested_items_id_seq'::regclass),
  request_id integer,
  item_name character varying NOT NULL,
  quantity integer NOT NULL,
  unit_cost bigint,
  available_quantity integer,
  intended_use text,
  specs text,
  device_info jsonb,
  purchase_type character varying CHECK (purchase_type::text = ANY (ARRAY['First Time'::character varying, 'Replacement'::character varying, 'Addition'::character varying]::text[])),
  approval_status character varying DEFAULT 'Pending'::character varying,
  total_cost bigint,
  procurement_status character varying DEFAULT 'pending'::character varying,
  procurement_comment text,
  marked_by integer,
  marked_at timestamp without time zone,
  procurement_updated_by integer,
  procurement_updated_at timestamp without time zone,
  purchased_quantity integer DEFAULT 0,
  brand text,
  approval_comments text,
  approved_by integer,
  approved_at timestamp with time zone,
  is_received boolean DEFAULT false,
  received_by integer,
  received_at timestamp with time zone,
  po_issuance_method text,
  CONSTRAINT requested_items_pkey PRIMARY KEY (id),
  CONSTRAINT requested_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT requested_items_marked_by_fkey FOREIGN KEY (marked_by) REFERENCES public.users(id),
  CONSTRAINT requested_items_procurement_updated_by_fkey FOREIGN KEY (procurement_updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.requests (
  id integer NOT NULL DEFAULT nextval('requests_id_seq'::regclass),
  request_type character varying NOT NULL CHECK (request_type::text = ANY (ARRAY['Stock'::character varying::text, 'Non-Stock'::character varying::text, 'Medical Device'::character varying::text, 'Medication'::character varying::text, 'IT Item'::character varying::text, 'Maintenance'::character varying::text, 'Warehouse Supply'::character varying::text, 'Printing Logbook'::character varying::text])),
  requester_id integer,
  department_id integer,
  status character varying DEFAULT 'Submitted'::character varying,
  justification text,
  estimated_cost bigint,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  assigned_to integer,
  request_domain character varying DEFAULT 'operational'::character varying CHECK (request_domain::text = ANY (ARRAY['medical'::character varying, 'operational'::character varying]::text[])),
  is_urgent boolean DEFAULT false,
  maintenance_ref_number text,
  initiated_by_technician_id integer,
  section_id integer,
  completed_at timestamp without time zone,
  print_count integer NOT NULL DEFAULT 0,
  project_id uuid,
  temporary_requester_name text,
  supply_warehouse_id integer,
  awarded_supplier_id integer,
  awarded_rfx_id integer,
  awarded_rfx_response_id integer,
  purchase_order_id integer,
  purchase_order_number text,
  sourcing_status text,
  awarded_at timestamp with time zone,
  po_issued_at timestamp with time zone,
  institute_id integer,
  CONSTRAINT requests_pkey PRIMARY KEY (id),
  CONSTRAINT requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.users(id),
  CONSTRAINT requests_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT requests_initiated_by_technician_id_fkey FOREIGN KEY (initiated_by_technician_id) REFERENCES public.users(id),
  CONSTRAINT requests_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT requests_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT requests_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT requests_awarded_supplier_id_fkey FOREIGN KEY (awarded_supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT requests_awarded_rfx_id_fkey FOREIGN KEY (awarded_rfx_id) REFERENCES public.rfx_events(id),
  CONSTRAINT requests_awarded_rfx_response_id_fkey FOREIGN KEY (awarded_rfx_response_id) REFERENCES public.rfx_responses(id),
  CONSTRAINT requests_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.institutes(id),
  CONSTRAINT requests_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT requests_supply_warehouse_id_fkey FOREIGN KEY (supply_warehouse_id) REFERENCES public.warehouses(id)
);
CREATE TABLE public.rfx_events (
  id integer NOT NULL DEFAULT nextval('rfx_events_id_seq'::regclass),
  title text NOT NULL,
  rfx_type text NOT NULL,
  description text,
  due_date timestamp with time zone,
  status text NOT NULL DEFAULT 'open'::text,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  request_id integer,
  details jsonb,
  CONSTRAINT rfx_events_pkey PRIMARY KEY (id),
  CONSTRAINT rfx_events_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT rfx_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.rfx_responses (
  id integer NOT NULL DEFAULT nextval('rfx_responses_id_seq'::regclass),
  rfx_id integer NOT NULL,
  supplier_id integer,
  submitted_by integer,
  bid_amount numeric,
  notes text,
  response_data jsonb,
  status text NOT NULL DEFAULT 'submitted'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  request_id integer,
  CONSTRAINT rfx_responses_pkey PRIMARY KEY (id),
  CONSTRAINT rfx_responses_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT rfx_responses_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.users(id),
  CONSTRAINT rfx_responses_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT rfx_responses_rfx_id_fkey FOREIGN KEY (rfx_id) REFERENCES public.rfx_events(id)
);
CREATE TABLE public.risk_register (
  id integer NOT NULL DEFAULT nextval('risk_register_id_seq'::regclass),
  title text NOT NULL,
  category text,
  description text,
  likelihood text NOT NULL DEFAULT 'possible'::text,
  impact text NOT NULL DEFAULT 'moderate'::text,
  risk_score integer NOT NULL DEFAULT 9,
  status text NOT NULL DEFAULT 'open'::text,
  owner text,
  response_plan text,
  due_date date,
  medication_risk jsonb,
  high_risk_item jsonb,
  supplier_risk jsonb,
  created_by_user_id integer,
  updated_by_user_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_at timestamp with time zone,
  CONSTRAINT risk_register_pkey PRIMARY KEY (id),
  CONSTRAINT risk_register_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT risk_register_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.role_data_scopes (
  role_id integer NOT NULL,
  data_scope_id integer NOT NULL,
  scope_value text NOT NULL,
  CONSTRAINT role_data_scopes_pkey PRIMARY KEY (role_id, data_scope_id, scope_value),
  CONSTRAINT role_data_scopes_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_data_scopes_data_scope_id_fkey FOREIGN KEY (data_scope_id) REFERENCES public.data_scopes(id)
);
CREATE TABLE public.role_permissions (
  role_id integer NOT NULL,
  permission_id integer NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.roles (
  id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sections (
  id integer NOT NULL DEFAULT nextval('sections_id_seq'::regclass),
  name character varying NOT NULL,
  department_id integer,
  CONSTRAINT sections_pkey PRIMARY KEY (id),
  CONSTRAINT sections_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.stock_item_requests (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  description text,
  unit text,
  requested_by integer,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_by integer,
  inserted_at timestamp with time zone DEFAULT now(),
  review_notes text,
  CONSTRAINT stock_item_requests_pkey PRIMARY KEY (id),
  CONSTRAINT stock_item_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT stock_item_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.stock_items (
  id integer NOT NULL DEFAULT nextval('stock_items_id_seq'::regclass),
  name text NOT NULL,
  brand text,
  cost numeric,
  description text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  category character varying,
  unit text,
  created_by integer,
  sub_category text,
  available_quantity numeric,
  CONSTRAINT stock_items_pkey PRIMARY KEY (id),
  CONSTRAINT stock_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.supplier_compliance_artifacts (
  id integer NOT NULL DEFAULT nextval('supplier_compliance_artifacts_id_seq'::regclass),
  supplier_id integer NOT NULL,
  artifact_type text NOT NULL,
  name text NOT NULL,
  document_url text,
  expiry_date date,
  status text NOT NULL DEFAULT 'active'::text,
  blocked boolean NOT NULL DEFAULT false,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT supplier_compliance_artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_compliance_artifacts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.supplier_document_submissions (
  id bigint NOT NULL DEFAULT nextval('supplier_document_submissions_id_seq'::regclass),
  request_id integer,
  rfq_id bigint,
  purchase_order_id bigint,
  supplier_id integer NOT NULL,
  supplier_user_id bigint,
  document_type text NOT NULL,
  submission_status text NOT NULL DEFAULT 'submitted'::text,
  reference_number text,
  file_name text,
  storage_path text,
  mime_type text,
  file_size_bytes bigint,
  notes text,
  metadata jsonb,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_by integer,
  reviewed_at timestamp with time zone,
  CONSTRAINT supplier_document_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_document_submissions_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT supplier_document_submissions_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT supplier_document_submissions_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT supplier_document_submissions_supplier_user_id_fkey FOREIGN KEY (supplier_user_id) REFERENCES public.supplier_users(id),
  CONSTRAINT supplier_document_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.supplier_evaluations (
  id integer NOT NULL DEFAULT nextval('supplier_evaluations_id_seq'::regclass),
  supplier_name text NOT NULL,
  evaluation_date date NOT NULL DEFAULT CURRENT_DATE,
  quality_score numeric,
  delivery_score numeric,
  cost_score numeric,
  compliance_score numeric,
  overall_score numeric NOT NULL,
  strengths text,
  weaknesses text,
  action_items text,
  evaluator_id integer,
  evaluator_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  otif_score numeric,
  corrective_actions_score numeric,
  esg_compliance_score numeric,
  weighted_overall_score numeric,
  kpi_weights jsonb,
  criteria_responses jsonb,
  scheduled_annually boolean NOT NULL DEFAULT true,
  travel_required boolean DEFAULT false,
  evaluation_criteria_notes text,
  overall_supplier_happiness numeric CHECK (overall_supplier_happiness IS NULL OR overall_supplier_happiness >= 1::numeric AND overall_supplier_happiness <= 5::numeric),
  price_satisfaction numeric CHECK (price_satisfaction IS NULL OR price_satisfaction >= 1::numeric AND price_satisfaction <= 5::numeric),
  delivery_as_scheduled numeric CHECK (delivery_as_scheduled IS NULL OR delivery_as_scheduled >= 1::numeric AND delivery_as_scheduled <= 5::numeric),
  delivery_in_good_condition numeric CHECK (delivery_in_good_condition IS NULL OR delivery_in_good_condition >= 1::numeric AND delivery_in_good_condition <= 5::numeric),
  delivery_meets_quality_expectations numeric CHECK (delivery_meets_quality_expectations IS NULL OR delivery_meets_quality_expectations >= 1::numeric AND delivery_meets_quality_expectations <= 5::numeric),
  communication_effectiveness numeric CHECK (communication_effectiveness IS NULL OR communication_effectiveness >= 1::numeric AND communication_effectiveness <= 5::numeric),
  compliance_alignment numeric CHECK (compliance_alignment IS NULL OR compliance_alignment >= 1::numeric AND compliance_alignment <= 5::numeric),
  operations_effectiveness_rating numeric CHECK (operations_effectiveness_rating IS NULL OR operations_effectiveness_rating >= 1::numeric AND operations_effectiveness_rating <= 5::numeric),
  payment_terms_comfort numeric CHECK (payment_terms_comfort IS NULL OR payment_terms_comfort >= 1::numeric AND payment_terms_comfort <= 5::numeric),
  CONSTRAINT supplier_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_evaluations_evaluator_id_fkey FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.supplier_invoices (
  id bigint NOT NULL DEFAULT nextval('supplier_invoices_id_seq'::regclass),
  request_id integer NOT NULL,
  supplier text NOT NULL,
  invoice_number text NOT NULL,
  invoice_date date NOT NULL,
  subtotal_amount numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  extra_charges numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  po_equivalent_number text,
  receipt_id bigint,
  attachment_metadata jsonb,
  submitted_by integer,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  purchase_order_id bigint,
  CONSTRAINT supplier_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_invoices_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT supplier_invoices_receipt_id_fkey FOREIGN KEY (receipt_id) REFERENCES public.goods_receipts(id),
  CONSTRAINT supplier_invoices_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.users(id),
  CONSTRAINT supplier_invoices_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.supplier_issues (
  id integer NOT NULL DEFAULT nextval('supplier_issues_id_seq'::regclass),
  supplier_id integer NOT NULL,
  contract_id integer,
  request_id integer,
  description text NOT NULL,
  severity text DEFAULT 'medium'::text,
  status text NOT NULL DEFAULT 'open'::text,
  capa_required boolean DEFAULT false,
  capa_plan text,
  due_date date,
  resolved_at timestamp with time zone,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT supplier_issues_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_issues_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT supplier_issues_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.supplier_portal_sessions (
  id bigint NOT NULL DEFAULT nextval('supplier_portal_sessions_id_seq'::regclass),
  supplier_user_id bigint NOT NULL,
  session_token_hash text NOT NULL UNIQUE,
  refresh_token_hash text,
  ip_address inet,
  user_agent text,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  revoked_at timestamp with time zone,
  revoked_reason text,
  last_seen_at timestamp with time zone,
  metadata jsonb,
  CONSTRAINT supplier_portal_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_portal_sessions_supplier_user_id_fkey FOREIGN KEY (supplier_user_id) REFERENCES public.supplier_users(id)
);
CREATE TABLE public.supplier_scorecards (
  id integer NOT NULL DEFAULT nextval('supplier_scorecards_id_seq'::regclass),
  supplier_id integer NOT NULL,
  contract_id integer,
  request_id integer,
  period_start date,
  period_end date,
  otif_score numeric NOT NULL,
  quality_defects integer DEFAULT 0,
  lead_time_variance numeric,
  notes text,
  created_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT supplier_scorecards_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_scorecards_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT supplier_scorecards_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.supplier_users (
  id bigint NOT NULL DEFAULT nextval('supplier_users_id_seq'::regclass),
  supplier_id integer NOT NULL,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'supplier_user'::text,
  password_hash text,
  auth_provider text NOT NULL DEFAULT 'local'::text,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  invited_by integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT supplier_users_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_users_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT supplier_users_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.suppliers (
  id integer NOT NULL DEFAULT nextval('suppliers_id_seq'::regclass),
  name text NOT NULL,
  contact_email text,
  contact_phone text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.technical_inspections (
  id integer NOT NULL DEFAULT nextval('technical_inspections_id_seq'::regclass),
  inspection_date date NOT NULL DEFAULT CURRENT_DATE,
  location text,
  item_name text NOT NULL,
  item_category text,
  model_number text,
  serial_number text,
  lot_number text,
  manufacturer text,
  supplier_name text,
  general_checklist jsonb NOT NULL DEFAULT '[]'::jsonb,
  category_checklist jsonb NOT NULL DEFAULT '[]'::jsonb,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  inspectors jsonb NOT NULL DEFAULT '[]'::jsonb,
  approvals jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by integer,
  created_by_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  request_id integer,
  requested_item_id integer,
  acceptance_status text DEFAULT 'pending'::text,
  acceptance_notes text,
  acceptance_recorded_by integer,
  acceptance_recorded_at timestamp with time zone,
  CONSTRAINT technical_inspections_pkey PRIMARY KEY (id),
  CONSTRAINT technical_inspections_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT technical_inspections_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT technical_inspections_requested_item_id_fkey FOREIGN KEY (requested_item_id) REFERENCES public.requested_items(id),
  CONSTRAINT technical_inspections_acceptance_recorded_by_fkey FOREIGN KEY (acceptance_recorded_by) REFERENCES public.users(id)
);
CREATE TABLE public.ui_resource_permissions (
  resource_key text NOT NULL,
  label text NOT NULL,
  description text,
  permissions ARRAY NOT NULL DEFAULT '{}'::text[],
  require_all boolean NOT NULL DEFAULT false,
  CONSTRAINT ui_resource_permissions_pkey PRIMARY KEY (resource_key)
);
CREATE TABLE public.user_data_scopes (
  user_id integer NOT NULL,
  data_scope_id integer NOT NULL,
  scope_value text NOT NULL,
  CONSTRAINT user_data_scopes_pkey PRIMARY KEY (user_id, data_scope_id, scope_value),
  CONSTRAINT user_data_scopes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_data_scopes_data_scope_id_fkey FOREIGN KEY (data_scope_id) REFERENCES public.data_scopes(id)
);
CREATE TABLE public.user_permissions (
  user_id integer NOT NULL,
  permission_id integer NOT NULL,
  CONSTRAINT user_permissions_pkey PRIMARY KEY (user_id, permission_id),
  CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.user_registration_requests (
  id integer NOT NULL DEFAULT nextval('user_registration_requests_id_seq'::regclass),
  name text NOT NULL,
  email text NOT NULL,
  password_hash text NOT NULL,
  requested_role text NOT NULL DEFAULT 'requester'::text,
  department_id integer NOT NULL,
  section_id integer,
  status text NOT NULL DEFAULT 'pending'::text,
  rejection_reason text,
  reviewer_id integer,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  employee_id text,
  institute_id integer,
  CONSTRAINT user_registration_requests_pkey PRIMARY KEY (id),
  CONSTRAINT user_registration_requests_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT user_registration_requests_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT user_registration_requests_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT user_registration_requests_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.institutes(id)
);
CREATE TABLE public.users (
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  role character varying NOT NULL,
  department_id integer,
  section_id integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  can_request_medication boolean DEFAULT false,
  employee_id text,
  warehouse_id integer,
  institute_id integer,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT users_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT users_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.institutes(id),
  CONSTRAINT users_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id)
);
CREATE TABLE public.warehouse_item_batches (
  id integer NOT NULL DEFAULT nextval('warehouse_item_batches_id_seq'::regclass),
  warehouse_id integer NOT NULL,
  stock_item_id integer NOT NULL,
  batch_number text,
  expiry_date date,
  quantity numeric NOT NULL DEFAULT 0,
  available_quantity numeric NOT NULL DEFAULT 0,
  supplier_id integer,
  received_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  lot_number text,
  manufactured_date date,
  received_date date DEFAULT CURRENT_DATE,
  unit_cost numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT warehouse_item_batches_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_item_batches_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_item_batches_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT warehouse_item_batches_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.warehouse_replenishment_policies (
  id integer NOT NULL DEFAULT nextval('warehouse_replenishment_policies_id_seq'::regclass),
  warehouse_id integer NOT NULL,
  stock_item_id integer NOT NULL,
  reorder_point numeric NOT NULL DEFAULT 0,
  safety_stock numeric NOT NULL DEFAULT 0,
  lead_time_days integer NOT NULL DEFAULT 14,
  review_period_days integer NOT NULL DEFAULT 7,
  lot_size numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by integer,
  CONSTRAINT warehouse_replenishment_policies_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_replenishment_policies_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_replenishment_policies_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT warehouse_replenishment_policies_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.warehouse_replenishment_tasks (
  id integer NOT NULL DEFAULT nextval('warehouse_replenishment_tasks_id_seq'::regclass),
  warehouse_id integer NOT NULL,
  stock_item_id integer NOT NULL,
  current_quantity numeric NOT NULL DEFAULT 0,
  reorder_point numeric NOT NULL DEFAULT 0,
  safety_stock numeric NOT NULL DEFAULT 0,
  suggested_quantity numeric NOT NULL DEFAULT 0,
  due_date date,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'planned'::text, 'ordered'::text, 'completed'::text, 'dismissed'::text])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  CONSTRAINT warehouse_replenishment_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_replenishment_tasks_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_replenishment_tasks_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT warehouse_replenishment_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.warehouse_stock_levels (
  id integer NOT NULL DEFAULT nextval('warehouse_stock_levels_id_seq'::regclass),
  warehouse_id integer NOT NULL,
  stock_item_id integer NOT NULL,
  item_name text NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  updated_by integer,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  batch_id integer,
  lot_number text,
  expiry_date date,
  serial_number text,
  CONSTRAINT warehouse_stock_levels_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_stock_levels_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT warehouse_stock_levels_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT warehouse_stock_levels_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_stock_levels_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.warehouse_item_batches(id)
);
CREATE TABLE public.warehouse_stock_movements (
  id integer NOT NULL DEFAULT nextval('warehouse_stock_movements_id_seq'::regclass),
  warehouse_id integer NOT NULL,
  stock_item_id integer,
  item_name text NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['in'::text, 'out'::text])),
  quantity numeric NOT NULL,
  reference_request_id integer,
  to_department_id integer,
  notes text,
  created_by integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  batch_id integer,
  to_section_id integer,
  lot_number text,
  expiry_date date,
  serial_number text,
  reference_transfer_id integer,
  CONSTRAINT warehouse_stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_stock_movements_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT warehouse_stock_movements_reference_request_id_fkey FOREIGN KEY (reference_request_id) REFERENCES public.requests(id),
  CONSTRAINT warehouse_stock_movements_to_department_id_fkey FOREIGN KEY (to_department_id) REFERENCES public.departments(id),
  CONSTRAINT warehouse_stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT warehouse_stock_movements_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_stock_movements_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.warehouse_item_batches(id),
  CONSTRAINT warehouse_stock_movements_to_section_id_fkey FOREIGN KEY (to_section_id) REFERENCES public.sections(id)
);
CREATE TABLE public.warehouse_supplied_items (
  id integer NOT NULL DEFAULT nextval('warehouse_supplied_items_id_seq'::regclass),
  request_id integer NOT NULL,
  item_id integer NOT NULL,
  supplied_quantity integer NOT NULL,
  supplied_by integer,
  supplied_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  warehouse_id integer,
  batch_id integer,
  department_id integer,
  section_id integer,
  department_stock_level_id integer,
  supplied_from_stock_level_id integer,
  received_by integer,
  received_at timestamp with time zone,
  CONSTRAINT warehouse_supplied_items_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_supplied_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT warehouse_supplied_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.warehouse_supply_items(id),
  CONSTRAINT warehouse_supplied_items_supplied_by_fkey FOREIGN KEY (supplied_by) REFERENCES public.users(id),
  CONSTRAINT warehouse_supplied_items_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_supplied_items_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.warehouse_item_batches(id),
  CONSTRAINT warehouse_supplied_items_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT warehouse_supplied_items_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.sections(id),
  CONSTRAINT warehouse_supplied_items_department_stock_level_id_fkey FOREIGN KEY (department_stock_level_id) REFERENCES public.department_stock_levels(id),
  CONSTRAINT warehouse_supplied_items_supplied_from_stock_level_id_fkey FOREIGN KEY (supplied_from_stock_level_id) REFERENCES public.warehouse_stock_levels(id),
  CONSTRAINT warehouse_supplied_items_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.users(id)
);
CREATE TABLE public.warehouse_supply_items (
  id integer NOT NULL DEFAULT nextval('warehouse_supply_items_id_seq'::regclass),
  request_id integer,
  item_name text NOT NULL,
  quantity integer NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  requested_item_id smallint,
  CONSTRAINT warehouse_supply_items_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_supply_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id)
);
CREATE TABLE public.warehouse_supply_templates (
  id bigint NOT NULL DEFAULT nextval('warehouse_supply_templates_id_seq'::regclass),
  template_name text NOT NULL UNIQUE,
  items jsonb NOT NULL,
  inserted_at timestamp with time zone DEFAULT now(),
  department_id integer,
  CONSTRAINT warehouse_supply_templates_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_supply_templates_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.warehouse_transfer_items (
  id integer NOT NULL DEFAULT nextval('warehouse_transfer_items_id_seq'::regclass),
  transfer_id integer NOT NULL,
  stock_item_id integer NOT NULL,
  item_name text NOT NULL,
  quantity numeric NOT NULL,
  notes text,
  CONSTRAINT warehouse_transfer_items_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_transfer_items_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.warehouse_transfer_requests(id),
  CONSTRAINT warehouse_transfer_items_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id)
);
CREATE TABLE public.warehouse_transfer_requests (
  id integer NOT NULL DEFAULT nextval('warehouse_transfer_requests_id_seq'::regclass),
  origin_warehouse_id integer NOT NULL,
  destination_warehouse_id integer NOT NULL,
  status text NOT NULL DEFAULT 'Pending'::text,
  notes text,
  requested_by integer,
  approved_by integer,
  approved_at timestamp with time zone,
  rejected_by integer,
  rejected_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT warehouse_transfer_requests_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_transfer_requests_origin_warehouse_id_fkey FOREIGN KEY (origin_warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_transfer_requests_destination_warehouse_id_fkey FOREIGN KEY (destination_warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_transfer_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT warehouse_transfer_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT warehouse_transfer_requests_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(id)
);
CREATE TABLE public.warehouses (
  id integer NOT NULL DEFAULT nextval('warehouses_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  type text NOT NULL DEFAULT 'warehouse'::text,
  location text,
  description text,
  department_id integer UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  institute_id integer,
  CONSTRAINT warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT warehouses_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT warehouses_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.institutes(id)
);