const ItemMasterRepository=require('../repositories/itemMasterRepository');
const {deriveIdentity}=require('../services/inventoryItemCreationService');
const {ItemMasterFoundationService}=require('../services/itemMasterFoundationService');

const transactionDb=(handler)=>{const calls=[];const client={query:jest.fn(async(sql,values)=>{calls.push({sql,values});return handler(sql,values,calls);}),release:jest.fn()};return {db:{connect:jest.fn(async()=>client)},client,calls};};

test('repository SQL uses only deployed canonical names',async()=>{const queries=[];const repo=new ItemMasterRepository({query:async(sql)=>{queries.push(sql);return{rows:[]}}});await repo.findGeneric(1);await repo.findProduct(2);await repo.findUom(3);const sql=queries.join('\n');expect(sql).toContain('c.category_name');expect(sql).toContain('m.manufacturer_name');expect(sql).toContain('u.uom_name');expect(sql).toContain('ap.product_uom_id');expect(sql).not.toMatch(/\bc\.name\b|\bm\.name\b|\bu\.name\b|ap\.uom_id/);});

test('controlled identity uses canonical category, manufacturer and UOM display fields',()=>{expect(deriveIdentity({id:1,generic_name:'Syringe',canonical_description:'Sterile',category_id:2,category_name:'Medical Supplies',subcategory:'Injection'},{id:3,manufacturer_id:4,manufacturer_name:'BD',manufacturer_part_number:'A-1'},{id:5,uom_code:'EA',uom_name:'Each'})).toMatchObject({name:'Syringe — BD — A-1',categoryName:'Medical Supplies',manufacturerName:'BD',uomName:'Each'});});

describe('reference governance',()=>{
 const success=(sql)=>sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK'?{rows:[],rowCount:0}:sql.includes('RETURNING')?{rows:[{id:9,uom_code:'EA',uom_name:'Each'}],rowCount:1}:{rows:[],rowCount:1};
 test.each([['categories',{name:'Medical Supplies'},'category_name'],['manufacturers',{name:'BD'},'manufacturer_name'],['uom',{code:'EA',name:'Each'},'uom_name']])('creates %s and audit atomically',async(type,payload,field)=>{const x=transactionDb(success);await new ItemMasterFoundationService(x.db).createReference(type,payload,7);expect(x.calls.map(c=>c.sql)).toEqual(expect.arrayContaining(['BEGIN','COMMIT']));expect(x.calls.some(c=>c.sql.includes(field))).toBe(true);expect(x.calls.some(c=>c.sql.includes('REFERENCE_CREATED'))).toBe(true);});
 test.each([['categories',{}],['manufacturers',{}],['uom',{code:'EA'}],['uom',{name:'Each'}],['bad',{name:'x'}]])('rejects missing fields or invalid type: %s',async(type,payload)=>{await expect(new ItemMasterFoundationService({}).createReference(type,payload,1)).rejects.toMatchObject({statusCode:400});});
 test('maps normalized duplicate to controlled conflict',async()=>{const x=transactionDb(sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return{rows:[]};const e=Object.assign(new Error('unique'),{code:'23505'});throw e;});await expect(new ItemMasterFoundationService(x.db).createReference('categories',{name:' medical   supplies '},1)).rejects.toMatchObject({statusCode:409});expect(x.calls.at(-1).sql).toBe('ROLLBACK');});
 test('normalizes UOM code separately and preserves name',async()=>{const x=transactionDb(success);await new ItemMasterFoundationService(x.db).createReference('uom',{code:' ea ',name:'Each'},1);const insert=x.calls.find(c=>c.sql.includes('INSERT INTO item_uom'));expect(insert.values).toEqual(['ea','Each','EA',1]);});
 test('deactivates UOM and audits in one transaction',async()=>{const x=transactionDb(success);await new ItemMasterFoundationService(x.db).deactivateReference('uom',9,1);expect(x.calls.map(c=>c.sql)).toEqual(expect.arrayContaining(['BEGIN','COMMIT']));expect(x.calls.some(c=>c.sql.includes('REFERENCE_DEACTIVATED'))).toBe(true);});
 test('audit failure rolls reference mutation back',async()=>{const x=transactionDb(sql=>{if(sql.includes('REFERENCE_CREATED'))throw new Error('audit down');return success(sql)});await expect(new ItemMasterFoundationService(x.db).createReference('categories',{name:'Clinical'},1)).rejects.toThrow('audit down');expect(x.calls.at(-1).sql).toBe('ROLLBACK');});
});

const product={generic_item_id:1,manufacturer:'ignored',manufacturer_id:2,product_name:'Needle',manufacturer_part_number:'MPN',product_uom:'EA',product_uom_id:3};
const catalog={supplier_id:1,approved_product_id:2,supplier_item_code:'SKU',purchasing_uom:'EA',purchasing_uom_id:3,unit_price:'9007199254740993.123456'};
const mutationHandler=(failAction)=>(sql,values)=>{if(failAction&&(sql.includes(failAction)||(values||[]).includes(failAction)))throw new Error('audit down');if(sql.includes('generic_items'))return{rows:[{id:1,base_uom_id:3,inventory_uom_id:3}],rowCount:1};if(sql.includes('item_manufacturers'))return{rows:[{manufacturer_name:'BD'}],rowCount:1};if(sql.includes('item_uom'))return{rows:[{uom_code:'EA'}],rowCount:1};if(sql.includes('approved_products')&&sql.includes('SELECT'))return{rows:[{id:2}],rowCount:1};if(sql.includes('supplier_catalog_items')&&sql.includes('SELECT'))return{rows:[{id:4,...catalog,is_active:true}],rowCount:1};if(sql.includes('RETURNING'))return{rows:[{id:4,...catalog}],rowCount:1};return{rows:[],rowCount:1};};

test('product create and audit commit together',async()=>{const x=transactionDb(mutationHandler());await new ItemMasterFoundationService(x.db).createProduct(product,8);expect(x.calls.map(c=>c.sql)).toEqual(expect.arrayContaining(['BEGIN','COMMIT']));expect(x.calls.some(c=>c.sql.includes('PRODUCT_CREATED'))).toBe(true);});
test('product audit failure rolls product back',async()=>{const x=transactionDb(mutationHandler('PRODUCT_CREATED'));await expect(new ItemMasterFoundationService(x.db).createProduct(product,8)).rejects.toThrow('audit down');expect(x.calls.at(-1).sql).toBe('ROLLBACK');});
test.each([['createCatalog',[catalog,8],'CATALOG_CREATED'],['updateCatalog',[4,catalog,8],'CATALOG_UPDATED'],['deactivateCatalog',[4,8],'CATALOG_DEACTIVATED']])('%s rolls back when audit fails',async(method,args,action)=>{const x=transactionDb(mutationHandler(action));await expect(new ItemMasterFoundationService(x.db)[method](...args)).rejects.toThrow('audit down');expect(x.calls.at(-1).sql).toBe('ROLLBACK');});
test('catalog create commits and preserves large exact decimal',async()=>{const x=transactionDb(mutationHandler());await new ItemMasterFoundationService(x.db).createCatalog(catalog,8);expect(x.calls.at(-1).sql).toBe('COMMIT');const insert=x.calls.find(c=>c.sql.includes('INSERT INTO supplier_catalog_items'));expect(insert.values).toContain('9007199254740993.123456');});