const {validateAddToInventoryPayload}=require('../validators/stockItemIdentityValidator');
const {TRANSITIONS,pagination}=require('../services/stockItemMappingService');
const {DatabaseCapabilityService}=require('../services/databaseCapabilityService');
const requireLegacy=require('../middleware/legacyStockItemCreation');
const suture=require('../services/itemParsers/surgicalSutureParser');const catheter=require('../services/itemParsers/catheterVascularParser');const lab=require('../services/itemParsers/laboratoryProductParser');const pharma=require('../services/itemParsers/pharmaceuticalProductParser');
function middleware(req){return new Promise(resolve=>requireLegacy(req,{},resolve));}
describe('Phase 1B completion',()=>{
 test('rejects duplicate warehouses and nonzero opening stock',()=>expect(()=>validateAddToInventoryPayload({generic_item_id:1,inventory_uom_id:2,warehouse_configurations:[{warehouse_id:3},{warehouse_id:3,initial_quantity:1}]})).toThrow('Request validation failed'));
 test('mapping transition matrix does not permit premature approval',()=>{expect(TRANSITIONS.proposed.has('approved')).toBe(false);expect(TRANSITIONS.review_required.has('approved')).toBe(true);expect(TRANSITIONS.approved.has('rolled_back')).toBe(true);});
 test('bounds mapping pagination',()=>expect(pagination({page:-2,limit:1000})).toEqual({page:1,limit:100,offset:0}));
 test('capability detection caches and fails closed for partial states',async()=>{const db={query:jest.fn().mockResolvedValue({rows:[{table_name:'stock_items'}]})};const service=new DatabaseCapabilityService(db,{ttlMs:1000});expect(await service.detect()).toMatchObject({stockItemIdentityAvailable:true,itemMasterFoundationAvailable:false,stockMappingAvailable:false});await service.detect();expect(db.query).toHaveBeenCalledTimes(1);await expect(service.require('stockMappingAvailable')).rejects.toMatchObject({code:'database_capability_unavailable',statusCode:503});});
 test('capability detection hides lookup failures',async()=>{const service=new DatabaseCapabilityService({query:jest.fn().mockRejectedValue(new Error('secret schema detail'))});expect(await service.detect()).toEqual(expect.objectContaining({stockItemIdentityAvailable:false}));});
 test('legacy approval requires centralized permission and reason',async()=>{expect(await middleware({body:{status:'approved'},user:{permissions:[]}})).toMatchObject({code:'legacy_creation_not_authorized',statusCode:403});expect(await middleware({body:{status:'approved'},user:{permissions:['inventory.legacy-create']}})).toMatchObject({code:'legacy_creation_not_authorized',statusCode:400});expect(await middleware({body:{status:'approved',legacy_creation_reason:'approved exception'},user:{permissions:['inventory.legacy-create']}})).toBeUndefined();});
 test('suture parser emits governed evidence',()=>expect(suture.parse('Sterile absorbable braided nylon suture 3/0 3/8 circle')).toMatchObject({parser_name:'surgical_suture',attributes:{sterility:true,absorbability:'absorbable',construction:'braided',material:'nylon'},source_fragments:expect.any(Object),confidence:expect.any(Object),normalization_rules:expect.any(Object)}));
 test('catheter parser extracts incompatibility attributes',()=>expect(catheter.parse('Sterile double lumen polyurethane catheter 7 Fr 18 gauge')).toMatchObject({attributes:{french_size:7,gauge:18,lumen_count:2,sterility:true}}));
 test('laboratory parser extracts controls and test count',()=>expect(lab.parse('ELISA kit 96 tests 2-8 C lot controlled expiry controlled')).toMatchObject({attributes:{method:'elisa',test_count:96,lot_control:true,expiry_control:true}}));
 test('pharmaceutical parser extracts strength form and route',()=>expect(pharma.parse('amoxicillin 500 mg capsule oral pack of 20')).toMatchObject({attributes:{active_ingredient:'amoxicillin',strength:'500 mg',dosage_form:'capsule',route:'oral',pack_size:20}}));
});