const router=require('express').Router();
const c=require('../controllers/organizationController');
const permit=require('../middleware/requirePermission');
router.get('/tree',c.tree); router.get('/units',c.list); router.get('/options',c.options); router.get('/resolve/:departmentId',c.resolve);
router.get('/head-reconciliation',permit('organization.manage'),c.reconciliation);
router.get('/head-reconciliation/preview',permit('organization.manage'),c.reconciliationPreview);
router.post('/head-reconciliation/bulk',permit('organization.manage'),c.bulkReconcile);
router.get('/units/:id',c.detail); router.get('/units/:id/positions',c.positions);
router.post('/units',permit('organization.manage'),c.create);
router.patch('/units/:id',permit('organization.manage'),c.update);
router.delete('/units/:id',permit('organization.manage'),c.archive);
router.post('/units/:id/move',permit('organization.manage'),c.move);
router.post('/units/:id/head',permit('organization.manage'),c.assignHead);
router.post('/units/:id/reconcile-head',permit('organization.manage'),c.assignLegacyHead);
router.post('/units/:id/reconciliation-decision',permit('organization.manage'),c.resolveReconciliation);
router.post('/units/:id/positions',permit('organization.manage'),c.createPosition);
router.patch('/positions/:positionId',permit('organization.manage'),c.updatePosition);
router.delete('/positions/:positionId',permit('organization.manage'),c.archivePosition);
module.exports=router;