'use strict';
const express=require('express'); const pool=require('../config/db'); const {validateManualActivity}=require('../services/procurementPerformance/procurementActivityService'); const {writeAuditEvent}=require('../services/auditService');
const router=express.Router(); const asyncHandler=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const {assessComplexity}=require('../services/procurementPerformance/procurementComplexityService'); const {verifyValueEvent}=require('../services/procurementPerformance/procurementValueService'); const {createProcurementPerformanceRepository}=require('../repositories/procurementPerformanceRepository');
const {coverageSummary}=require('../services/procurementPerformance/procurementMetricsService');
const requirePermission=(req,code)=>{if(!req.user?.hasPermission?.(code)){const e=new Error('Forbidden');e.statusCode=403;throw e;}};
const scope=(req,alias='pc')=>{const ids=req.user?.data_scopes?.institute_ids; if(Array.isArray(ids)&&ids.length)return {sql:`${alias}.institute_id = ANY($1::int[])`,params:[ids]}; return {sql:`${alias}.institute_id = $1`,params:[req.user.institute_id]};};
router.get('/dashboard',asyncHandler(async(req,res)=>{
  requirePermission(req,'procurement-performance.view');
  const s=scope(req);const params=[...s.params];let where=s.sql;
  if(req.query.date_from){params.push(req.query.date_from);where+=` AND pc.opened_at >= $${params.length}::date`;}
  const domains=['activity','complexity','commercial','logistics','cycle_time'];
  const coverageColumns=domains.map(domain=>`count(*) FILTER (WHERE ${domain}_coverage='FULL')::int AS ${domain}_covered_cases,
    CASE WHEN count(*)=0 OR count(*) FILTER (WHERE ${domain}_coverage='FULL')=0 THEN 'MISSING' WHEN count(*) FILTER (WHERE ${domain}_coverage='FULL')=count(*) THEN 'FULL' ELSE 'PARTIAL' END AS ${domain}_status,
    to_char(CASE WHEN count(*)=0 THEN 0::numeric ELSE 100::numeric*count(*) FILTER (WHERE ${domain}_coverage='FULL')/count(*) END,'FM990.00') AS ${domain}_coverage_percent`).join(',');
  const [result,complexity,pending,coverageResult,activity]=await Promise.all([
    pool.query(`SELECT count(*)::int cases,count(DISTINCT request_id)::int prs,count(DISTINCT requested_item_id)::int requested_items,count(DISTINCT department_id)::int departments FROM procurement_cases pc WHERE ${where}`,params),
    pool.query(`SELECT complexity_class AS class,count(*)::int count,COALESCE(sum(workload_units),0)::int pwu FROM procurement_cases pc WHERE ${where} AND complexity_class IS NOT NULL GROUP BY complexity_class ORDER BY complexity_class`,params),
    pool.query(`SELECT pending_root_cause AS root_cause,count(*)::int count,avg(EXTRACT(EPOCH FROM (NOW()-opened_at)))::bigint average_age_seconds FROM procurement_cases pc WHERE ${where} AND closed_at IS NULL AND pending_root_cause IS NOT NULL GROUP BY pending_root_cause`,params),
    pool.query(`SELECT count(*)::int total_cases,${coverageColumns} FROM procurement_cases pc WHERE ${where}`,params),
    pool.query(`SELECT count(*)::int touches,count(*) FILTER(WHERE activity_type='RFQ_CREATED')::int rfqs,count(*) FILTER(WHERE activity_type='QUOTATION_RECEIVED')::int quotations FROM procurement_case_activities a JOIN procurement_cases pc ON pc.id=a.procurement_case_id WHERE ${where}`,params),
  ]);
  const base=result.rows[0];const coverage=coverageResult.rows[0];
  const summary=domain=>coverageSummary(coverage,domain);
  const unavailable=domain=>({...summary(domain),value:null,status:'not_available',reason:`${domain} denominator is unsafe with incomplete source coverage`});
  res.json({metrics:{
    demand:{prs:base.prs,requested_items:base.requested_items,departments:base.departments,coverage:'FULL'},
    activities:{...activity.rows[0],...summary('activity'),warning:summary('activity').coverage==='PARTIAL'?'Known activities shown; some categories are not comprehensively captured':undefined},
    complexity:{class_mix:complexity.rows,assessed_cases:summary('complexity').covered_cases,unassessed_cases:summary('complexity').total_cases-summary('complexity').covered_cases,...summary('complexity')},
    commercial:unavailable('commercial'),logistics:unavailable('logistics'),cycle_time:unavailable('cycle_time'),
  },pending:pending.rows,buyers:[],highlights:[]});
}));
router.get('/cases/:id',asyncHandler(async(req,res)=>{requirePermission(req,'procurement-performance.view');const s=scope(req);const result=await pool.query(`SELECT pc.*,ri.item_name,ri.specs,r.justification FROM procurement_cases pc JOIN requested_items ri ON ri.id=pc.requested_item_id JOIN requests r ON r.id=pc.request_id WHERE pc.id=$2 AND ${s.sql}`,[...s.params,req.params.id]);if(!result.rowCount){const e=new Error('Case not found');e.statusCode=404;throw e;}const [activities,factors,values]=await Promise.all([pool.query('SELECT * FROM procurement_case_activities WHERE procurement_case_id=$1 ORDER BY activity_at,id',[req.params.id]),pool.query('SELECT * FROM procurement_case_complexity_factors WHERE procurement_case_id=$1 ORDER BY factor_code',[req.params.id]),pool.query('SELECT * FROM procurement_value_events WHERE procurement_case_id=$1 ORDER BY created_at,id',[req.params.id])]);const timeline=activities.rows;res.json({case:result.rows[0],timeline,complexity_facts:factors.rows,touch_count:timeline.filter(x=>['SUPPLIER_CONTACTED','RFQ_SENT','RFQ_RESPONSE_RECEIVED','QUOTATION_RECEIVED','TECHNICAL_EVALUATION_REQUESTED','TECHNICAL_EVALUATION_COMPLETED'].includes(x.activity_type)).length,rfx_references:timeline.filter(x=>x.related_entity_type==='rfx_event'||x.related_entity_type==='rfx_response'),award_references:timeline.filter(x=>x.related_entity_type==='procurement_award'),po_references:timeline.filter(x=>x.related_entity_type==='purchase_order'),commercial_value_events:values.rows,coverage:{activity:result.rows[0].activity_coverage,complexity:result.rows[0].complexity_coverage,commercial:result.rows[0].commercial_coverage,cycle_time:result.rows[0].cycle_time_coverage,logistics:result.rows[0].logistics_coverage}});}));
router.post('/cases/:id/complexity',asyncHandler(async(req,res)=>{requirePermission(req,'procurement-performance.manage');if(['score','class','PWU','pwu','workload_units'].some(k=>Object.hasOwn(req.body||{},k))){const e=new Error('Score, class and PWU are derived and cannot be supplied');e.statusCode=400;throw e;}const s=scope(req);const visible=await pool.query(`SELECT id FROM procurement_cases pc WHERE pc.id=$2 AND ${s.sql}`,[...s.params,req.params.id]);if(!visible.rowCount){const e=new Error('Case not found');e.statusCode=404;throw e;}const result=await assessComplexity({repository:createProcurementPerformanceRepository(),caseId:req.params.id,facts:req.body?.facts,reason:req.body?.reason,actorId:req.user.id,canManage:true});res.json(result);}));
router.post('/cases/:id/value-events/verify',asyncHandler(async(req,res)=>{requirePermission(req,'procurement-performance.verify-savings');const s=scope(req);const visible=await pool.query(`SELECT id FROM procurement_cases pc WHERE pc.id=$2 AND ${s.sql}`,[...s.params,req.params.id]);if(!visible.rowCount){const e=new Error('Case not found');e.statusCode=404;throw e;}const result=await verifyValueEvent({repository:createProcurementPerformanceRepository(),input:{...req.body,procurementCaseId:req.params.id},actor:{id:req.user.id,canVerifySavings:true}});res.status(201).json(result);}));
router.post('/cases/:id/activities',asyncHandler(async(req,res)=>{requirePermission(req,'procurement-performance.manage');const input=validateManualActivity({...req.body,procurement_case_id:req.params.id,actor_id:req.user.id});const s=scope(req);const client=await pool.connect();try{await client.query('BEGIN');const visible=await client.query(`SELECT id FROM procurement_cases pc WHERE pc.id=$2 AND ${s.sql} FOR UPDATE`,[...s.params,req.params.id]);if(!visible.rowCount){const e=new Error('Case not found');e.statusCode=404;throw e;}const row=await client.query(`INSERT INTO procurement_case_activities(procurement_case_id,activity_type,activity_at,actor_id,supplier_id,source,notes) VALUES($1,$2,$3,$4,$5,'MANUAL',$6) RETURNING *`,[req.params.id,input.activity_type,input.activity_at,req.user.id,input.supplier_id||null,input.notes]);await writeAuditEvent({client,entityType:'procurement_case_activity',entityId:row.rows[0].id,action:'MANUAL_ACTIVITY_CREATED',actorUserId:req.user.id,metadata:{procurement_case_id:req.params.id,activity_type:input.activity_type}});await client.query('COMMIT');res.status(201).json(row.rows[0]);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
module.exports=router;