-- PHASE 3 MANUAL MIGRATION. REVIEW AND RUN MANUALLY; application code never executes this file.
-- IMPORTANT: execute only during an inventory-write maintenance window.
-- This script deliberately uses short, independently committed phases. Do not wrap the whole file in BEGIN/COMMIT.
-- A prior version held locks on multiple inventory relations until the final COMMIT and could deadlock with live writers.

-- =============================================================================
-- PHASE 0: PREFLIGHT (read only)
-- Expected: both invalid_* counts are zero. Stop if either is nonzero.
-- =============================================================================
SELECT
  (SELECT count(*) FROM warehouse_stock_levels WHERE quantity < 0) AS invalid_negative_balances,
  (SELECT count(*) FROM inventory_transactions WHERE quantity = 0) AS invalid_zero_movements,
  to_regclass('public.inventory_transaction_allocations') AS existing_allocation_table;

-- Inventory uniqueness inventory: retain this output with the change record.
SELECT CASE WHEN con.oid IS NULL THEN 'index' ELSE 'constraint' END AS object_type,
       idx.relname AS object_name, con.conname AS constraint_name,
       pg_get_indexdef(i.indexrelid) AS definition
  FROM pg_index i
  JOIN pg_class tbl ON tbl.oid = i.indrelid
  JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
  JOIN pg_class idx ON idx.oid = i.indexrelid
  LEFT JOIN pg_constraint con ON con.conindid = i.indexrelid
 WHERE ns.nspname = 'public' AND tbl.relname = 'warehouse_stock_levels'
   AND i.indisunique
 ORDER BY idx.relname;

-- =============================================================================
-- PHASE 1: BALANCE PROJECTION DDL
-- NOWAIT makes this phase fail immediately instead of waiting in a lock cycle.
-- This transaction touches only warehouse_stock_levels and releases its lock at COMMIT.
-- =============================================================================
BEGIN;
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '2min';
LOCK TABLE warehouse_stock_levels IN ACCESS EXCLUSIVE MODE NOWAIT;
ALTER TABLE warehouse_stock_levels ADD COLUMN IF NOT EXISTS stock_status text NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE warehouse_stock_levels ADD COLUMN IF NOT EXISTS batch_number text;
ALTER TABLE warehouse_stock_levels ADD COLUMN IF NOT EXISTS reserved_quantity numeric NOT NULL DEFAULT 0;
ALTER TABLE warehouse_stock_levels DROP CONSTRAINT IF EXISTS warehouse_stock_levels_quantity_nonnegative;
ALTER TABLE warehouse_stock_levels ADD CONSTRAINT warehouse_stock_levels_quantity_nonnegative CHECK (quantity >= 0) NOT VALID;
ALTER TABLE warehouse_stock_levels DROP CONSTRAINT IF EXISTS warehouse_stock_levels_reserved_nonnegative;
ALTER TABLE warehouse_stock_levels ADD CONSTRAINT warehouse_stock_levels_reserved_nonnegative CHECK (reserved_quantity >= 0 AND reserved_quantity <= quantity) NOT VALID;
ALTER TABLE warehouse_stock_levels DROP CONSTRAINT IF EXISTS warehouse_stock_levels_stock_status_check;
ALTER TABLE warehouse_stock_levels ADD CONSTRAINT warehouse_stock_levels_stock_status_check
  CHECK (stock_status IN ('AVAILABLE','QUARANTINE','BLOCKED','RECALLED','DAMAGED','EXPIRED')) NOT VALID;
COMMIT;

-- =============================================================================
-- PHASE 1A: CANONICAL MOVEMENT ALLOCATIONS
-- Existing movements are intentionally left legacy/unallocated. No history is inferred.
-- Snapshot columns preserve the posted identity even if the referenced balance later changes.
-- =============================================================================
BEGIN;
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '2min';
CREATE TABLE IF NOT EXISTS inventory_transaction_allocations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_transaction_id integer NOT NULL REFERENCES inventory_transactions(id) ON DELETE RESTRICT,
  warehouse_stock_level_id integer REFERENCES warehouse_stock_levels(id) ON DELETE RESTRICT,
  warehouse_id integer NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  stock_item_id integer NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT,
  stock_status text NOT NULL CHECK (stock_status IN ('AVAILABLE','QUARANTINE','BLOCKED','RECALLED','DAMAGED','EXPIRED')),
  quantity numeric NOT NULL CHECK (quantity <> 0),
  batch_number text,
  lot_number text,
  serial_number text,
  expiry_date date,
  base_uom text NOT NULL,
  allocation_sequence integer NOT NULL CHECK (allocation_sequence > 0),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (inventory_transaction_id, allocation_sequence)
);
COMMIT;

-- =============================================================================
-- PHASE 2: LEDGER COLUMNS
-- This phase locks only inventory_transactions. The institute FK is added NOT VALID
-- in a separate short phase so its referenced-table lock is not held during column work.
-- =============================================================================
BEGIN;
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '2min';
LOCK TABLE inventory_transactions IN ACCESS EXCLUSIVE MODE NOWAIT;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS movement_type text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS institute_id integer;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS base_uom text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS source_quantity numeric;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS source_uom text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS conversion_factor numeric;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS lot_number text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS stock_status text NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS source_document_type text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS source_document_id text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS source_document_line_id text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS idempotency_key text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS correlation_id text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS reversal_of_movement_id integer;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS reversed_by_movement_id integer;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS command_fingerprint text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS posted_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;
COMMIT;

-- =============================================================================
-- PHASE 3: LEDGER BACKFILL AND CHECKS
-- Existing data is preserved. New engine rows use canonical uppercase movement types.
-- =============================================================================
BEGIN;
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '5min';
LOCK TABLE inventory_transactions IN ACCESS EXCLUSIVE MODE NOWAIT;
UPDATE inventory_transactions SET movement_type = UPPER(transaction_type) WHERE movement_type IS NULL;
ALTER TABLE inventory_transactions ALTER COLUMN movement_type SET NOT NULL;
ALTER TABLE inventory_transactions DROP CONSTRAINT IF EXISTS inventory_transactions_transaction_type_check;
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_transaction_type_check CHECK (transaction_type IN
 ('warehouse','department','transfer','receipt','issue','adjustment','recall','GOODS_RECEIPT','GOODS_RECEIPT_REVERSAL','ISSUE','ISSUE_REVERSAL','TRANSFER_DISPATCH','TRANSFER_RECEIPT','POSITIVE_ADJUSTMENT','NEGATIVE_ADJUSTMENT','QUARANTINE','RELEASE_FROM_QUARANTINE')) NOT VALID;
ALTER TABLE inventory_transactions DROP CONSTRAINT IF EXISTS inventory_transactions_positive_conversion;
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_positive_conversion CHECK (conversion_factor IS NULL OR conversion_factor > 0) NOT VALID;
COMMIT;

-- =============================================================================
-- PHASE 4: FOREIGN KEYS (short transactions, NOT VALID to avoid an immediate table scan)
-- =============================================================================
BEGIN;
SET LOCAL lock_timeout = '3s';
ALTER TABLE inventory_transactions DROP CONSTRAINT IF EXISTS inventory_transactions_institute_id_fkey;
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_institute_id_fkey
  FOREIGN KEY (institute_id) REFERENCES institutes(id) ON DELETE RESTRICT NOT VALID;
COMMIT;
BEGIN;
SET LOCAL lock_timeout = '3s';
ALTER TABLE inventory_transactions DROP CONSTRAINT IF EXISTS inventory_transactions_reversal_of_movement_id_fkey;
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_reversal_of_movement_id_fkey
  FOREIGN KEY (reversal_of_movement_id) REFERENCES inventory_transactions(id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE inventory_transactions DROP CONSTRAINT IF EXISTS inventory_transactions_reversed_by_movement_id_fkey;
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_reversed_by_movement_id_fkey
  FOREIGN KEY (reversed_by_movement_id) REFERENCES inventory_transactions(id) ON DELETE RESTRICT NOT VALID;
COMMIT;

-- =============================================================================
-- PHASE 5: TRANSACTION-COMPATIBLE INDEX BUILDS
-- Supabase SQL Editor may wrap submitted SQL in a transaction, where CONCURRENTLY is illegal.
-- These ordinary builds are therefore maintenance-window operations. SHARE NOWAIT permits reads,
-- rejects active writers immediately, and avoids waiting in a lock cycle.
-- =============================================================================
-- Both queries must return zero rows before creating unique indexes.
SELECT idempotency_key, count(*) FROM inventory_transactions WHERE idempotency_key IS NOT NULL GROUP BY 1 HAVING count(*) > 1;
SELECT reversal_of_movement_id, count(*) FROM inventory_transactions WHERE reversal_of_movement_id IS NOT NULL GROUP BY 1 HAVING count(*) > 1;
-- Report legacy rows whose old batch entity distinguishes otherwise identical canonical identities.
SELECT warehouse_id, stock_item_id, stock_status, batch_number, lot_number, serial_number, expiry_date,
       count(*) AS rows, array_agg(id ORDER BY id) AS balance_ids,
       array_agg(batch_id ORDER BY id) AS legacy_batch_ids
  FROM warehouse_stock_levels
 GROUP BY warehouse_id, stock_item_id, stock_status, batch_number, lot_number, serial_number, expiry_date
HAVING count(*) > 1 AND count(DISTINCT batch_id) > 1;

-- Configuration-like zero rows are safe only as the untracked AVAILABLE identity; review those
-- coexisting with tracked stock because application configuration now lives in replenishment policies.
SELECT z.id AS zero_balance_id, z.warehouse_id, z.stock_item_id,
       array_agg(t.id ORDER BY t.id) AS tracked_balance_ids
  FROM warehouse_stock_levels z
  JOIN warehouse_stock_levels t ON t.warehouse_id = z.warehouse_id
   AND t.stock_item_id = z.stock_item_id AND t.id <> z.id
 WHERE z.quantity = 0 AND z.stock_status = 'AVAILABLE' AND z.batch_number IS NULL
   AND z.lot_number IS NULL AND z.serial_number IS NULL AND z.expiry_date IS NULL
   AND (t.batch_number IS NOT NULL OR t.lot_number IS NOT NULL OR t.serial_number IS NOT NULL OR t.expiry_date IS NOT NULL)
 GROUP BY z.id, z.warehouse_id, z.stock_item_id;


-- Canonical balance identity is warehouse + stock item + status + batch + lot + serial + expiry.
-- These are read-only preflights. If either returns rows, STOP: do not merge or delete data;
-- provide the rows to the inventory owner for manual reconciliation before this migration resumes.
SELECT warehouse_id, stock_item_id, stock_status, batch_number, lot_number, serial_number, expiry_date,
       count(*) AS duplicate_rows, array_agg(id ORDER BY id) AS balance_ids
  FROM warehouse_stock_levels
 GROUP BY warehouse_id, stock_item_id, stock_status, batch_number, lot_number, serial_number, expiry_date
HAVING count(*) > 1;
-- The same stock-item serial cannot be positively AVAILABLE in multiple rows. Serial text may repeat across items.
SELECT stock_item_id, serial_number, count(*) AS duplicate_rows, array_agg(id ORDER BY id) AS balance_ids
  FROM warehouse_stock_levels
 WHERE serial_number IS NOT NULL AND stock_status = 'AVAILABLE' AND quantity > 0
 GROUP BY stock_item_id, serial_number
HAVING count(*) > 1;
-- Must return zero rows. An invalid same-named index makes IF NOT EXISTS skip rebuilding it;
-- have a DBA drop only the reported invalid index before continuing.
SELECT c.relname AS invalid_index
  FROM pg_index x JOIN pg_class c ON c.oid = x.indexrelid
 WHERE NOT x.indisvalid AND c.relname IN
 ('ux_inventory_transactions_idempotency','ux_inventory_transactions_reversal',
  'ix_inventory_ledger_scope','ix_inventory_balance_lock','ux_inventory_balance_identity','ux_available_serial_location');
BEGIN;
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '10min';
LOCK TABLE inventory_transactions IN SHARE MODE NOWAIT;
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_transactions_idempotency ON inventory_transactions(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_transactions_reversal ON inventory_transactions(reversal_of_movement_id) WHERE reversal_of_movement_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_inventory_ledger_scope ON inventory_transactions(institute_id, warehouse_id, stock_item_id, posted_at DESC);
COMMIT;
BEGIN;
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '10min';
LOCK TABLE inventory_transaction_allocations IN SHARE MODE NOWAIT;
CREATE INDEX IF NOT EXISTS ix_inventory_allocations_movement ON inventory_transaction_allocations(inventory_transaction_id, allocation_sequence);
CREATE INDEX IF NOT EXISTS ix_inventory_allocations_balance ON inventory_transaction_allocations(warehouse_stock_level_id);
CREATE INDEX IF NOT EXISTS ix_inventory_allocations_trace ON inventory_transaction_allocations(stock_item_id, batch_number, lot_number, serial_number, expiry_date);
COMMIT;
BEGIN;
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '10min';
LOCK TABLE warehouse_stock_levels IN SHARE MODE NOWAIT;
-- Keep the ordinary pair lookup path after obsolete pair-only uniqueness is removed.
CREATE INDEX IF NOT EXISTS idx_wsl_warehouse_item ON warehouse_stock_levels(warehouse_id, stock_item_id);
CREATE INDEX IF NOT EXISTS ix_inventory_balance_lock ON warehouse_stock_levels(warehouse_id, stock_item_id, stock_status, batch_number, lot_number, serial_number, id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_balance_identity ON warehouse_stock_levels
  (warehouse_id, stock_item_id, stock_status, batch_number, lot_number, serial_number, expiry_date) NULLS NOT DISTINCT;
-- Remove only unique objects whose complete, non-expression, non-partial key is exactly the
-- obsolete ordered pair. Constraint-backed indexes are removed through their constraint.
DO $$
DECLARE candidate record;
BEGIN
  FOR candidate IN
    SELECT idx.relname AS index_name, con.conname AS constraint_name
      FROM pg_index i
      JOIN pg_class tbl ON tbl.oid = i.indrelid
      JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
      JOIN pg_class idx ON idx.oid = i.indexrelid
      LEFT JOIN pg_constraint con ON con.conindid = i.indexrelid AND con.contype IN ('u', 'p')
     WHERE ns.nspname = 'public' AND tbl.relname = 'warehouse_stock_levels'
       AND i.indisunique AND i.indnkeyatts = 2 AND i.indexprs IS NULL AND i.indpred IS NULL
       AND (SELECT array_agg(att.attname ORDER BY key.ordinality)
              FROM unnest(i.indkey::smallint[]) WITH ORDINALITY key(attnum, ordinality)
              JOIN pg_attribute att ON att.attrelid = tbl.oid AND att.attnum = key.attnum
             WHERE key.ordinality <= i.indnkeyatts)
           = ARRAY['warehouse_id','stock_item_id']::name[]
  LOOP
    IF candidate.constraint_name IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.warehouse_stock_levels DROP CONSTRAINT %I', candidate.constraint_name);
    ELSE
      EXECUTE format('DROP INDEX public.%I', candidate.index_name);
    END IF;
  END LOOP;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS ux_available_serial_location ON warehouse_stock_levels(stock_item_id, serial_number)
 WHERE serial_number IS NOT NULL AND stock_status = 'AVAILABLE' AND quantity > 0;
COMMIT;

-- =============================================================================
-- PHASE 6: IMMUTABILITY TRIGGER
-- DELETE is always rejected for engine-posted rows. UPDATE may change only the reversal link.
-- =============================================================================
CREATE OR REPLACE FUNCTION prevent_posted_inventory_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.idempotency_key IS NULL THEN
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  END IF;
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Posted inventory transactions are immutable; post a reversal';
  END IF;
  IF (to_jsonb(NEW) - 'reversed_by_movement_id') IS DISTINCT FROM
     (to_jsonb(OLD) - 'reversed_by_movement_id') OR
     NEW.reversed_by_movement_id IS NOT DISTINCT FROM OLD.reversed_by_movement_id THEN
    RAISE EXCEPTION 'Posted inventory transactions are immutable; only the reversal link may be set';
  END IF;
  IF OLD.reversed_by_movement_id IS NOT NULL OR NEW.reversed_by_movement_id IS NULL THEN
    RAISE EXCEPTION 'Inventory reversal links cannot be cleared or replaced';
  END IF;
  RETURN NEW;
END $$;
BEGIN;
SET LOCAL lock_timeout = '3s';
DROP TRIGGER IF EXISTS trg_inventory_transactions_immutable ON inventory_transactions;
CREATE TRIGGER trg_inventory_transactions_immutable BEFORE UPDATE OR DELETE ON inventory_transactions
FOR EACH ROW EXECUTE FUNCTION prevent_posted_inventory_mutation();
COMMIT;

CREATE OR REPLACE FUNCTION prevent_inventory_allocation_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Inventory transaction allocations are immutable; post a reversal';
END $$;
BEGIN;
SET LOCAL lock_timeout = '3s';
DROP TRIGGER IF EXISTS trg_inventory_transaction_allocations_immutable ON inventory_transaction_allocations;
CREATE TRIGGER trg_inventory_transaction_allocations_immutable BEFORE UPDATE OR DELETE ON inventory_transaction_allocations
FOR EACH ROW EXECUTE FUNCTION prevent_inventory_allocation_mutation();
COMMIT;

-- =============================================================================
-- PHASE 7: VALIDATION (run one statement at a time during a quiet period)
-- Validation uses weaker locks than column DDL but can scan the full table.
-- =============================================================================
ALTER TABLE warehouse_stock_levels VALIDATE CONSTRAINT warehouse_stock_levels_quantity_nonnegative;
ALTER TABLE warehouse_stock_levels VALIDATE CONSTRAINT warehouse_stock_levels_reserved_nonnegative;
ALTER TABLE warehouse_stock_levels VALIDATE CONSTRAINT warehouse_stock_levels_stock_status_check;
ALTER TABLE inventory_transactions VALIDATE CONSTRAINT inventory_transactions_transaction_type_check;
ALTER TABLE inventory_transactions VALIDATE CONSTRAINT inventory_transactions_positive_conversion;
ALTER TABLE inventory_transactions VALIDATE CONSTRAINT inventory_transactions_institute_id_fkey;
ALTER TABLE inventory_transactions VALIDATE CONSTRAINT inventory_transactions_reversal_of_movement_id_fkey;
ALTER TABLE inventory_transactions VALIDATE CONSTRAINT inventory_transactions_reversed_by_movement_id_fkey;

-- Post-validation: all queries must return zero rows/counts.
SELECT idempotency_key, count(*) FROM inventory_transactions WHERE idempotency_key IS NOT NULL GROUP BY 1 HAVING count(*) > 1;
SELECT * FROM warehouse_stock_levels WHERE quantity < 0 OR reserved_quantity < 0 OR reserved_quantity > quantity;
SELECT warehouse_id, stock_item_id, stock_status, batch_number, lot_number, serial_number, expiry_date, count(*)
 FROM warehouse_stock_levels GROUP BY 1,2,3,4,5,6,7 HAVING count(*) > 1;
SELECT stock_item_id, serial_number, count(*) FROM warehouse_stock_levels
 WHERE serial_number IS NOT NULL AND stock_status = 'AVAILABLE' AND quantity > 0 GROUP BY 1,2 HAVING count(*) > 1;
SELECT count(*) AS invalid_institute_references FROM inventory_transactions it
 WHERE it.institute_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM institutes i WHERE i.id = it.institute_id);
SELECT count(*) AS invalid_zero_allocations FROM inventory_transaction_allocations WHERE quantity = 0;
SELECT count(*) AS orphan_movement_allocations FROM inventory_transaction_allocations a
 WHERE NOT EXISTS (SELECT 1 FROM inventory_transactions it WHERE it.id = a.inventory_transaction_id);
SELECT it.id, it.quantity AS movement_quantity, count(a.id) AS allocation_count,
       COALESCE(sum(a.quantity), 0) AS allocation_quantity
  FROM inventory_transactions it
  LEFT JOIN inventory_transaction_allocations a ON a.inventory_transaction_id = it.id
 WHERE it.metadata->>'allocationLedgerVersion' = '1'
 GROUP BY it.id, it.quantity
HAVING count(a.id) = 0 OR COALESCE(sum(a.quantity), 0) <> it.quantity;