-- PHASE 3B MANUAL MIGRATION. REVIEW AND EXECUTE MANUALLY. APPLICATION CODE MUST NEVER RUN THIS FILE.
-- Backup recommendation: take a restorable database backup and retain preflight output.
-- Lock risk: DDL takes brief relation locks; deploy in an inventory-write maintenance window.
SELECT to_regclass('public.inventory_transactions') ledger,
       to_regclass('public.inventory_transaction_allocations') allocations,
       count(*) FILTER (WHERE quantity < 0) negative_balances
FROM warehouse_stock_levels;

BEGIN;
SET LOCAL lock_timeout='3s'; SET LOCAL statement_timeout='2min';
CREATE TABLE IF NOT EXISTS inventory_transfer_movement_links (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transfer_id integer NOT NULL REFERENCES warehouse_transfer_requests(id) ON DELETE RESTRICT,
 transfer_line_id integer NOT NULL REFERENCES warehouse_transfer_items(id) ON DELETE RESTRICT UNIQUE,
 dispatch_movement_id integer NOT NULL REFERENCES inventory_transactions(id) ON DELETE RESTRICT UNIQUE,
 receipt_movement_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
 dispatched_quantity numeric NOT NULL CHECK(dispatched_quantity>0),
 received_quantity numeric NOT NULL DEFAULT 0 CHECK(received_quantity>=0 AND received_quantity<=dispatched_quantity),
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS inventory_transfer_links_transfer_idx ON inventory_transfer_movement_links(transfer_id,transfer_line_id);
ALTER TABLE warehouse_transfer_requests ADD COLUMN IF NOT EXISTS dispatched_at timestamptz;
ALTER TABLE warehouse_transfer_requests ADD COLUMN IF NOT EXISTS dispatched_by integer REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE warehouse_transfer_requests ADD COLUMN IF NOT EXISTS received_at timestamptz;

CREATE TABLE IF NOT EXISTS inventory_reservations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id integer NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
 stock_item_id integer NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT, document_type text NOT NULL, document_id text NOT NULL,
 document_line_id text, quantity numeric NOT NULL CHECK(quantity>0), status text NOT NULL CHECK(status IN('ACTIVE','RELEASED','CONSUMED','EXPIRED','CANCELLED')),
 idempotency_key text NOT NULL UNIQUE, expires_at timestamptz, created_by integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 released_by integer REFERENCES users(id), released_at timestamptz, consumed_by integer REFERENCES users(id), consumed_at timestamptz,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS inventory_reservations_available_idx ON inventory_reservations(warehouse_id,stock_item_id,status) WHERE status='ACTIVE';

CREATE TABLE IF NOT EXISTS inventory_cycle_counts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id integer NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
 status text NOT NULL CHECK(status IN('OPEN','COUNTING','REVIEW','APPROVED','POSTED')), notes text, opened_by integer NOT NULL REFERENCES users(id),
 reviewed_by integer REFERENCES users(id), reviewed_at timestamptz, posted_by integer REFERENCES users(id), posted_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS inventory_cycle_count_lines (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cycle_count_id bigint NOT NULL REFERENCES inventory_cycle_counts(id) ON DELETE RESTRICT,
 stock_item_id integer NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT, warehouse_stock_level_id integer REFERENCES warehouse_stock_levels(id) ON DELETE RESTRICT,
 system_quantity numeric NOT NULL, counted_quantity numeric, variance numeric, counted_by integer REFERENCES users(id), counted_at timestamptz,
 posted_movement_id integer REFERENCES inventory_transactions(id) ON DELETE RESTRICT, posted_at timestamptz, UNIQUE(cycle_count_id,warehouse_stock_level_id)
);
COMMIT;

-- Permission catalog is de-duplicated by its existing unique permission code.
INSERT INTO permissions(code,name,description)
SELECT code,description,description FROM (VALUES
 ('inventory.receive','Receive inventory'),('inventory.issue','Issue inventory'),('inventory.transfer','Transfer inventory'),
 ('inventory.adjust','Adjust inventory'),('inventory.reverse','Reverse inventory'),('inventory.quarantine','Quarantine inventory'),
 ('inventory.release-quarantine','Release quarantined inventory'),('inventory.recall','Recall or block inventory'),
 ('inventory.cycle-count','Count inventory'),('inventory.reserve','Reserve inventory'),
 ('inventory.cross-warehouse','Operate across warehouses'),('inventory.cross-institute','Operate across institutes')
) p(code,description) ON CONFLICT(code) DO NOTHING;

-- Post-validation (all results should be zero except permission_count=12).
SELECT count(*) FILTER(WHERE received_quantity>dispatched_quantity) invalid_transfer_links FROM inventory_transfer_movement_links;
SELECT count(*) FILTER(WHERE status='ACTIVE' AND quantity<=0) invalid_reservations FROM inventory_reservations;
SELECT count(*) permission_count FROM permissions WHERE code=ANY(ARRAY['inventory.receive','inventory.issue','inventory.transfer','inventory.adjust','inventory.reverse','inventory.quarantine','inventory.release-quarantine','inventory.recall','inventory.cycle-count','inventory.reserve','inventory.cross-warehouse','inventory.cross-institute']);
-- Rollback limitation: posted ledger/history must not be deleted. Schema rollback is intentionally not supplied;
-- after live use, disable endpoints and retain these tables for audit. Before first use only, reviewed DROP statements may be prepared separately.