-- PHASE 3B MANUAL MIGRATION. REVIEW AND EXECUTE MANUALLY. APPLICATION CODE MUST NEVER RUN THIS FILE.
-- Backup recommendation: take a restorable database backup and retain preflight output.
-- Lock risk: DDL takes brief relation locks; deploy in an inventory-write maintenance window.
SELECT to_regclass('public.inventory_transactions') ledger,
       to_regclass('public.inventory_transaction_allocations') allocations,
       to_regclass('public.inventory_reservations') reservations,
       count(*) FILTER (WHERE quantity < 0) negative_balances
FROM warehouse_stock_levels;
DO $$ DECLARE invalid_count bigint; BEGIN
 IF to_regclass('public.inventory_reservations') IS NOT NULL THEN
  EXECUTE 'SELECT count(*) FROM inventory_reservations WHERE btrim(idempotency_key)=''''' INTO invalid_count;
  IF invalid_count>0 THEN RAISE EXCEPTION 'Preflight failed: % blank inventory reservation idempotency keys',invalid_count; END IF;
 END IF;
 IF to_regclass('public.inventory_transfer_receipt_operations') IS NOT NULL THEN
  EXECUTE 'SELECT count(*) FROM inventory_transfer_receipt_operations WHERE btrim(idempotency_key)=''''' INTO invalid_count;
  IF invalid_count>0 THEN RAISE EXCEPTION 'Preflight failed: % blank transfer receipt operation idempotency keys',invalid_count; END IF;
 END IF;
END $$;

BEGIN;
SET LOCAL lock_timeout='3s'; SET LOCAL statement_timeout='2min';
CREATE TABLE IF NOT EXISTS inventory_transfer_movement_links (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transfer_id integer NOT NULL REFERENCES warehouse_transfer_requests(id) ON DELETE RESTRICT,
 transfer_line_id integer NOT NULL REFERENCES warehouse_transfer_items(id) ON DELETE RESTRICT UNIQUE,
 dispatch_movement_id integer NOT NULL REFERENCES inventory_transactions(id) ON DELETE RESTRICT UNIQUE,
 receipt_movement_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
 dispatched_quantity numeric NOT NULL CHECK(dispatched_quantity>0),
 received_quantity numeric NOT NULL DEFAULT 0 CHECK(received_quantity>=0 AND received_quantity<=dispatched_quantity),
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS inventory_transfer_links_transfer_idx ON inventory_transfer_movement_links(transfer_id,transfer_line_id);
CREATE TABLE IF NOT EXISTS inventory_transfer_allocation_links (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transfer_id integer NOT NULL REFERENCES warehouse_transfer_requests(id) ON DELETE RESTRICT,
 transfer_line_id integer NOT NULL REFERENCES warehouse_transfer_items(id) ON DELETE RESTRICT,
 dispatch_movement_id integer NOT NULL REFERENCES inventory_transactions(id) ON DELETE RESTRICT,
 dispatch_allocation_id bigint NOT NULL REFERENCES inventory_transaction_allocations(id) ON DELETE RESTRICT,
 dispatched_quantity numeric NOT NULL CHECK(dispatched_quantity>0),
 received_quantity numeric NOT NULL DEFAULT 0 CHECK(received_quantity>=0 AND received_quantity<=dispatched_quantity),
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(dispatch_allocation_id), UNIQUE(transfer_id,transfer_line_id,dispatch_movement_id,dispatch_allocation_id)
);
CREATE INDEX IF NOT EXISTS inventory_transfer_allocation_links_line_idx ON inventory_transfer_allocation_links(transfer_line_id,dispatch_allocation_id);
INSERT INTO inventory_transfer_allocation_links(transfer_id,transfer_line_id,dispatch_movement_id,dispatch_allocation_id,dispatched_quantity,received_quantity)
SELECT l.transfer_id,l.transfer_line_id,l.dispatch_movement_id,a.id,abs(a.quantity),
       CASE WHEN sum(abs(a.quantity)) OVER(PARTITION BY l.transfer_line_id ORDER BY a.allocation_sequence,a.id)-abs(a.quantity)>=l.received_quantity THEN 0
            ELSE least(abs(a.quantity),l.received_quantity-(sum(abs(a.quantity)) OVER(PARTITION BY l.transfer_line_id ORDER BY a.allocation_sequence,a.id)-abs(a.quantity))) END
FROM inventory_transfer_movement_links l JOIN inventory_transaction_allocations a ON a.inventory_transaction_id=l.dispatch_movement_id
ON CONFLICT(dispatch_allocation_id) DO NOTHING;
ALTER TABLE warehouse_transfer_requests ADD COLUMN IF NOT EXISTS dispatched_at timestamptz;
ALTER TABLE warehouse_transfer_requests ADD COLUMN IF NOT EXISTS dispatched_by integer REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE warehouse_transfer_requests ADD COLUMN IF NOT EXISTS received_at timestamptz;
CREATE TABLE IF NOT EXISTS inventory_transfer_receipt_operations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transfer_id integer NOT NULL REFERENCES warehouse_transfer_requests(id) ON DELETE RESTRICT,
 idempotency_key text NOT NULL CHECK(btrim(idempotency_key)<>''),
 receipt_movement_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
 created_by integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(transfer_id,idempotency_key)
);

CREATE TABLE IF NOT EXISTS inventory_reservations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id integer NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
 stock_item_id integer NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT, document_type text NOT NULL, document_id text NOT NULL,
 document_line_id text, quantity numeric NOT NULL CHECK(quantity>0), status text NOT NULL CHECK(status IN('ACTIVE','RELEASED','CONSUMED','EXPIRED','CANCELLED')),
 idempotency_key text NOT NULL UNIQUE CHECK(btrim(idempotency_key)<>''), expires_at timestamptz, created_by integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 released_by integer REFERENCES users(id), released_at timestamptz, consumed_by integer REFERENCES users(id), consumed_at timestamptz,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS inventory_reservations_available_idx ON inventory_reservations(warehouse_id,stock_item_id,status) WHERE status='ACTIVE';
ALTER TABLE inventory_reservations ADD COLUMN IF NOT EXISTS consumed_quantity numeric NOT NULL DEFAULT 0;
DO $$ BEGIN ALTER TABLE inventory_reservations ADD CONSTRAINT inventory_reservations_consumed_check CHECK(consumed_quantity>=0 AND consumed_quantity<=quantity); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS inventory_reservation_allocations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reservation_id bigint NOT NULL REFERENCES inventory_reservations(id) ON DELETE RESTRICT,
 warehouse_stock_level_id integer NOT NULL REFERENCES warehouse_stock_levels(id) ON DELETE RESTRICT,
 reserved_quantity numeric NOT NULL CHECK(reserved_quantity>0),
 consumed_quantity numeric NOT NULL DEFAULT 0 CHECK(consumed_quantity>=0),
 released_quantity numeric NOT NULL DEFAULT 0 CHECK(released_quantity>=0),
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(reservation_id,warehouse_stock_level_id), CHECK(consumed_quantity+released_quantity<=reserved_quantity)
);
CREATE INDEX IF NOT EXISTS inventory_reservation_allocations_reservation_idx ON inventory_reservation_allocations(reservation_id,id);
INSERT INTO inventory_reservation_allocations(reservation_id,warehouse_stock_level_id,reserved_quantity,consumed_quantity,released_quantity)
SELECT r.id,(entry->>'warehouseStockLevelId')::integer,(entry->>'quantity')::numeric,
       CASE WHEN r.status='CONSUMED' THEN (entry->>'quantity')::numeric ELSE 0 END,
       CASE WHEN r.status IN('RELEASED','EXPIRED','CANCELLED') THEN (entry->>'quantity')::numeric ELSE 0 END
FROM inventory_reservations r CROSS JOIN LATERAL jsonb_array_elements(COALESCE(r.metadata->'allocations','[]'::jsonb)) entry
ON CONFLICT(reservation_id,warehouse_stock_level_id) DO NOTHING;
UPDATE inventory_reservations r SET consumed_quantity=quantity WHERE status='CONSUMED' AND consumed_quantity=0;

CREATE TABLE IF NOT EXISTS inventory_reservation_issue_operations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reservation_id bigint NOT NULL REFERENCES inventory_reservations(id) ON DELETE RESTRICT,
 idempotency_key text NOT NULL CHECK(btrim(idempotency_key)<>''),
 requested_quantity numeric NOT NULL CHECK(requested_quantity>0),
 inventory_movement_id integer NOT NULL REFERENCES inventory_transactions(id) ON DELETE RESTRICT UNIQUE,
 created_by integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(reservation_id,idempotency_key)
);
CREATE INDEX IF NOT EXISTS inventory_reservation_issue_operations_reservation_idx
 ON inventory_reservation_issue_operations(reservation_id,created_at);

DO $$ BEGIN ALTER TABLE inventory_reservations ADD CONSTRAINT inventory_reservations_idempotency_key_nonempty CHECK(btrim(idempotency_key)<>''); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE inventory_transfer_receipt_operations ADD CONSTRAINT inventory_transfer_receipt_operations_idempotency_key_nonempty CHECK(btrim(idempotency_key)<>''); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS inventory_cycle_counts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id integer NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
 status text NOT NULL CHECK(status IN('OPEN','COUNTING','REVIEW','APPROVED','POSTED')), notes text, opened_by integer NOT NULL REFERENCES users(id),
 reviewed_by integer REFERENCES users(id), reviewed_at timestamptz, posted_by integer REFERENCES users(id), posted_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS inventory_cycle_count_lines (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cycle_count_id bigint NOT NULL REFERENCES inventory_cycle_counts(id) ON DELETE RESTRICT,
 stock_item_id integer NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT, warehouse_stock_level_id integer REFERENCES warehouse_stock_levels(id) ON DELETE RESTRICT,
 system_quantity numeric NOT NULL, counted_quantity numeric, variance numeric, counted_by integer REFERENCES users(id), counted_at timestamptz,
 posted_movement_id integer REFERENCES inventory_transactions(id) ON DELETE RESTRICT, posted_at timestamptz, UNIQUE(cycle_count_id,warehouse_stock_level_id)
);
COMMIT;

-- Permission catalog is de-duplicated by its existing unique permission code.
INSERT INTO permissions(code,name,description)
SELECT code,description,description FROM (VALUES
 ('inventory.receive','Receive inventory'),('inventory.issue','Issue inventory'),('inventory.transfer','Transfer inventory'),
 ('inventory.adjust','Adjust inventory'),('inventory.reverse','Reverse inventory'),('inventory.quarantine','Quarantine inventory'),
 ('inventory.release-quarantine','Release quarantined inventory'),('inventory.recall','Recall or block inventory'),
 ('inventory.cycle-count','Count inventory'),('inventory.reserve','Reserve inventory'),
 ('inventory.cross-warehouse','Operate across warehouses'),('inventory.cross-institute','Operate across institutes')
) p(code,description) ON CONFLICT(code) DO NOTHING;

-- Post-validation (all results should be zero except permission_count=12).
SELECT count(*) FILTER(WHERE received_quantity>dispatched_quantity) invalid_transfer_links FROM inventory_transfer_movement_links;
SELECT count(*) FILTER(WHERE received_quantity>dispatched_quantity) invalid_transfer_allocations FROM inventory_transfer_allocation_links;
SELECT count(*) FILTER(WHERE quantity<=0 OR consumed_quantity<0 OR consumed_quantity>quantity) invalid_reservations FROM inventory_reservations;
SELECT count(*) FILTER(WHERE consumed_quantity+released_quantity>reserved_quantity) invalid_reservation_allocations FROM inventory_reservation_allocations;
SELECT count(*) FILTER(WHERE reserved_quantity<0 OR reserved_quantity>quantity) invalid_reserved_balances FROM warehouse_stock_levels;
SELECT count(*) invalid_receipt_operations FROM inventory_transfer_receipt_operations WHERE idempotency_key='' OR jsonb_typeof(receipt_movement_ids)<>'array';
SELECT count(*) invalid_issue_operations FROM inventory_reservation_issue_operations
 WHERE btrim(idempotency_key)='' OR requested_quantity<=0;
SELECT count(*) orphaned_issue_operations FROM inventory_reservation_issue_operations o
 LEFT JOIN inventory_reservations r ON r.id=o.reservation_id
 LEFT JOIN inventory_transactions t ON t.id=o.inventory_movement_id
 WHERE r.id IS NULL OR t.id IS NULL;
SELECT count(*) permission_count FROM permissions WHERE code=ANY(ARRAY['inventory.receive','inventory.issue','inventory.transfer','inventory.adjust','inventory.reverse','inventory.quarantine','inventory.release-quarantine','inventory.recall','inventory.cycle-count','inventory.reserve','inventory.cross-warehouse','inventory.cross-institute']);
-- Rollback limitation: posted ledger/history must not be deleted. Schema rollback is intentionally not supplied;
-- after live use, disable endpoints and retain these tables for audit. Before first use only, reviewed DROP statements may be prepared separately.