-- 017: Fixed Asset + vendor-neutral RFID core. MANUAL/PENDING; depends on pending 016 lineage.
-- Never executed by application startup. Absent installs, complete validates/no-ops, partial fails closed.
BEGIN;
DO $migration$
DECLARE expected text[] := ARRAY['asset_number_allocators','asset_categories','asset_locations','assets','asset_movements','asset_tags','rfid_readers','rfid_antennas','rfid_portals','rfid_portal_antennas','rfid_integration_clients','rfid_read_events','rfid_business_events','asset_exceptions']; present int;
BEGIN
 IF EXISTS (SELECT 1 FROM unnest(ARRAY['institutes','users','departments','sections','stock_items','requests','requested_items','purchase_orders','purchase_order_items','goods_receipts','goods_receipt_items','suppliers','custody_records']) d(name) WHERE to_regclass('public.'||name) IS NULL) THEN
   RAISE EXCEPTION 'SQL_017_DEPENDENCY_MISSING_OR_INCOMPATIBLE';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='institutes' AND column_name='id' AND data_type='integer')
 OR NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='custody_records' AND column_name='id') THEN
   RAISE EXCEPTION 'SQL_017_DEPENDENCY_MISSING_OR_INCOMPATIBLE';
 END IF;
 SELECT count(*) INTO present FROM unnest(expected) n WHERE to_regclass('public.'||n) IS NOT NULL;
 IF present NOT IN (0,array_length(expected,1)) THEN RAISE EXCEPTION 'SQL_017_PARTIAL_OR_DRIFTED_SCHEMA'; END IF;
 IF present=0 THEN
  EXECUTE $ddl$
CREATE TABLE asset_number_allocators(institute_id integer PRIMARY KEY REFERENCES institutes(id) ON DELETE RESTRICT,next_value bigint NOT NULL DEFAULT 1 CHECK(next_value>0),prefix varchar(20) NOT NULL DEFAULT 'WICI-A');
CREATE FUNCTION next_asset_number(p_institute_id integer) RETURNS text LANGUAGE plpgsql AS $fn$ DECLARE n bigint;p text; BEGIN INSERT INTO asset_number_allocators(institute_id,next_value) VALUES(p_institute_id,2) ON CONFLICT(institute_id) DO UPDATE SET next_value=asset_number_allocators.next_value+1 RETURNING next_value-1,prefix INTO n,p;RETURN p||'-'||lpad(n::text,6,'0');END $fn$;
CREATE TABLE asset_categories(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),code varchar(40) NOT NULL,name varchar(160) NOT NULL,description text,parent_category_id bigint REFERENCES asset_categories(id),is_active boolean NOT NULL DEFAULT true,created_by integer REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_by integer REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(institute_id,code));
CREATE TABLE asset_locations(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),code varchar(40) NOT NULL,name varchar(160) NOT NULL,location_type varchar(30) NOT NULL CHECK(location_type IN('CAMPUS','BUILDING','FLOOR','DEPARTMENT_AREA','SECTION_AREA','ROOM','STORE','WORKSHOP','EXTERNAL','OTHER')),parent_location_id bigint REFERENCES asset_locations(id),department_id integer REFERENCES departments(id),section_id integer REFERENCES sections(id),is_active boolean NOT NULL DEFAULT true,created_by integer REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_by integer REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(parent_location_id IS DISTINCT FROM id),UNIQUE(institute_id,code));
CREATE TABLE assets(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),asset_number varchar(60) NOT NULL,asset_class varchar(20) NOT NULL CHECK(asset_class IN('CAPITAL','CONTROLLED')),asset_category_id bigint NOT NULL REFERENCES asset_categories(id),description text NOT NULL,generic_item_id bigint,approved_product_id bigint,stock_item_id integer REFERENCES stock_items(id),manufacturer text,model text,serial_number text,finance_asset_number text,acquisition_method varchar(30) NOT NULL CHECK(acquisition_method IN('PURCHASE','DONATION','TRANSFER_IN','LEASE','LOAN','LEGACY','OTHER')),purchase_request_id integer REFERENCES requests(id),requested_item_id integer REFERENCES requested_items(id),purchase_order_id bigint REFERENCES purchase_orders(id),purchase_order_item_id bigint REFERENCES purchase_order_items(id),goods_receipt_id bigint REFERENCES goods_receipts(id),goods_receipt_item_id bigint REFERENCES goods_receipt_items(id),supplier_id integer REFERENCES suppliers(id),acquisition_date date,acquisition_cost numeric(20,4) CHECK(acquisition_cost>=0),currency char(3),capitalization_status varchar(30) NOT NULL DEFAULT 'NOT_ASSESSED',ownership_type varchar(30) NOT NULL CHECK(ownership_type IN('INSTITUTE_OWNED','LEASED','SUPPLIER_OWNED','LOANED','DONATED','OTHER')),owner_name text,responsible_department_id integer REFERENCES departments(id),current_location_id bigint REFERENCES asset_locations(id),condition varchar(30) NOT NULL CHECK(condition IN('NEW','GOOD','FAIR','DAMAGED','UNDER_REPAIR','UNSERVICEABLE','UNKNOWN')),operational_status varchar(30) NOT NULL CHECK(operational_status IN('IN_SERVICE','IN_STORAGE','UNDER_MAINTENANCE','OUT_OF_SERVICE','MISSING','RETIRED','DISPOSED')),reconciliation_status varchar(20) NOT NULL CHECK(reconciliation_status IN('VERIFIED','UNVERIFIED','MISMATCH','MISSING','UNKNOWN')),warranty_expiry date,creation_source varchar(30) NOT NULL CHECK(creation_source IN('PROCUREMENT','LEGACY_RECOVERY','IMPORT','MANUAL','SYSTEM')),notes text,is_active boolean NOT NULL DEFAULT true,created_by integer REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_by integer REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now(),row_version integer NOT NULL DEFAULT 1,UNIQUE(institute_id,asset_number));
CREATE TABLE asset_movements(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),asset_id bigint NOT NULL REFERENCES assets(id),from_department_id integer REFERENCES departments(id),from_location_id bigint REFERENCES asset_locations(id),to_department_id integer REFERENCES departments(id),to_location_id bigint REFERENCES asset_locations(id),movement_type varchar(40) NOT NULL CHECK(movement_type IN('PERMANENT_TRANSFER','TEMPORARY_LOAN','MAINTENANCE_TRANSFER','EXTERNAL_MAINTENANCE','RETURN','STORAGE_TRANSFER','DISPOSAL_TRANSFER','LOCATION_CORRECTION')),requested_by integer NOT NULL REFERENCES users(id),approved_by integer REFERENCES users(id),dispatched_by integer REFERENCES users(id),received_by integer REFERENCES users(id),requested_at timestamptz NOT NULL DEFAULT now(),approved_at timestamptz,dispatched_at timestamptz,received_at timestamptz,expected_return_at timestamptz,actual_return_at timestamptz,reason text NOT NULL,status varchar(30) NOT NULL CHECK(status IN('DRAFT','PENDING_APPROVAL','APPROVED','IN_TRANSIT','RECEIVED','RETURNED','CANCELLED','REJECTED')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE asset_tags(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),asset_id bigint NOT NULL REFERENCES assets(id),tag_type varchar(20) NOT NULL CHECK(tag_type IN('RFID_UHF','RFID_HF','QR','BARCODE','OTHER')),epc varchar(128),tid varchar(256),qr_value text,tag_status varchar(30) NOT NULL CHECK(tag_status IN('PENDING_ENCODING','ACTIVE','DAMAGED','LOST','RETIRED','REPLACED')),is_primary boolean NOT NULL DEFAULT false,installed_at timestamptz,installed_by integer REFERENCES users(id),retired_at timestamptz,retired_by integer REFERENCES users(id),replacement_reason text,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(epc IS NULL OR epc=upper(regexp_replace(epc,'\s','','g'))));
CREATE UNIQUE INDEX asset_tags_active_epc_uq ON asset_tags(institute_id,epc) WHERE epc IS NOT NULL AND tag_status='ACTIVE';CREATE UNIQUE INDEX asset_tags_primary_uhf_uq ON asset_tags(asset_id) WHERE is_primary AND tag_type='RFID_UHF' AND tag_status='ACTIVE';
CREATE TABLE rfid_readers(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),code varchar(60) NOT NULL,name text NOT NULL,reader_type varchar(20) NOT NULL CHECK(reader_type IN('HANDHELD','FIXED')),manufacturer text,model text,serial_number text,device_identifier text NOT NULL,firmware_version text,ip_address inet,location_id bigint REFERENCES asset_locations(id),status varchar(20) NOT NULL DEFAULT 'OFFLINE',last_seen_at timestamptz,configuration jsonb NOT NULL DEFAULT '{}',is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(institute_id,code),UNIQUE(institute_id,device_identifier));
CREATE TABLE rfid_antennas(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),reader_id bigint NOT NULL REFERENCES rfid_readers(id),antenna_port integer NOT NULL CHECK(antenna_port>0),name text NOT NULL,location_id bigint REFERENCES asset_locations(id),antenna_type text,enabled boolean NOT NULL DEFAULT true,configuration jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(reader_id,antenna_port));
CREATE TABLE rfid_portals(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),code varchar(60) NOT NULL,name text NOT NULL,location_id bigint REFERENCES asset_locations(id),portal_type varchar(30) NOT NULL,from_location_id bigint REFERENCES asset_locations(id),to_location_id bigint REFERENCES asset_locations(id),enabled boolean NOT NULL DEFAULT true,configuration jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(institute_id,code));
CREATE TABLE rfid_portal_antennas(portal_id bigint NOT NULL REFERENCES rfid_portals(id) ON DELETE CASCADE,antenna_id bigint NOT NULL REFERENCES rfid_antennas(id) ON DELETE CASCADE,sequence_group integer,direction_role varchar(20) NOT NULL DEFAULT 'UNKNOWN' CHECK(direction_role IN('SIDE_A','SIDE_B','APPROACH','DEPARTURE','UNKNOWN')),sort_order integer NOT NULL DEFAULT 0,PRIMARY KEY(portal_id,antenna_id));
CREATE TABLE rfid_integration_clients(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),client_identifier varchar(100) NOT NULL UNIQUE,credential_hash char(64) NOT NULL,scopes text[] NOT NULL DEFAULT ARRAY['rfid:ingest'],enabled boolean NOT NULL DEFAULT true,last_used_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),CHECK(credential_hash ~ '^[0-9a-f]{64}$'));
CREATE TABLE rfid_read_events(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),integration_client_id bigint NOT NULL REFERENCES rfid_integration_clients(id),epc varchar(128) NOT NULL,tid varchar(256),asset_tag_id bigint REFERENCES asset_tags(id),asset_id bigint REFERENCES assets(id),reader_id bigint NOT NULL REFERENCES rfid_readers(id),antenna_id bigint REFERENCES rfid_antennas(id),portal_id bigint REFERENCES rfid_portals(id),rssi smallint CHECK(rssi BETWEEN -120 AND 0),read_timestamp timestamptz NOT NULL,source_type varchar(20) NOT NULL CHECK(source_type IN('HANDHELD','FIXED','IMPORT','TEST')),external_event_id text,raw_payload jsonb,processing_status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK(processing_status IN('PENDING','PROCESSING','PROCESSED','FAILED','IGNORED')),processing_attempts integer NOT NULL DEFAULT 0,processing_error text,business_event_id bigint,processed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX rfid_read_external_event_uq ON rfid_read_events(integration_client_id,external_event_id) WHERE external_event_id IS NOT NULL;CREATE INDEX rfid_read_epc_time_idx ON rfid_read_events(epc,read_timestamp DESC);CREATE INDEX rfid_read_asset_time_idx ON rfid_read_events(asset_id,read_timestamp DESC) WHERE asset_id IS NOT NULL;CREATE INDEX rfid_read_reader_time_idx ON rfid_read_events(reader_id,read_timestamp DESC);CREATE INDEX rfid_read_portal_time_idx ON rfid_read_events(portal_id,read_timestamp DESC) WHERE portal_id IS NOT NULL;CREATE INDEX rfid_read_processing_idx ON rfid_read_events(processing_status,read_timestamp);
CREATE TABLE rfid_business_events(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),event_type varchar(30) NOT NULL CHECK(event_type IN('ASSET_SEEN','LOCATION_VERIFIED','PORTAL_ENTRY','PORTAL_EXIT','AUTHORIZED_MOVEMENT','UNAUTHORIZED_MOVEMENT','UNKNOWN_TAG')),asset_id bigint REFERENCES assets(id),asset_tag_id bigint REFERENCES asset_tags(id),epc varchar(128) NOT NULL,portal_id bigint REFERENCES rfid_portals(id),reader_id bigint REFERENCES rfid_readers(id),from_location_id bigint REFERENCES asset_locations(id),to_location_id bigint REFERENCES asset_locations(id),direction varchar(20) NOT NULL CHECK(direction IN('ENTERING','EXITING','UNKNOWN')),first_seen_at timestamptz NOT NULL,last_seen_at timestamptz NOT NULL,observation_count integer NOT NULL CHECK(observation_count>0),confidence_score numeric(5,4) CHECK(confidence_score BETWEEN 0 AND 1),authorization_status varchar(20) NOT NULL CHECK(authorization_status IN('AUTHORIZED','UNAUTHORIZED','NOT_APPLICABLE','UNKNOWN')),related_asset_movement_id bigint REFERENCES asset_movements(id),status varchar(20) NOT NULL DEFAULT 'OPEN',metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE rfid_read_events ADD CONSTRAINT rfid_read_business_event_fk FOREIGN KEY(business_event_id) REFERENCES rfid_business_events(id);
CREATE TABLE asset_exceptions(id bigserial PRIMARY KEY,institute_id integer NOT NULL REFERENCES institutes(id),asset_id bigint REFERENCES assets(id),asset_tag_id bigint REFERENCES asset_tags(id),rfid_business_event_id bigint REFERENCES rfid_business_events(id),exception_type varchar(40) NOT NULL CHECK(exception_type IN('UNAUTHORIZED_MOVEMENT','UNKNOWN_TAG','LOCATION_MISMATCH','MISSING_ASSET','DUPLICATE_SERIAL_REVIEW','RFID_CONFIGURATION')),severity varchar(20) NOT NULL CHECK(severity IN('LOW','MEDIUM','HIGH','CRITICAL')),status varchar(20) NOT NULL CHECK(status IN('OPEN','ACKNOWLEDGED','RESOLVED')),detected_at timestamptz NOT NULL,acknowledged_by integer REFERENCES users(id),acknowledged_at timestamptz,resolved_by integer REFERENCES users(id),resolved_at timestamptz,resolution_notes text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(rfid_business_event_id,exception_type));
ALTER TABLE custody_records ADD COLUMN asset_id bigint REFERENCES assets(id) ON DELETE RESTRICT;CREATE INDEX custody_records_asset_idx ON custody_records(asset_id,created_at DESC) WHERE asset_id IS NOT NULL;
$ddl$;
 END IF;
 -- Complete-path contract checks: representative columns/types/nullability plus critical indexes/FKs.
 IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='assets' AND column_name='acquisition_cost' AND data_type='numeric' AND is_nullable='YES') OR NOT EXISTS(SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='asset_tags_active_epc_uq') OR NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='rfid_read_events' AND column_name='read_timestamp' AND data_type='timestamp with time zone') THEN RAISE EXCEPTION '017 drift: critical schema contract mismatch'; END IF;
END $migration$;
COMMIT;