-- MANUAL MIGRATION 033: read-only AI Intelligence audit foundation
BEGIN;

CREATE TABLE IF NOT EXISTS public.ai_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.users(id),
  institute_id INTEGER NOT NULL REFERENCES public.institutes(id),
  session_id TEXT NOT NULL,
  feature TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT,
  status TEXT NOT NULL CHECK (status IN ('STARTED','COMPLETED','FAILED')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ai_tool_executions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interaction_id BIGINT NOT NULL REFERENCES public.ai_interactions(id) ON DELETE CASCADE,
  tool_name TEXT NOT NULL,
  parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  record_count INTEGER CHECK (record_count IS NULL OR record_count >= 0),
  execution_time_ms INTEGER NOT NULL CHECK (execution_time_ms >= 0),
  success BOOLEAN NOT NULL,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_interactions_user_created_idx ON public.ai_interactions(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS ai_interactions_institute_created_idx ON public.ai_interactions(institute_id,created_at DESC);
CREATE INDEX IF NOT EXISTS ai_interactions_session_idx ON public.ai_interactions(session_id);
CREATE INDEX IF NOT EXISTS ai_tool_executions_interaction_idx ON public.ai_tool_executions(interaction_id,created_at);
CREATE INDEX IF NOT EXISTS ai_tool_executions_tool_created_idx ON public.ai_tool_executions(tool_name,created_at DESC);

INSERT INTO public.permissions(code,name,description)
VALUES('ai-intelligence.use','Use AI Intelligence','Use the read-only, audited AI Intelligence assistant within existing data scopes.')
ON CONFLICT(code) DO NOTHING;

COMMIT;